- .github/actions/setup-builder/action.yaml
- .github/workflows/pr_build.yml
- core/src/errors.rs
- pom.xml
- spark/pom.xml
- spark/src/test/scala/org/apache/spark/sql/comet/CometPlanStabilitySuite.scala
This adds some basic CI test pipelines for the project. Basically run tests in the Rust and Java/Scala side within the repo.
Closes #7
> build: Add basic CI test pipelines

- .github/pull_request_template.md
Adding PR template for the repo. This is mostly copied from DataFusion but removed the "user facing" part.
> build: Add PR template

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/pull_request_template.md
Adding a structured ticket templates to describe unpcoming tickets in concise and clear way
> build: Create ticket templates

- dev/scalastyle-config.xml
- pom.xml
- scalafmt.conf
- spark/src/main/scala/org/apache/spark/sql/comet/CometBatchScanExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
This PR re-enables Scala style checker and spotless Maven plugin. Now the CI should fail when the code style is incorrect.
> build: Re-enable Scala style checker and spotless 

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
> fix: Comet sink operator should not have children operators

- .github/actions/java-test/action.yaml
- .github/actions/rust-test/action.yaml
- .github/actions/setup-builder/action.yaml
- .github/actions/setup-macos-builder/action.yaml
- .github/workflows/pr_build.yml
Closes #9.
Add CI for MacOS, including both `x86_64` and `aarch64`. This increases our test coverage and make sure the library is tested in more platforms & architectures. Many people uses Spark on their Mac as well.
Add CI for MacOS, including both `x86_64` and `aarch64`. Since the existing workflows largely share the same logic, this also creates two common actions: `java-test` and `rust-test`, that are used by the main `pr_build` workflows.
> build: Add CI for MacOS (x64 and aarch64)

- .github/workflows/pr_build.yml
Closes #.
With `macos-13`, CI is failing with `libcrypto` related error like following:
```
WARNING: /Users/runner/hostedtoolcache/Java_Adopt_jdk/17.0.10-7/x64/Contents/Home/bin/java is loading libcrypto in an unsafe way
```
For some reason, this error only happens in `macos-13`, and doesn't appear in `macos-12`. This switches to `macos-latest` (`macos-12`) to bypass the error for the time being.
Switch to `macos-latest` for the MacOS (`x86_64`) CI job.
> test: Fix CI failure on libcrypto

- core/src/execution/datafusion/expressions/sum_decimal.rs
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes #46.
If the upstream operator of `HashAggregate` is sorted, `HashAggregate` will try to emit first groups if possible. Our custom `SumDecimalGroupsAccumulator` doesn't support `Emit::First`. So if  `Sort` is followed by `HashAggregate` and there is sum of decimal, the query will fail with:
```
at std::backtrace::Backtrace::create(__internal__:0)                                                                                                                                                                           
at comet::errors::init::{{closure}}(__internal__:0)                                                                                                                                                                            
at …
```
> feat: Support Emit::First for SumDecimalGroupsAccumulator

- common/src/main/java/org/apache/comet/vector/CometMapVector.java
- common/src/main/java/org/apache/comet/vector/CometVector.java
- core/src/execution/proto/expr.proto
- core/src/execution/serde.rs
- core/src/execution/shuffle/map.rs
- core/src/execution/shuffle/mod.rs
- core/src/execution/shuffle/row.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometShuffleSuite.scala
Closes #52.
Contributed internal patch of map shuffle support to Comet.
This patch implements native map accessor for Spark `UnsafeRows`. So columnar shuffle can support nested map field.
Note that deeply nested map is not supported. Due to the design of `MapBuilder`, it has a `K: ArrayBuilder` and `V: ArrayBuilder` as type parameter. It makes hard to construct an arbitrarily nested `MapBuilder`. Actually map of map sounds like a DataType rarely to be used in practice. Maybe we don't need to support it.
Map of list (i.e., `MapBuilder<ListBuilder<...>, ...>`) is not supported too for same reason.
> feat: Nested map support for columnar shuffle

- .github/actions/setup-macos-builder/action.yaml
Closes #41 
Another attempt to fix libcrypto loading issues.  
Currently, CIs are still failing randomly with the following logging, for example:
`WARNING: /Users/runner/hostedtoolcache/Java_Adopt_jdk/17.0.10-7/x64/Contents/Home/bin/java is loading libcrypto in an unsafe way`
install openssl for mac runners and setup corresponding DYLD_LIBRARY_PATH
Existed CI workflow
> build: Fix potential libcrypto lib loading issue for X86 mac runners

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes #38.
This PR adds the support for COUNT(DISTINCT) and similar aggregation functions.
e.g.
```
COUNT(DISTINCT col)
SUM(DISTINCT col)
DISTINCT(col)
```
This PR has the changes for `DISTINCT` aggregation functions
new tests
> feat: Support Count(Distinct) and similar aggregation functions

- .github/actions/java-test/action.yaml
- .github/actions/rust-test/action.yaml
Closes #33 .
Fix maven cache issues
Modify github action files
Verified in the CI runs.
* Rust on Ubuntu: 
* Java on Ubuntu:
* and Java on Mac:
Others CI runs are also cached: https://github.com/apache/arrow-datafusion-comet/actions/runs/7973418479/job/21767221655?pr=48
> build: Fix mvn cache for containerized runners

- core/Cargo.lock
- core/Cargo.toml
- core/src/errors.rs
- core/src/execution/datafusion/expressions/subquery.rs
- core/src/execution/jni_api.rs
- core/src/execution/metrics/utils.rs
- core/src/jvm_bridge/comet_exec.rs
- core/src/jvm_bridge/comet_metric_node.rs
- core/src/jvm_bridge/mod.rs
- core/src/lib.rs
- core/src/parquet/mod.rs
- core/src/parquet/util/jni.rs
- core/src/parquet/util/mod.rs
Closes #49.
Comet currently use `jni-rs` 0.19 which is a bit out-dated. The latest version `0.21.x` provides more improvements including updated safety, better JVM handling, less data copying, etc. On the other hand, it also introduced many API changes. In the long term, we should update to `0.21`+ to get continuous improvements from `jni-rs`.
This PR upgrades `jni-rs` from 0.19 to 0.21. There are many API changes between the two versions and hence many places need to be updated as well in the repo.
Most notably, many method calls in `jni-rs` now requires a `&mut JNIEnv` as parameter, while it used to be `&JNIEnv`.
> feat: Upgrade to `jni-rs` 0.21

- core/src/errors.rs
- core/src/execution/datafusion/expressions/subquery.rs
- core/src/jvm_bridge/mod.rs
Closes #.
Currently when invoking JVM methods from the native side, we do not handle potential exceptions being thrown as part of the process. Ideally, we should catch them and propagate the error to the JVM side to make them visible to the users.
This PR catches exceptions thrown from native side via calling Java methods, and convert them into a `CometError::JavaException` which can then be properly propagated to the JVM.
It is a bit hard to add a unit test for this. I tested it manually instead.
> feat: Handle exception thrown from native side

- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes #.
Running TPCH17 query fails now with columnar shuffle + native execution configs:
```
Couldn't find l_extendedprice#7 in [l_partkey#28L,l_quantity#31]
java.lang.IllegalStateException: Couldn't find l_extendedprice#7 in [l_partkey#28L,l_quantity#31]
```
It is because when we try to find aggregation function inputs for `Final` aggregation, we may get wrong inputs from unrelated `CometHashAggregateExec`. When collecting the `Partial` `CometHashAggregateExec`, we should ensure we don't cross between native and Spark operators.
The internal patch of this PR is originally a bug fix to HashAggregate. Above is its description.
But the just merged patch #42 which is actually a later patch internally and when it is ported it doesn't only copy original commit but latest code. So this fix is …
> test: Ensure traversed operators during finding first partial aggregaion are all native

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #60.
As an optimization of `In` expression, `InSet` is also an expression commonly used. We can support it to unblock more queries.
> feat: Support InSet expression in Comet

- common/src/main/java/org/apache/comet/CometNativeException.java
- core/src/errors.rs
Closes #.
We currently use `CometRuntimeException` for exceptions from both JVM and native side. It's better to have a separate exception class dedicated to the latter.
This introduces another `CometNativeException` dedicated for the latter.
N/A
> feat: Add `CometNativeException` for exceptions thrown from the native side

- core/src/jvm_bridge/mod.rs
Closes #.
We re-throw Java exception which is thrown in JVM during JNI calls. The re-thrown exception includes original exception class name and message but doesn't include cause. We should add the cause as sometimes the cause exception is root cause of the exception.
> feat: Add cause to native exception

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
Plan match issue in CometExecRule
Bug fix
Add default match branch for UnionExec in  CometExecRule
Local test
> fix: Fix the UnionExec match branches in CometExecRule

- common/src/main/scala/org/apache/comet/vector/NativeUtil.scala
- core/src/errors.rs
- core/src/execution/datafusion/planner.rs
- core/src/execution/jni_api.rs
- core/src/execution/operators/scan.rs
- core/src/jvm_bridge/batch_iterator.rs
- core/src/jvm_bridge/mod.rs
- spark/src/main/java/org/apache/comet/CometBatchIterator.java
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/comet/Native.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
Closes #70.
Comet native execution's scan is not started from native but from JVM. Thus Comet scan is push-based instead of pull-based. Although we pull next input batches from child operator in JVM, this new input is not pulled from native but pushed from JVM side.
For an operator like Expand, one input batch can produces multiple output batches. So we cannot pull next batch directly and push into native without peeking it. We need to "peek" into native side and see if any more output batch there. If so, we take it as next output, if not, we pull next input batch and push into native side to execute on it.
If we pull next input from child operator and push it into native without peek, new input will be ignored.
Not only we cannot have consistent way to get input for native operators. The …
> feat: Pull based native execution

- common/src/main/scala/org/apache/comet/vector/NativeUtil.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #72.
Currently except for executing entire query plan by calling `collect`, `show` etc., we don't have a way to collect the result of any Comet operators in the middle of a query. In many cases, we need this feature so we can evaluate a child operator inside another Comet operator. This is also useful for debugging an arbitrary Comet operator.
> feat: Add executeColumnarCollectIterator to CometExec to collect Comet operator result

- common/src/main/scala/org/apache/comet/CometConf.scala
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Closes #81.
This patch adds `CometBroadcastExchangeExec` operator to support broadcasting the result of Comet native operator. This is another step towards supporting `BroadcastHashJoinExec`.
Like Spark `BroadcastExchangeExec`, `CometBroadcastExchangeExec` is not directly called with `doExecute` or `doExecuteColumnar` as other operators. `CometBroadcastExchangeExec` is used when Spark query planner inserts BroadcastDistribution on top of an operator to broadcast it. The upstream operator of `CometBroadcastExchangeExec`, e.g., `BroadcastHashJoinExec`, will call `executeBroadcast` method of `CometBroadcastExchangeExec` to execute the query plan and broadcast its results.
> feat: Add CometBroadcastExchangeExec to support broadcasting the result of Comet native operator

- common/src/main/scala/org/apache/comet/CometConf.scala
- core/benches/row_columnar.rs
- core/src/execution/datafusion/shuffle_writer.rs
- core/src/execution/jni_api.rs
- core/src/execution/shuffle/row.rs
- spark/src/main/java/org/apache/spark/sql/comet/execution/shuffle/SpillWriter.java
- spark/src/main/scala/org/apache/comet/Native.scala
Closes #.
Currently in columnar shuffle, when spills are triggered, Comet will write sorted shuffle data to disk on the native side. As part of the process, it will also do row to columnar conversion, and write out the shuffle data in Arrow format. However, the row to columnar conversion will try to buffer all the shuffle data in memory before writing them to disk. This will potentially cause OOM since spills usually are triggered when memory is under pressure, and the Spark executor may not have enough memory left.
Instead, this PR changes the logic so it no longer buffers all shuffle data in memory. Instead, it immediately flushes out the data to disk once a certain threshold has been reached. A (internal) config parameter `spark.comet.columnar.shuffle.batch.size` is introduced to …
> feat: Reduce memory consumption when writing sorted shuffle files

- core/src/execution/shuffle/row.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometShuffleSuite.scala
Closes #.
This patch adds more unsupported partitioning types. So user applications can fallback to Spark early without running into error.
> feat: Add struct/map as unsupported map key/value for columnar shuffle

- spark/src/main/scala/org/apache/comet/shims/ShimCometBroadcastExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
> fix: Fix compilation error for CometBroadcastExchangeExec

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/ZippedPartitionsRDD.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q28/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q41/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q44/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q54/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q6/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q9/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7/q6/explain.txt
Closes #90.
`CometNativeExec` currently limits the number of input source. That blocks the operators with multiple input sources like join operator. This patch generalizes the input source handling to remove the limitation.
> feat: Support multiple input sources for CometNativeExec

- core/src/execution/datafusion/expressions/temporal.rs
- core/src/execution/kernels/temporal.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
feat: date and timestamp trunc with format array
Closes #93 
Compatibility with Spark
Implements support for the `format` parameter to be an array.
Adds additional unit tests
> feat: Date and timestamp trunc with format array

- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: Avoid exception caused by broadcasting empty result

- spark/src/test/scala/org/apache/spark/sql/CometTPCHQuerySuite.scala
Closes #.
`CometTPCHQuerySuite` currently hides thrown exception during query execution as following Spark test sure. We should expose such exception to help debugging. Note that we already fixed this issue in Spark test suite.
> test: Expose thrown exception when executing query in CometTPCHQuerySuite

- core/src/execution/datafusion/planner.rs
- core/src/execution/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes #.
This PR adds the support for `First/Last` aggregation functions.
This PR has the changes for `First/Last` aggregation functions
new tests
> feat: Support `First`/`Last` aggregate functions

- spark/src/test/scala/org/apache/spark/sql/CometTPCDSQuerySuite.scala
Closes #.
q41 in `CometTPCDSQuerySuite` now can pass with Comet.
Re-enabling q41 in CometTPCDSQuerySuite.
> test: Enable TPCDS q41 in CometTPCDSQuerySuite

- .github/workflows/pr_build.yml
- pom.xml
- spark/src/test/scala/org/apache/spark/sql/CometTPCDSQuerySuite.scala
Closes #101.
We need a CI pipeline that could help us verify Comet query correctness.
This patch enables `CometTPCDSQuerySuite` in CI pipeline that runs TPCDS queries with Comet enabled and checks the results with Spark.
> build: Add CI for TPCDS queries

- core/src/execution/datafusion/shuffle_writer.rs
- core/src/execution/shuffle/row.rs
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: Add num_rows when building RecordBatch

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/shims/ShimCometTakeOrderedAndProjectExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometExecUtils.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #89.
`TakeOrderedAndProjectExec` is a common operator in Spark. In Comet, we should support it to increase query coverage.
> feat: Add support of TakeOrderedAndProjectExec in Comet

- pom.xml
Closes #.
Once the cache of generated tpcds data is used by CI, it will check license header for the files. We should exclude it too.
https://github.com/apache/arrow-datafusion-comet/actions/runs/8034989426/job/21947156559?pr=106
> build: Add tpcds-sf-1 to license header excluded list

- core/src/execution/datafusion/expressions/cast.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #17.
Comet needs to be compatible with Spark on string to boolean casting results.
Currently, Spark supports following boolean values and Comet also needs to compatible with Spark.
```
trueStrings => "t", "true", "y", "yes", "1"
falseStrings => "f", "false", "n", "no", "0"
```
Spark Reference API:
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/StringUtils.scala#L74
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Cast.scala#L585
Note: I will also add `spark.sql.ansi.enabled` case support.
Added new UT.
> fix: Cast string to boolean not compatible with Spark

- .github/actions/setup-macos-builder/action.yaml
- .github/workflows/pr_build.yml
Closes #76 
The previous fix(#55) is not correct as it doesn't propagate `DYLD_LIBRARY_PATH` to the test phase: the `export` statement is executed in a bash shell, which is lost in the new shell command in the test phase. 
Q: If the library path is not correctly set, how does most of the test instances are passed?
A: It turns out that Github's mac runners have inconsistent state of SIP enable status. See https://github.com/actions/runner-images/issues/9091 for related reports, and I also observed related output in my personal debug branch. When SIP is disabled, the X86 mac runners will try to find `libcrypto.dylib` in `/usr/lib/local` on macos-latest(a.k.a: macos-12), which are already linked by homebrew's openssl lib. Below is a screenshot that listing `/usr/local/lib`:
So all the tests …
> fix: Another attempt to fix libcrypto.dylib loading issue

- pom.xml
This PR partially resolves #67 
Currently, CI takes a lot of time to finish. This PR adds the ability to output test duration for each test cases. 
The duration info could be valuable to determine which tests cases to be optimized.
Add stdout reporter for scala test in pom.xml
Manual verification. After this PR, the test cases show duration as follows:
> build: Show time duration for scala test

- dev/copyright/java-header.txt
- dev/copyright/scala-header.txt
- pom.xml
- spark/src/test/scala/org/apache/spark/sql/TPCH.scala
- spark/src/test/scala/org/apache/spark/sql/Tables.scala
- spark/src/test/scala/org/apache/spark/sql/comet/CometPlanStabilitySuite.scala
Closes #.
Add corresponding license header automatically, so developers doesn't need to bother that.
1.  spotless plugin changes to include scala/java license
2. spotless:apply to the existing code
manual verification
> feat: Add license header by spotless:apply automatically

- core/src/execution/datafusion/shuffle_writer.rs
- core/src/execution/datafusion/spark_hash.rs
- spark/src/test/scala/org/apache/comet/exec/CometShuffleSuite.scala
Closes #114.
Native shuffle writer can write dictionary of string but dictionary of binary is not supported. We should add it.
Adding the support of dictionary of binary to native shuffle writer.
> feat: Add dictionary binary to shuffle writer

- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #113.
Comet currently doesn't compile with Spark 3.2 and 3.3 since it uses `Dataset.offset` API, was introduced in https://issues.apache.org/jira/browse/SPARK-39159 which is Spark 3.4. 
This replaces the API usage with a SQL text `OFFSET`, and also mark the test as Spark 3.4+ only.
Manually tested locally with `PROFILES="-Pspark-3.2" make`
> fix: Fix compilation error for Spark 3.2 & 3.3

- .github/workflows/pr_build.yml
Closes #.
MacOS (x86) tests tend to be very slow, especially in Java 8. This moves them to post-commit to improve test time in PRs.
Moves MacOS (x86) CI pipelines to post-commit.
N/A
> test: Move MacOS (x86) pipelines to post-commit

- README.md
Closes #57 .
Quickstart Comet doc section
> doc: Add Quickstart Comet doc section

- core/Cargo.lock
- core/Cargo.toml
- core/benches/common.rs
- core/src/execution/datafusion/expressions/avg.rs
- core/src/execution/datafusion/expressions/avg_decimal.rs
- core/src/execution/datafusion/expressions/scalar_funcs.rs
- core/src/execution/datafusion/expressions/sum_decimal.rs
- core/src/execution/datafusion/planner.rs
- core/src/execution/operators/copy.rs
- core/src/execution/operators/scan.rs
- core/src/parquet/util/test_common/page_util.rs
> build: Upgrade DF to 36.0.0 and arrow-rs 50.0.0

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #.
While working on sort merge join, we encountered some failures in TPCDSQueryTestSuite, they look like:
```
- q14a *** FAILED ***                                                                                                                                       
java.lang.Exception: class [B cannot be cast to class org.apache.spark.sql.catalyst.expressions.aggregate.AggregateMode ([B is in module java.base of load
er 'bootstrap'; org.apache.spark.sql.catalyst.expressions.aggregate.AggregateMode is in unnamed module of loader 'app')                                     Error using configs:                                                                                                                                        
spark.sql.autoBroadcastJoinThreshold=-1 …
```
> fix: Fix corrupted AggregateMode when transforming plan parameters

- common/src/main/java/org/apache/comet/parquet/FileReader.java
- common/src/main/java/org/apache/comet/parquet/ReadOptions.java
Closes #124 
The current parallel reader implementation opens and closes too many connections to the file system. This can be reduced by using a fixed number of connections which does not exceed the number of threads used by the parallel reader
Creates read ranges and assigns consecutive read range to each thread which then opens only one connection to read the ranges it has been assigned.
TPC-DS benchmark queries on AWS/S3.
> feat: Minimize number of connections used by parallel reader

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/shims/ShimCometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometCoalesceExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometCollectLimitExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometExecUtils.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Closes #37 .
Better operator coverage
Add `CometCollectLimitExec`
Add new test and some manual verification.
> feat: Support CollectLimit operator

- spark/src/test/scala/org/apache/spark/sql/CometTPCDSQuerySuite.scala
Closes #.
This patch re-enables TPCDS queries q34 and q64 in `CometTPCDSQuerySuite`.
> build: Re-enable TPCDS queries q34 and q64 in `CometTPCDSQuerySuite`

- spark/src/main/java/org/apache/spark/sql/comet/CometScalarSubquery.java
Closes #.
In `CometScalarSubquery.removeSubquery`, we should make sure the `planId` is still in `subqueryMap` before we go to delete subquery from it. Otherwise, null exception could be thrown.
> fix: Avoid null exception in removeSubquery

- core/src/errors.rs
- core/testdata/backtrace.txt
- core/testdata/stacktrace.txt
Closes #149.
The test has already been implemented, but the golden files were missing.
The missing golden files for running the unit test are added, and the test is re-enabled.
Running the existing test
> test: Add golden files for test

- .github/workflows/pr_build.yml
Closes #75 .
It be useful to add a checker making sure all the PR titles conform to certain format, such as [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
Added a Github action to check PR title and fail the PR if it violates the format. At the moment, the format is simply "type: message" or "type(scope): message". We don't restrict the set of valid types or scopes yet.
> build: Add checker for PR title

- .github/actions/java-test/action.yaml
- .github/workflows/pr_build.yml
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Closes #143.
Software quality and makes sure we don't introduce breaking code that breaks lower Spark versions.
1. fix compile and test failures for old Spark versions
2. modify PR_BUILD.yml to add build and test against Spark 3.2 and 3.3
CI runs.
> build: Support CI pipelines for Spark 3.2, 3.3 and 3.4

- .github/workflows/pr_build.yml
- .github/workflows/pr_title_check.yml
Closes #.
In #151 we checks PR title for both pull-requests and push events. We should only do it for the former. This is a follow-up to fix the behavior.
Fix PR title checker to only trigger on pull requests.
> minor: Only trigger PR title checker on pull requests

- common/src/main/java/org/apache/comet/parquet/BatchReader.java
- core/src/lib.rs
- pom.xml
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometCollectLimitExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCHQuerySuite.scala
Closes #.
When build comet locally, I noticed various warnings. Some are compiler warnings, some are test environment warnings. 
Related code should be refactored for better code quality
Fixes various warning in the compiler and test environments
Manually verify the output of maven test
> chore: Fix warnings in both compiler and test environments

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes #.
Enable `min/max` for `BooleanType`. This is also for `bool_and` and `bool_or` since Spark maps `bool_and` to `min` and `bool_or` to `max`.
new test
> feat: Enable min/max for boolean type

- core/src/execution/datafusion/planner.rs
- core/src/execution/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes #156.
We now bind aggregate expressions to the input of partial aggregate for `HashAggregate` no matter what the mode is.  However, the output of partial aggregate is not same as its input. This incorrect binding will cause unmatched column index. Currently it doesn't expose issues because we don't check the index of bound reference in native side, and the bound columns in aggregate expressions are not used.
However, this is a potential bug and causes some issues when starting to check the index of bound reference.
This patch adds the check of the index of bound reference. The aggregate expressions of final aggregation are not bound to the input of partial aggregation anymore but sent to native side as unbound expressions.
> fix: Final aggregation should not bind to the input of partial aggregation

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
> fix: coalesce should return correct datatype

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes #.
This removes some unnecessary logic in `QueryPlanSerde` when handling `Final` aggregation mode.
After #155, some previous logic on handling `Final` aggregation mode is no longer needed.
> minor: Remove unnecessary logic

- common/src/main/java/org/apache/comet/CometOutOfMemoryError.java
- core/src/errors.rs
- core/src/execution/jni_api.rs
- core/src/execution/memory_pool.rs
- core/src/execution/mod.rs
- core/src/jvm_bridge/comet_task_memory_manager.rs
- core/src/jvm_bridge/mod.rs
- dev/ensure-jars-have-correct-contents.sh
- spark/src/main/java/org/apache/spark/CometTaskMemoryManager.java
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/comet/Native.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCDSQuerySuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCHQuerySuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Closes #34.
Currently Comet uses the default memory pool implementation in DataFusion, which is not aware of the memory manager on the JVM Spark side. Therefore, in the case when a Spark job has both Spark and Comet operators, we'd need to initialize two memory pools separately for each of them, and make sure there is enough budget in them. In addition, since we cannot trigger spilling from native to JVM, or vise versa, the budget need to be large enough which means Comet typically will need to use more memory than Spark does.
Since Spark already has a `UnifiedMemoryManager`, this PR proposes to create a new memory pool implementation which delegate calls to the JVM side `UnifiedMemoryManager`, which serves as the source of truth and serves memory acquisition and release from both JVM and …
> feat: Introduce `CometTaskMemoryManager` and native side memory pool

- core/src/execution/datafusion/expressions/scalar_funcs.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
> fix: attempt to divide by zero error on decimal division

- DEBUGGING.md
Closes #104 .
Adding docs how to extend Comet exceptions by leveraging DF backtraces
> doc: Add initial doc how to expand Comet exceptions

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
> fix: Aggregation without aggregation expressions should use correct result expressions

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
> minor: Make `QueryPlanSerde` warning log less confusing

- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
> fix: Comet native operator can be executed after ReusedExchange

- common/src/main/scala/org/apache/comet/CometConf.scala
- common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/ArrowReaderIterator.scala
Closes #.
Because we have set shuffle batch size in shuffle writer, we don't need to slice shuffle arrays at shuffle reader now.
> refactor: Skipping slicing on shuffle arrays in shuffle reader

- core/src/execution/datafusion/planner.rs
Closes #183 
Leverage `InSet` optimization and improve performance.
1. use datafusion's `in_list` function to create an `InListExpr`
2. optimize use group to make all the datafusion::physical_expr's items into a same group
> fix: Try to convert a static list into a set in Rust

- .github/actions/setup-spark-builder/action.yaml
- .github/workflows/spark_sql_test.yml
- dev/diffs/3.4.2.diff
- pom.xml
Closes #8.
We want to leverage SQL tests in Spark itself to increase our test coverage. We should run them with Comet enabled and make sure the tests pass all the existing checks.
This PR enables us to run SQL tests in Spark itself in Comet. To enable Comet for Spark, a diff file is introduced to patch Spark (version 3.4.2) so that we can:
- Enable Comet in Spark (this is controlled via an environment variable `ENABLE_COMET`)
- Modify certain tests that check certain operators in Spark. For those, we need to change the code and add handling for the equivalent Comet operators too.
- Skip certain tests for unsupported features etc.
> build: Run Spark SQL tests for 3.4

- spark/src/main/java/org/apache/spark/shuffle/sort/CometShuffleExternalSorter.java
Closes #.
We should include `activeSpillerSorter` when calculating peak shuffle memory. Otherwise, the stats will be inaccurate.
> fix: Include active spiller when computing peak shuffle memory

- bin/comet-spark-shell
Closes #.
Enable the comet shuffle manager to activate some native operators for comet spark shell, like native `collectLimitExec`
> feat: enable comet shuffle manager for comet shell

- .github/actions/java-test/action.yaml
- DEVELOPMENT.md
- Makefile
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #.
When developing #179 and `CometRowToColumnar` support, I noticed suspicious errors. It turns out that scalafix in the java-test action rewrites the scala source code and have conflict result with `scalafmt`(used by spotless). It's hard to debug such cases and quite annoying. 
1. enforce scalafix check in CI rather rewriting silently
2. apply `scalafix:scalafix` to the current codebase
3. refine `format` target in Makefile so that developers can format code by simply type: `make format`
4. add a section about code formatting before submit a PR
Existing test and CI checks
> build: Enforce scalafix check in CI

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometNativeShuffleSuite.scala
> fix: CometExecRule should handle ShuffleQueryStage and ReusedExchange

- core/src/execution/datafusion/planner.rs
- core/src/execution/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes #.
Support bitwise  aggregate functions such as `BitAnd`, `BitOr`, `BitXor`
> feat: Support bitwise aggregate functions

- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
> fix: Use `makeCopy` to change relation in `FileSourceScanExec`

- core/src/common/bit.rs
- core/src/execution/datafusion/expressions/bloom_filter_might_contain.rs
- core/src/execution/datafusion/mod.rs
- core/src/execution/datafusion/planner.rs
- core/src/execution/datafusion/spark_hash.rs
- core/src/execution/datafusion/util/mod.rs
- core/src/execution/datafusion/util/spark_bit_array.rs
- core/src/execution/datafusion/util/spark_bloom_filter.rs
- core/src/execution/proto/expr.proto
- pom.xml
- spark/pom.xml
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/shims/ShimQueryPlanSerde.scala
- spark/src/test/spark-3.3-plus/org/apache/comet/CometExpression3_3PlusSuite.scala
- spark/src/test/spark-3.3-plus/org/apache/comet/CometExpressionPlusSuite.scala
Closes #145 
More expr coverage
1. define new expr in proto
2. add SparkBitArray, SparkBloomFilter and BloomFilterMightContain support in the rust side
3. glue code to transform SparkPlan to proto message in JVM side and proto message to physical expr in the native side
4. add tests in both JVM and native side
Note: `BloomFilterMightContain` is only available in Spark 3.3+. So we have to add a separate test directory to test that.
Added new tests.
> feat: Support BloomFilterMightContain expr

- README.md
Closes #.
Shuffle features are added into Comet, but the document is not updated to at least show how to enable it. This patch updates the doc accordingly.
> doc: Update README.md with shuffle configs

- dev/diffs/3.4.2.diff
Closes #.
Certain changes to address comments from https://github.com/apache/arrow-datafusion-comet/pull/166 were somehow excluded in the final commit. This adds them back.
> test: Follow up on Spark 3.4 diff

- Makefile
The logs can include spark and scala versions that don't match the specified profile, which can lead to confusion.  This change includes the profile when running `make clean` to ensure consistency.
Adds `$(PROFILES)` to the `make clean` task
Manually
> build: Avoid confusion by using profile with clean

- common/src/main/java/org/apache/comet/vector/CometDictionary.java
- common/src/main/java/org/apache/comet/vector/CometVector.java
> fix: Remove duplicate byte array allocation for CometDictionary

- core/src/execution/datafusion/expressions/avg_decimal.rs
- core/src/execution/datafusion/expressions/scalar_funcs.rs
- core/src/execution/datafusion/expressions/utils.rs
- core/src/lib.rs
Partially implements #142 .
Int_roundings is not stabalized yet, so I am using the functions provided by num crate. This should help us a bit in migrating to stable rust.
Checked that the github ci passes in my forked repo.
> feat: Remove use of nightly int_roundings feature

- dev/diffs/3.4.2.diff
Closes #195.
Currently the Spark SQL tests do not enable Comet shuffle yet, which causes it to miss quite a lot test coverage. This PR enables shuffle for them. It uses the default shuffle mechanism for now (Comet native shuffle).
I have to disable a few tests that are failing probably due to some bugs in Comet itself. Once this is merged, I'll create separate Github issues to track them.
Enable Comet shuffle for Spark SQL tests.
> test: Enable Comet shuffle in Spark SQL tests

- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
> fix: Remove redundant data copy in columnar shuffle

- core/src/execution/datafusion/expressions/utils.rs
- core/src/execution/kernels/temporal.rs
Closes #.
For builds that fail when there are deprecated warnings, this eliminates build failures.
Replaces deprecated methods with equivalent implementations.
Tested locally
> chore: Replace deprecated temporal methods

- common/src/main/java/org/apache/comet/parquet/TypeUtil.java
Closes #.
UUID is not a SQL type in Spark, but is supported by Iceberg and is mapped to UTF8String. In order to support UUID, we have mapped FIXED_LEN_BYTE_ARRAY to String, but we can only do this if the FIXED_LEN_BYTE_ARRAY is UUID. This PR adds the check so we only map FIXED_LEN_BYTE_ARRAY to String for UUID type.
> fix: Only maps FIXED_LEN_BYTE_ARRAY to String for uuid type

- spark/src/main/java/org/apache/spark/sql/comet/execution/shuffle/CometDiskBlockWriter.java
- spark/src/main/scala/org/apache/spark/shuffle/sort/RowPartition.scala
Closes #.
`RowPartition` allocates memory for storing row addresses and sizes. We call `ArrayBuffer.clear` in `RowPartition.reset` method to clean up the memory allocation. But `ArrayBuffer.clear` doesn't actually deallocate the internal array but just initiates its content.
When we insert elements into the array, it will ensure the array size by doubling the array size every time if the space is not enough. So the array grows. That's said if the arrow grows, `clear` cannot deallocate the array after spilling but still uses unnecessary size of array.
This patch fixes it.
Besides, as we limit columnar batch size in native writer, it doesn't make sense to have JVM row buffer larger than the size. In this patch, it uses `COMET_COLUMNAR_SHUFFLE_BATCH_SIZE` as the initial size of …
> fix: Reduce RowPartition memory allocation

- core/src/execution/datafusion/spark_hash.rs
Closes #.
While developing #226, I noticed the rust implementation of Murmur3Hash doesn't handle float with null input correctly.
This PR fixes that correctness issue.
1. remove extra and wrong hash calculation in `hash_array_primitive_float` macro
2. update unit test to include null input
Updated test
> fix: Remove wrong calculation for Murmur3Hash for float with null input

- spark/src/main/java/org/apache/spark/sql/comet/execution/shuffle/SpillWriter.java
- spark/src/main/scala/org/apache/spark/shuffle/sort/RowPartition.scala
Closes #.
When we export row addresses and sizes to native, they are copied to separate arrays. We should deallocate array buffers after exporting them to reduce memory allocation.
> fix: Deallocate row addresses and size arrays after exporting

- core/src/execution/datafusion/expressions/if_expr.rs
Closes #.
While working on #95, some queries in `CometTPCDSQuerySuite` are failed on incorrect child expression in `IfExpr`. It is because `IfExpr.children` returns incorrect order of children expressions.
> fix: Fix wrong children expression order in IfExpr

- common/src/main/scala/org/apache/comet/CometConf.scala
- common/src/main/scala/org/apache/comet/vector/NativeUtil.scala
- common/src/main/scala/org/apache/comet/vector/StreamReader.scala
- common/src/main/scala/org/apache/spark/sql/comet/execution/arrow/ArrowWriters.scala
- common/src/main/scala/org/apache/spark/sql/comet/execution/arrow/CometArrowConverters.scala
- common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometRowToColumnarExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
This closes #119 and partially resolves #137 
For ease testing with RangeExec operator in the short term.
In the long term, this PR introduce a general way to enable Comet with row-based source exec nodes
1. Introduce `CometRowToColumnarExec` to transform Spark's InternalRow into ColumnarBatch
2. CometArrowConverters and its corresponding ArrowWriters
3. Glue code to apply RowToColumnar transition
1. added tests and existing test code
4. verify plan transition in the Spark UI
> feat: Add CometRowToColumnar operator

- spark/src/test/scala/org/apache/spark/sql/CometTPCHQuerySuite.scala
> test: Enable all remaining TPCH queries

- core/src/execution/datafusion/expressions/avg.rs
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Part of #260.
Comet Final aggregation could be used after Spark partial aggregation if columnar shuffle is enabled. While enabling columnar shuffle by default in #250, some Spark SQL tests with Average aggregation are failed on all null inputs.
It is because Comet Average expression relies on null buffers of input array to decide if the input are all null or not. But Spark Average expression simply relies on `count` value. If all inputs are null values, `count` is 0.
So in above case, Comet Average sees zero values on `sum` and `count` states but it still computes the average `sum / count` instead of returning null. This is different to Spark behavior and we should fix it.
> fix: Average expression in Comet Final should handle all null inputs from partial Spark aggregation

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
> fix: Only trigger Comet Final aggregation on Comet partial aggregation

- README.md
- spark/src/main/java/org/apache/spark/shuffle/sort/CometShuffleExternalSorter.java
Closes #221
The class loader exception that you get when this is not configured is confusing.
Documentation change + wrapped exception pointing to the documentation.
Ran with different launch flags.
> feat: Document the class path / classloader issue with the shuffle manager

- core/src/execution/datafusion/planner.rs
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
> fix: incorrect result on Comet multiple column distinct count

- dev/diffs/3.4.2.diff
Closes #.
Avoid the potential for an UnknownClassException if the Comet jar isn't provided by using a static string
Replace field reference with a static string.
Tested locally
> fix: Avoid using CometConf

- core/src/execution/datafusion/planner.rs
N/A
Remove unwraps from code.
Remove some calls to `unwrap` when calling `create_expr` in the planner.
> chore: Remove some calls to unwrap when calling create_expr in planner.rs

- core/Cargo.lock
- core/Cargo.toml
- core/src/execution/datafusion/operators/expand.rs
- core/src/execution/operators/copy.rs
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
> fix: Fix arrow error when sorting on empty batch

- dev/cargo.config
Closes #.
TOML files use `#` to include comments. The `cargo.config` file currently is using an XML comment.
Update license comment to use `#`
Local run
> fix: Include license using `#` instead of using XML comment

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/shims/ShimQueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: Comet should not translate try_sum to native sum expression

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
> fix: incorrect result with aggregate expression with filter

- pom.xml
- spark/pom.xml
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/spark-3.4/org/apache/comet/exec/CometExec3_4Suite.scala
> fix: Comet should not fail on negative limit parameter

- spark/src/test/scala/org/apache/spark/sql/CometTPCHQueriesList.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCQueryListBase.scala
Closes #.
When running `org.apache.spark.sql.CometTPCHQueriesList` directly from console/IDEA, I notice it failed with NPE. The exception track is showed as below:
```
Exception in thread "main" java.lang.NullPointerException
at org.apache.spark.sql.catalyst.util.package$.resourceToBytes(package.scala:67)
at org.apache.spark.sql.catalyst.util.package$.resourceToString(package.scala:75)
at org.apache.spark.sql.CometTPCQueryListBase.$anonfun$runQueries$1(CometTPCQueryListBase.scala:82)
at org.apache.spark.sql.CometTPCQueryListBase.$anonfun$runQueries$1$adapted(CometTPCQueryListBase.scala:79)
at scala.collection.immutable.List.foreach(List.scala:431)
at org.apache.spark.sql.CometTPCQueryListBase.runQueries(CometTPCQueryListBase.scala:79)
at …
```
> chore: Fix NPE when running CometTPCHQueriesList directly

- core/src/execution/jni_api.rs
Rather than cloning the strings, inserting into map and creating session config from it. The current approach just sets these values manually. This way we avoid creating a few temporary strings and data structures.
Reworked the way datafusion session config is created.
Ensured github ci passes in my forked repo.
> Chore: Cleanup how datafusion session config is created

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: Comet columnar shuffle should not be on top of another Comet shuffle operator

- dev/ensure-jars-have-correct-contents.sh
- pom.xml
- spark/inspections/CometTPCDSQueriesList-results.txt
- spark/inspections/CometTPCHQueriesList-results.txt
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/ExtendedExplainInfo.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/shims/ShimCometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/spark/sql/ExtendedExplainGenerator.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCQueryBase.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCQueryListBase.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Closes #253
Adds addition planning information to a Spark plan which allows us to track the reasons why a Spark plan was not fully converted to Comet.
This PR adds a `CometExplainInfo` structure that is returned by every step of the planning process. Eventually the Structure is attached to the Spark plan being returned by adding it as a Comet specific tag
Additional unit test and tested with all TPCH and TPCDS queries with both Spark 3.4 and Spark 3.4 with the extended plan support.
Also regenerated the `CometTPC*QueriesList` output for both TPCH and TPCDS run against a 1TB dataset.
Note: Since the extended plan support does not exist before Spark 4, the output of `CometTPC*QueriesList` was updated with a build of Spark 3.4 with the feature backported.
> feat: Add extended explain info to Comet plan

- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #303 .
Add all statistics SortMergeJoinExec datafusion node provides.
All available metrics
```
/// Total time for joining probe-side batches to the build-side batches
join_time: metrics::Time,
/// Number of batches consumed by this operator
input_batches: metrics::Count,
/// Number of rows consumed by this operator
input_rows: metrics::Count,
/// Number of batches produced by this operator
output_batches: metrics::Count,
/// Number of rows produced by this operator
output_rows: metrics::Count,   
/// Peak memory used for buffered data.
/// Calculated as sum of peak memory values across partitions
peak_mem_used: metrics::Gauge
```
Unit testing and manual testing
> feat: Improve CometSortMergeJoin statistics

- spark/src/main/scala/org/apache/comet/shims/ShimCometBroadcastHashJoinExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/main/scala/org/apache/spark/sql/comet/plans/AliasAwareOutputExpression.scala
- spark/src/main/scala/org/apache/spark/sql/comet/plans/PartitioningPreservingUnaryExecNode.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: CometExec's outputPartitioning might not be same as Spark expects after AQE interferes

- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/173
CI failure
This PR suppresses decimal random number tests for 3.2 and 3.3 because only Spark 3.4+ has the fix for SPARK-45786
test canged
> test: Suppress decimal random number tests for 3.2 and 3.3

- EXPRESSIONS.md
- core/src/execution/datafusion/expressions/mod.rs
- core/src/execution/datafusion/expressions/variance.rs
- core/src/execution/datafusion/planner.rs
- core/src/execution/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes #.
Supports `VAR_SAMP` and `VAR_POP`
The implementation mostly is the same as the DataFusion's implementation. The reason
we have our own implementation is that DataFusion has UInt64 for state_field `count`,
while Spark has Double for count. Also adding `null_on_divide_by_zero`
to be consistent with Spark's implementation.
> feat: Support Variance

- core/Cargo.toml
- core/src/execution/datafusion/expressions/scalar_funcs.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
This partially closes #205 
More expression coverage for comet
2. add user_defined scalar function: `spark_murmur3_hash` to support murmur3_hash in comet 
3. refine and re-enable md5 expression test.
4. bridge sha2 family functions to Datafusion's built-in scalar functions
5. glue code to convert Spark expression to proto messages
6. new test code
Added new test code
> feat: Support murmur3_hash and sha2 family hash functions

- common/src/main/scala/org/apache/comet/vector/NativeUtil.scala
- common/src/main/scala/org/apache/comet/vector/StreamReader.scala
- common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/ArrowReaderIterator.scala
- common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometBlockStoreShuffleReader.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
Closes #.
There is a memory leak reported by Java Arrow in #324. When looking at the error message for debugging:
```
Memory was leaked by query. Memory leaked: (49152)
Allocator(ROOT) 0/49152/180352/9223372036854775807 (res/actual/peak/limit)
```
I figured that it is hard to know where the allocation comes from. In this PR, I added the source of allocators.
The error message is updated to:
```
Memory was leaked by query. Memory leaked: (49152)                                                                                                                                                                                     
Allocator(StreamReader/shuffle reader) 0/49152/180352/9223372036854775807 (res/actual/peak/limit) …
```
> chore: Add allocation source to StreamReader

- spark/src/main/scala/org/apache/spark/sql/comet/CometMetricNode.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #338 .
Add all statistics HashJoinExec datafusion node provides.
All available metrics
```
/// Total time for collecting build-side of join
pub(crate) build_time: metrics::Time
/// Number of batches consumed by build-side
pub(crate) build_input_batches: metrics::Count,
/// Number of rows consumed by build-side
pub(crate) build_input_rows: metrics::Count,
/// Memory used by build-side in bytes
pub(crate) build_mem_used: metrics::Gauge,
/// Total time for joining probe-side batches to the build-side batches
pub(crate) join_time: metrics::Time,
/// Number of batches consumed by probe-side of this operator
pub(crate) input_batches: metrics::Count,
/// Number of rows consumed by probe-side this operator
pub(crate) input_rows: metrics::Count,
/// Number of batches produced by this …
```
> feat: Improve CometBroadcastHashJoin statistics

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
> fix: SortMergeJoin with unsupported key type should fall back to Spark

- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Part of https://github.com/apache/datafusion-comet/issues/286
Get a better idea of which casts are failing.
- Add test to make sure we have coverage for valid cast combinations
- Add tests to cover all cast operations supported by Spark (for the data types we currently support). Some of the tests are ignored and/or contain TODO statements
- Bring in some framework improvements from pending PRs
New tests
> chore: Add more cast tests and improve test framework

- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Part of https://github.com/apache/datafusion-comet/issues/286
Implement more tests.
- Tests: 104
- Passing: 44
- Ignored: 60
- Implement tests for casting from Date and TimestampType
- Change some tests from `ignore` to `test`
- Update comments in failing tests
- Note that TIMESTAMP_NTZ is not tested yet because that requires some shim work, so will tackle that in a separate PR
> chore: Implement remaining CAST tests

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/spark-3.4/org/apache/comet/exec/CometExec3_4Suite.scala
> fix: limit with offset should return correct results

- docs/source/contributor-guide/development.md
The test-java target does not exist. It should be test-jvm. See Makefile.
> doc: Fix target typo in development.md

- README.md
> doc: Clean up supported JDKs in README

- .github/workflows/spark_sql_test_ansi.yml
- dev/diffs/3.4.2.diff
- pom.xml
Closes #320 .
Setup a  test pipeline to run Spark sql tests with ANSI modeenabled. This is part of the effort to reach full ANSI mode support
Adds a new manual pipeline to run Spark SQL tests with ANSOI mode enabled. 
Sets the environment variable `ENABLE_COMET_ANSI_MODE=true` before running the tests.
Manually run spark tests on command line with Spark 3.4.2.
> build: Add Spark SQL test pipeline with ANSI mode enabled

- docs/source/user-guide/compatibility-template.md
- docs/source/user-guide/compatibility.md
- spark/src/main/scala/org/apache/comet/GenerateDocs.scala
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Part of https://github.com/apache/datafusion-comet/issues/286
- Improved CometCastSuite to assert that cast tests are enabled (and therefore passing) for casts that we report as compatible. This helps ensure that the docs are in sync with the real status. There is likely more that we can do in the future but this is another step closer.
- Update compatibility reporting based on errors found by this new test enhancement
- Added some notes on some of the current incompatibilities so that they are in the documentation
- Improvements to the documentation formatting
- Fixed a regression from a recent PR where the cast float/double to string tests weren't actually running the test
We have a table of compatible casts, followed by:
Tested docs locally.
> feat: Improve cast compatibility tests and docs

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/ExtendedExplainInfo.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
N/A
I think it would be cleaner to store extension info as `Set[String]` rather than using a newline-delimited string, because:
- It removes the need to use `split("\n")` and `mkString("\n")` when manipulating the info
- It ensures that we do not have duplicate entries
- Some refactoring inside `CometSparkSessionExtensions`
Existing tests
> chore: Store EXTENSION_INFO as Set[String] instead of newline-delimited String

- .github/workflows/pr_build.yml
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/388
scalafix check will fail when running Scala 2.13, but is skipped for Scala 2.12.
Add testing of Scala 2.13 along with 2.12 by adding `scala-version` to the matrix.  Explicitly exclude combinations of Spark `3.2` and Scala `2.13`.
Local repo
> build: Add scala-version to matrix

- core/src/execution/datafusion/expressions/cast.rs
- docs/source/user-guide/compatibility.md
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Closes #350 
Improve compatibility with Spark
1) Functionality to "Spark compatible cast" floats, doubles, and decimals to bytes, shorts, ints, and longs
2) Enhanced decimal tests to check for cast edge cases 
CometCastSuite tests pass.
> feat: Implement Spark-compatible CAST from non-integral numeric types to integral types

- core/src/errors.rs
- core/src/execution/datafusion/expressions/cast.rs
- docs/source/user-guide/compatibility.md
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Closes #371 
Improve compatibility with spark
Add custom implementation of CAST from double to timestamp to handle eval_modes if error in casting.
CometCastSuite test case passes.
> feat: Implement Spark-compatible CAST from floating-point/double to decimal

- README.md
- docs/source/contributor-guide/development.md
- pom.xml
As discussed in the Discord channel, some developers have setup that relies on the CLI to execute single tests. 
When using only ScalaTest variables to select a suite, modules that do not use scalaTest but uses maven-surefire-plugin runs all the tests, which is not desirable sometime
> docs: Running ScalaTest suites from the CLI

- core/Cargo.toml
- core/benches/cast_from_string.rs
- core/benches/cast_numeric.rs
N/A
We need benchmarks so that we can evaluate performance impacts of PRs that refactor existing code.
New benchmark and some refactoring for code readability
> chore: Add criterion benchmarks for casting between integer types

- common/src/main/scala/org/apache/comet/CometConf.scala
- spark/src/main/java/org/apache/spark/shuffle/sort/CometShuffleExternalSorter.java
- spark/src/main/java/org/apache/spark/sql/comet/execution/shuffle/CometBypassMergeSortShuffleWriter.java
- spark/src/main/java/org/apache/spark/sql/comet/execution/shuffle/CometDiskBlockWriter.java
- spark/src/main/java/org/apache/spark/sql/comet/execution/shuffle/ShuffleThreadPool.java
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
> chore: Rename some columnar shuffle configs for code consistently

- docs/source/user-guide/compatibility.md
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/DataGenerator.scala
N/A
Start moving random data generation out of `CometCastSuite` and into a class that can be used from other test suites.
- Refactor data generator
- Mark CAST string -> integer as incompatible because the data gen changes exposed new issues
Existing tests
> tests: Move random data generation methods from CometCastSuite to new DataGenerator class

- docs/source/user-guide/installation.md
Closes https://github.com/apache/datafusion-comet/issues/182
We need to specify additional options when launching Spark shell to avoid `ClassNotFoundException`
> docs: Update Spark shell command to include setting additional class path

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Closes #374 .
Improve compatibility with various versions of spark.
Inclusion of trycast while pattern matching expr
All test cases pass.
> feat: Add support for TryCast expression in Spark 3.2 and 3.3

- spark/src/main/spark-3.x/org/apache/comet/shims/ShimCometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Closes #.
The test was not properly done due to a typo
Fixed the typo as well as a string match bug
> test: Fix explain with exteded info comet test

- docs/source/index.rst
- docs/source/user-guide/tuning.md
Part of https://github.com/apache/datafusion-comet/issues/446
> doc: Add Tuning Guide with shuffle configs

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: Reuse CometBroadcastExchangeExec with Spark ReuseExchangeAndSubquery rule

- spark/src/main/spark-3.x/org/apache/comet/shims/ShimCometScanExec.scala
Closes #411 .
the file spark-sql_2.12-3.4.1-amzn-2.jar is a custom version of spark and contains the class org.apache.spark.sql.execution.datasources.FileScanRDD with 2 constructs, one with 6 parameters and the second with 8 parameters. The suggested  workaround  filters out the custom constructor.
> fix: newFileScanRDD should not take constructor from custom Spark versions

- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7/q5a/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7/q5a/simplified.txt
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: fix CometNativeExec.doCanonicalize for ReusedExchangeExec

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
N/A
The current message `Native shuffle is not enabled` is not very informative. There are several configs that need to be set in order for native shuffle to be enabled.
Improve the fallback message to explain why native shuffle is not enabled
> chore: improve fallback message when comet native shuffle is not enabled

- docs/source/contributor-guide/adding-a-new-expression.md
- docs/source/contributor-guide/adding_a_new_expression.md
- docs/source/index.rst
Part of #370 (haven't added anything on cast or aggregate, mainly scalar func)
Make it easier for people to contribute new expressions.
A new markdown file in the contributor guide.
~Not yet, I haven't tried building the docs. Will do before marking this PR ready.~
Built the docs and reviewed the HTML.
> docs: add guide to adding a new expression

- core/src/execution/datafusion/expressions/cast.rs
- docs/source/user-guide/compatibility.md
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/431
Enable cast string to int as a compatible expression.
Also, there is a performance improvement with these changes:
```
cast_string_to_int/cast_string_to_i16
time:   [17.445 µs 17.699 µs 18.019 µs]
change: [-41.405% -40.622% -39.805%] (p = 0.00 < 0.05)
Performance has improved.
```
- Enable tests for cast string to int
- Include original input value in error message instead of trimmed input value
- Simplify code and remove whitespace handling code that was not needed since we already trim the input values
Enabled the tests that were previously disabled
> fix: Enable cast string to int tests and fix compatibility issue

- common/src/main/java/org/apache/comet/parquet/ColumnReader.java
- common/src/main/java/org/apache/comet/vector/CometDecodedVector.java
- common/src/main/java/org/apache/comet/vector/CometDictionaryVector.java
- common/src/main/java/org/apache/comet/vector/CometPlainVector.java
Closes #.
Supports UUID column. This is for Iceberg/Comet integration 
This has been tested locally using iceberg
> feat: Supports UUID column

- core/src/execution/datafusion/expressions/correlation.rs
- core/src/execution/datafusion/expressions/mod.rs
- core/src/execution/datafusion/planner.rs
- core/src/execution/proto/expr.proto
- docs/source/user-guide/expressions.md
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Supports `CORR`
The implementation mostly is the same as the DataFusion's implementation. The reason
we have our own implementation is that DataFusion has UInt64 for state_field count,
while Spark has Double for count. Also adding null_on_divide_by_zero
to be consistent with Spark's implementation.
Closes #.
> feat: correlation support

- core/src/execution/datafusion/expressions/cast.rs
- docs/source/user-guide/compatibility.md
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
> feat: Implement Spark-compatible CAST from String to Date

- spark/src/test/scala/org/apache/comet/DataGenerator.scala
- spark/src/test/scala/org/apache/comet/DataGeneratorSuite.scala
Closes #.
Follow up of #426, supports generating random rows for specified struct type.
Add utility method:  `generateRows` to generate random rows.
N/A.
> feat: Add random row generator in data generator

- core/src/execution/datafusion/spark_hash.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #427 
Bug fixes. When submitting #424, we found there's a bug in spark_hash, which doesn't handle dictionary array correctly.
This PR tries to fix this first.
1. refactor some part of spark_hash.rs and be ready for xxhash64 support
2. unpack dictionary when computing with hashes
3. updated test
This PR currently depends on #426, will rebase once that's merged.
Updated test with randomized input.
> fix: Compute murmur3 hash with dictionary input correctly

- core/src/execution/datafusion/expressions/cast.rs
N/A
We have a catchall block in `cast.rs` that delegates to DataFusion for any cast that we don't have a specific match arm for. This is dangerous because it means we sometimes inadvertently delegate to DataFusion for casts where DataFusion is not compatible with Spark, which can lead to data corruption and hard-to-debug issues such as https://github.com/apache/datafusion-comet/pull/383#issuecomment-2127417428
This PR introduces specific checks so that we only delegate to DataFusion for specific casts and changes the catchall to return an error.
I also improved handling of dictionary-encoded string arrays so that these are unpacked early on and this would have prevented the issue in https://github.com/apache/datafusion-comet/pull/383#issuecomment-2127417428
Existing tests
> fix: Only delegate to DataFusion cast when we know that it is compatible with Spark

- common/src/main/java/org/apache/comet/parquet/ColumnReader.java
> fix: `ColumnReader.loadVector` should initiate `CometDictionary` after re-import arrays

- core/src/execution/datafusion/planner.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #463 
Fix for substring with negative indices produces incorrect results
- negative len in substring(child, start, len) should be >= 0
- test cases
added more test cases that would fail without the change.
> fix: substring with negative indices should produce correct result

- common/src/main/java/org/apache/comet/parquet/ColumnReader.java
- common/src/main/java/org/apache/comet/vector/CometDictionary.java
> fix: Reuse previous CometDictionary Java arrays

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Fallback to Spark for LIKE with custom escape character because currently, LIKE with custom escape character produces incorrect results.
Closes #462 
An `if` clause is introduced for LIKE in `exprToProtoInternal` in `QueryPlanSerde.scala`. It ensures that we fallback to Spark in case LIKE has a custom escape character.
A test was added to `org.apache.comet.CometExpressionSuite`.
> fix: Fallback to Spark for LIKE with custom escape character

- .github/actions/setup-spark-builder/action.yaml
- .github/workflows/spark_sql_test.yml
- dev/diffs/3.4.3.diff
- pom.xml
> build: bump spark version to 3.4.3

- common/src/main/java/org/apache/comet/vector/CometDictionary.java
> chore: Removing copying data from dictionary values into CometDictionary

- dev/diffs/3.4.2.diff
- dev/diffs/3.4.3.diff
Closes #.
To fix `java.lang.ClassNotFoundException: org.apache.spark.CometSparkSessionExtensions` in Hive tests
fixed diffs
existing tests
> test: fix ClassNotFoundException for Hive tests

- core/Cargo.lock
- core/Cargo.toml
- core/src/execution/datafusion/expressions/scalar_funcs.rs
- core/src/execution/datafusion/shuffle_writer.rs
- core/src/execution/datafusion/spark_hash.rs
- docs/source/user-guide/expressions.md
- spark/inspections/CometTPCDSQueriesList-results.txt
- spark/inspections/CometTPCHQueriesList-results.txt
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Part of #205 
Closes #344 
More function coverage
1. include twox-hash as a dep in rust
2. implement xxhash64 related method in rust side
3. glue code to bridge the jvm and rust
New added test.
> feat: Add xxhash64 function support

- core/src/execution/datafusion/expressions/scalar_funcs.rs
- core/src/execution/datafusion/expressions/scalar_funcs/hex.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Related to https://github.com/apache/datafusion-comet/issues/341.
I recently added `unhex` so this PR adds `hex`. It's another scalar function that isn't yet implemented in Comet.
I decided to do a native version here because datafusion has an `to_hex`, but it has different functionality. E.g. `to_hex(-1)` returns `ffffffffffffffff` in datafusion vs `hex(-1)` returning `FFFFFFFFFFFFFFFF` in spark. Spark `hex` also supports strings, but datafusion and postgres do not. I'm happy to start the discussion if it seems it could be merged upstream.
I added the `hex` scalar function.
Yes, I've added tests to the rust side as well as spark sql based tests in scala.
> feat: add hex scalar function

- dev/scalastyle-config.xml
- fuzz-testing/.gitignore
- fuzz-testing/README.md
- fuzz-testing/pom.xml
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/DataGen.scala
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/Main.scala
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/Meta.scala
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/QueryGen.scala
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/QueryRunner.scala
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/Utils.scala
- pom.xml
N/A
Comet Fuzz is a standalone project for generating random data and queries and executing queries against Spark 
with Comet disabled and enabled and checking for incompatibilities.
Although it is a simple tool it has already been useful in finding many bugs, including:
- #479 
- #480 
- #481 
- #482 
- #483 
- #484 
- #485 
- #486 
Comet Fuzz is inspired by the [SparkFuzz](https://ir.cwi.nl/pub/30222) paper from Databricks and CWI.
New standalone `comet-fuzz` project.
Manually tested.
> feat: Add "Comet Fuzz" fuzz-testing utility

- core/src/execution/datafusion/planner.rs
- core/src/execution/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Closes #361 
The updates to `expr.proto` by using enums instead of strings, which prevents potential errors in type interpretation. Modifications in `planner.rs` and `QueryPlanSerde.scala` resolve issues found during compilation and style checks.
- `expr.proto`: Updated the `eval_mode` field from a string type to an enum type (`EvalMode`), with defined values `LEGACY`, `TRY`, and `ANSI`. 
- Rust Code: Modified `ExprStruct::Cast(expr)` in `planner.rs` to handle `eval_mode` as integers corresponding to the new protobuf enum. Updated the match statement to directly convert integers to the EvalMode Rust enum and added error handling for invalid integers.
- `QueryPlanSerde.scala`: 
- Introduced the `stringToEvalMode` function, which converts input strings to `ExprOuterClass.EvalMode` enum …
> feat: Use enum to represent CAST eval_mode in expr.proto

- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
N/A
In the original code, `getNextBatch` called `executeNative` which would create a `Batch` object which is then discarded in `getNextBatch`. This seems like unnecessary overhead even though it is small.
- Remove the interim `Batch` structure. Combine the two methods.
- Add some comments
> chore: Simplify code in CometExecIterator and avoid some small overhead

- core/src/execution/datafusion/expressions/mod.rs
- core/src/execution/datafusion/expressions/unbound.rs
- core/src/execution/datafusion/planner.rs
> chore: Add UnboundColumn to carry datatype for unbound reference

- core/src/execution/datafusion/shuffle_writer.rs
> fix: Input batch to ShuffleRepartitioner.insert_batch should not be larger than configured batch size

- core/src/execution/datafusion/expressions/cast.rs
This resolves one of the overflows discussed in #481
The date_parser was introduced in #383 and is mostly a direct port of code in Spark. In Spark the code uses Scala which has defined integer overflow as two's complement wrapping. 
The proposed fixed is to use `std::num::Wrapping` to get the same wrapping behavior in rust.  The overflown value will still be rejected in a later check that uses `current_segment_digits` so allowing the overflow does not lead to correctness issues.
New and existing unit tests.
> fix: Fix integer overflow in date_parser

- spark/src/main/scala/org/apache/comet/GenerateDocs.scala
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/main/scala/org/apache/comet/expressions/CometEvalMode.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/spark-3.2/org/apache/comet/shims/CometExprShim.scala
- spark/src/main/spark-3.3/org/apache/comet/shims/CometExprShim.scala
- spark/src/main/spark-3.4/org/apache/comet/shims/CometExprShim.scala
- spark/src/main/spark-4.0/org/apache/comet/shims/CometExprShim.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
N/A
Code cleanup.
- Add new `CometEvalMode`
- Use this enum instead of strings
Existing tests
> chore: Add CometEvalMode enum to replace string literals

- core/src/execution/datafusion/expressions/scalar_funcs.rs
- core/src/execution/datafusion/expressions/scalar_funcs/chr.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #479 .
Improves compatibility with apache spark.
Spark compatible implementation of chr scala func.
New test case added to check null character. All test case pass.
> fix: null character not permitted in chr function

- core/src/errors.rs
- core/src/execution/datafusion/planner.rs
- core/src/execution/operators/mod.rs
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
> feat: Fix Comet error message

- core/src/parquet/read/values.rs
Part of https://github.com/apache/datafusion-comet/issues/507
The documentation for `from_raw_parts` states that the the memory must be "properly aligned" and Rust 1.78 added debug assertions that fail if the memory is not properly aligned. We are seeing those assertions fail when we run with Rust 1.78.
https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html
Refactor `make_int_variant_impl` to follow the same pattern as other decode methods and use `read_unaligned` and `write_unaligned` instead of incorrect use of `from_raw_parts`.
> chore: Remove unsafe use of from_raw_parts in Parquet decoder

- core/src/parquet/read/values.rs
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Closes #481.
When spark reads and writes timestamps in parquet file it using the following code: https://github.com/apache/spark/blob/v3.5.1/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/DateTimeUtils.scala#L48-L66 to convert from the Long microsecond timestamp into the julian date + nano second format used in parquet. Because of the logic is implement dates like `290000-12-31T01:00:00+02:00` will lead to overflow both when encoding and decoding the value. Since it for both the reading and writing it "cancels out" and still gives the expected results.  This means the date in year 290000 is stored with a negative day offset, which to me is a bit unexpected. 
This changes the comet code to use wrapping_mul/add to make it explicit that wrapping overflow is expected and …
> fix: Overflow when reading Timestamp from parquet file

- core/src/execution/datafusion/planner.rs
Followup on #184.
Since the [improvement](https://github.com/apache/arrow-datafusion/issues/9530) in DataFusion has been released, we can  remove the special check in Comet.
Remove special check for dictionary type in `in_list` expression 
Existing test.
> chore: Use in_list func directly

- core/benches/hash.rs
- core/src/execution/datafusion/expressions/scalar_funcs.rs
- core/src/execution/datafusion/mod.rs
- core/src/execution/datafusion/spark_hash.rs
Related to https://github.com/apache/datafusion-comet/issues/547
We suspect that we may have a performance issue in xxhash64, so the first step is to add a benchmark to evaluate current performance.
New criterion benchmark
Here are the results from Apple M3 Max.
```
hash/xxhash64/8192      time:   [891.80 µs 893.20 µs 895.25 µs]
Found 12 outliers among 100 measurements (12.00%)
1 (1.00%) low mild
5 (5.00%) high mild
6 (6.00%) high severe
```
> perf: Add criterion benchmark for xxhash64 function

- core/Cargo.lock
- core/Cargo.toml
- core/benches/parquet_decode.rs
- core/src/parquet/read/values.rs
Part of https://github.com/apache/datafusion-comet/issues/557
Parquet decoding when converting between different integral types was using `copy_nonoverlapping` without meeting the precondition that both pointers were properly aligned.
- Rewrite without using `copy_nonoverlapping`
- Added unit tests in Rust
- New tests in Rust
- Existing tests in Scala
> fix: Re-implement some Parquet decode methods without `copy_nonoverlapping`

- core/src/execution/datafusion/expressions/scalar_funcs/chr.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #480 .
improves compatibility with spark
- added support for negative integers while encoding
- also added support for integers larger than 256
Test cases added, all the existing tests pass.
> fix: requested character too large for encoding in chr function

- core/build.rs
I don't think rerun-if-changed supports globs https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed but according to the docs passing a directory should work.
Closes #578.
Quicker build in many cases.
Fixes our build.rs build script to only rebuild when there is actual changes in the proto files.
Running `make core` manually.
> fix: Running cargo build always triggers rebuild

- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
> fix: Avoid recursive call to `canonicalizePlans`

- common/src/main/scala/org/apache/comet/CometConf.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
N/A
We previously disabled xxhash64 by default because TPC-H query 8 would hang when this option was enabled, but the issue was actually caused by a recursion bug in https://github.com/apache/datafusion-comet/issues/576 which is now fixed.
Remove config. Enable xxhash64.
> feat: Enable xxhash64 by default

- core/src/jvm_bridge/batch_iterator.rs
- core/src/jvm_bridge/comet_exec.rs
- core/src/jvm_bridge/comet_metric_node.rs
- core/src/jvm_bridge/comet_task_memory_manager.rs
- core/src/jvm_bridge/mod.rs
The method uses unsafe code to cast a value to a static lifetime using `std::mem::transmute`. But none of users of the method actually seems to depend on this lifetime extention. So to me it seems better to just call the underlying `find_class` method and delete the unsafe code.
We needed to change this code in https://github.com/apache/datafusion-comet/pull/570 when upgrading to rust 1.79 and that highlights that usage of transmute is fishy.
Less code and less unsafe which makes it easier to check and understand that the code is correct.
Removed the method `get_global_jclass`. All users could be changed to use the underlying method `find_class` without further changes.
> refactor: Remove method get_global_jclass

- core/benches/hash.rs
- core/src/execution/datafusion/expressions/scalar_funcs.rs
- core/src/execution/datafusion/expressions/scalar_funcs/hash_expressions.rs
- core/src/execution/datafusion/expressions/scalar_funcs/hex.rs
This is a follow-up as discussed in https://github.com/apache/datafusion-comet/pull/449#discussion_r1608635628
1. hex_encode and wrap_digest_result_as_hex_string goes to hex submodule
2. spark_murmur3_hash and spark_xxhash64 goes to hash_expressions submodule
3. update benchmark and modify test code
Existing tests with one slightly modification.
> chore: Move some utility methods to submodules of scalar_funcs

- core/Cargo.toml
- core/src/execution/datafusion/expressions/subquery.rs
- core/src/execution/memory_pool.rs
- core/src/execution/operators/scan.rs
- core/src/jvm_bridge/batch_iterator.rs
- core/src/jvm_bridge/comet_exec.rs
- core/src/jvm_bridge/comet_metric_node.rs
- core/src/jvm_bridge/mod.rs
Related to https://github.com/apache/datafusion-comet/issues/597
it is better to return `Err` than to call `unwrap`.
> chore: Remove some calls to `unwrap`

- core/src/jvm_bridge/mod.rs
Related to https://github.com/apache/datafusion-comet/issues/597
I noticed in the documentation for JMethodID that we should maintain references to the classes otherwise they could get garbage collected, and I wonder if this may be the root cause of https://github.com/apache/datafusion-comet/issues/597
> chore: Improve JNI safety

- common/src/main/java/org/apache/arrow/c/ArrowImporter.java
- common/src/main/java/org/apache/arrow/c/CometArrayImporter.java
- common/src/main/java/org/apache/arrow/c/CometBufferImportTypeVisitor.java
- core/Cargo.lock
- core/Cargo.toml
> fix: Fix range out of index error with a temporary workaround

- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala
> chore: Use proper constructor of IndexShuffleBlockResolver

- .github/workflows/spark_sql_test.yml
- dev/diffs/3.5.1.diff
- docs/source/contributor-guide/spark-sql-tests.md
- docs/source/index.rst
- pom.xml
Closes https://github.com/apache/datafusion-comet/issues/589
- Add diff file for 3.5.1
- Enable Spark SQL tests for 3.5.1 in CI
- Add documentation on how I did this
> feat: Enable Spark SQL tests for Spark 3.5.1

- core/src/execution/datafusion/planner.rs
- core/src/execution/proto/operator.proto
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Co-authored-by: comphead <comphead@ukr.net>
Co-authored-by: Huaxin Gao [huaxin_gao@apple.com](mailto:huaxin_gao@apple.com)
Closes #.
This PR has the initial changes for window function. Currently, only `Count`, `Max` and `Min` are supported. In the following PRs, we will add all the other aggregate functions support, built-in window function support, ignoreNulls support, ect.
> feat: Initial support for Window function

- core/src/execution/datafusion/expressions/scalar_funcs.rs
- docs/source/user-guide/expressions.md
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #611.
Support IsNaN expression, so that more expressions can be executed natively.
Adds support for IsNaN. The implemenatation is done using a custom scalar function. The reason we do not use the datafusion builtin is that we need to return false for null values.
New tests in CometExpressionSuite.
> feat: IsNaN expression in Comet

- spark/src/main/scala/org/apache/spark/sql/comet/CometCollectLimitExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
N/A
I was comparing Spark vs Comet in Spark UI and found the metrics confusing to compare.
- Rename "shuffle read elapsed compute at native" to "shuffle native code time" because the timer is used to measure (almost) all execution time in the native code, including reading, repartitioning, and writing.
Tested manually
> chore: Rename shuffle write metric

- core/src/execution/datafusion/expressions/create_named_struct.rs
- core/src/execution/datafusion/expressions/mod.rs
- core/src/execution/datafusion/planner.rs
- core/src/execution/proto/expr.proto
- docs/source/user-guide/expressions.md
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #619.
Add support for one more expression.
Adds a custom `PhysicalExpr` that implements the behavior of the CreateNamedStruct in spark.
New unit tests in the CometExpressionSuite.
> feat: Add support for CreateNamedStruct

- core/src/execution/datafusion/planner.rs
N/A
Minor code cleanup. We can check the type of an `Any` using `is::<T>()` instead of actually attempting to perform the downcast first.
> minor: replace .downcast_ref::<T>().is_some() with .is::<T>()

- .github/actions/rust-test/action.yaml
- native/Cargo.lock
- native/core/Cargo.toml
Closes #.
Removing unused dependencies. Better for streamlining the project and frees up space. 
Adding `cargo machete` to CI.
Build succeeds. All tests pass.
> feat: add cargo machete to remove udeps

- native/Cargo.lock
- native/core/Cargo.toml
- native/core/src/execution/datafusion/expressions/abs.rs
- native/core/src/execution/datafusion/expressions/avg.rs
- native/core/src/execution/datafusion/operators/expand.rs
- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/datafusion/shuffle_writer.rs
- native/core/src/execution/operators/copy.rs
- native/core/src/execution/operators/scan.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
N/A
DataFusion is preparing to release version 40.0.0 so I would like to make sure that we are testing with the latest prior to the release.
Use a very recent revision of the official DataFusion repo.
> feat: Upgrade to DataFusion 40.0.0-rc1

- dev/diffs/4.0.0-preview1.diff
Addresses part of https://github.com/apache/datafusion-comet/issues/551 
This addresses the following tests which require SubqueyBroadcastExec to be implemented
- partition pruning in broadcast hash joins with aliases (appears twice)
- partition pruning in broadcast hash joins (appears twice)
- different broadcast subqueries with identical children
- SPARK-32817: DPP throws error when the broadcast side is empty
- SPARK-36444: Remove OptimizeSubqueries from batch of PartitionPruning
- SPARK-38674: Remove useless deduplicate in SubqueryBroadcastExec
- SPARK-39338: Remove dynamic pruning subquery if pruningKey's references is empty
- SPARK-39217: Makes DPP support the pruning side has Union
- join with ordering requirement
> fix: Tag ignored tests that require SubqueryBroadcastExec

- native/Cargo.lock
- native/Cargo.toml
- native/core/Cargo.toml
- native/core/src/execution/datafusion/expressions/utils.rs
- native/core/src/execution/datafusion/planner.rs
- native/spark-expr/src/abs.rs
- native/spark-expr/src/if_expr.rs
- native/spark-expr/src/lib.rs
- native/utils/Cargo.toml
- native/utils/README.md
- native/utils/src/lib.rs
Part of https://github.com/apache/datafusion-comet/issues/630
Move another Spark expr into the spark-expr crate
- Mostly just moving code around. No functional changes.
- Created new `datafusion-comet-utils` crate
> feat: Move `IfExpr` to `spark-expr` crate

- native/Cargo.lock
- native/Cargo.toml
- native/core/Cargo.toml
- native/core/src/errors.rs
- native/core/src/execution/datafusion/expressions/cast.rs
- native/core/src/execution/datafusion/expressions/mod.rs
- native/core/src/execution/datafusion/expressions/negative.rs
- native/spark-expr/Cargo.toml
- native/spark-expr/src/abs.rs
- native/spark-expr/src/error.rs
- native/spark-expr/src/lib.rs
Part of https://github.com/apache/datafusion-comet/issues/630
These changes are extracted from the larger WIP PR https://github.com/apache/datafusion-comet/pull/654 and are a first step to being able to move the `cast` expression to the new `spark-expr` crate.
- Move `SparkError` into its own source file
- Move variants `ArithmeticOverflow`, `CastInvalidValue`, `CastOverFlow`, and `NumericValueOutOfRange` from `CometError` to `SparkError`
- Add new `CometError::Spark(SparkError)` variant
Existing tests
> chore: Refactoring of CometError/SparkError

- native/core/src/execution/datafusion/expressions/strings.rs
- native/core/src/execution/datafusion/planner.rs
- native/spark-expr/src/lib.rs
- native/spark-expr/src/temporal.rs
N/A
By convention, DataFusion uses a suffix of `Expr` for implementations of `PhysicalExpr`, and `Exec` for implementations of `ExecutionPlan`.
We currently have some expressions with a suffix of `Exec`, which may cause some confusion. I propose that we rename these before the 0.1.0 release, especially since we are providing a public API in the new `datafusion-comet-spark-expr` crate.
Just renaming some expressions.
> chore: Change suffix on some expressions from Exec to Expr

- dev/diffs/3.5.1.diff
- spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala
Part of https://github.com/apache/datafusion-comet/issues/617
- Fix some issues in the CometScan shim for 3.5.1 and enable some Spark tests
> chore: Fix some regressions with Spark 3.5.1

- fuzz-testing/README.md
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/DataGen.scala
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/Main.scala
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/Meta.scala
- fuzz-testing/src/main/scala/org/apache/comet/fuzz/QueryGen.scala
> chore: Improve fuzz testing coverage

- kube/Dockerfile
Closes #643 .
Create a Comet dockerfile to create a Spark based image with integrated Comet jar
> Create Comet docker file

- pom.xml
Closes #.
After we changed native code path, I got this warning when building Comet locally:
```
[WARNING] Files with unapproved licenses:
native/core/src/execution/generated/spark.spark_operator.rs
native/core/src/execution/generated/spark.spark_partitioning.rs
native/core/src/execution/generated/spark.spark_expression.rs
```
> build: Exclude protobug generated codes from apache-rat check

- docs/source/contributor-guide/benchmarking.md
N/A
I used the wrong formula for calculating the speedups when updating the benchmark results and they were inconsistent with how we previously stated them and how we calculate them in the charts.
This PR updates them based on the following math:
TPC-DS:
```
>>> round((1973/1608)-1, 2) * 100
23.0
```
TPC-H:
```
>>> round((626/407)-1, 2) * 100
54.0
```
> docs: Update percentage speedups in benchmarking guide

- docs/source/user-guide/tuning.md
Closes https://github.com/apache/datafusion-comet/issues/595
> doc: Add memory tuning section to user guide

- .github/actions/setup-spark-builder/action.yaml
- .github/workflows/spark_sql_test.yml
- .github/workflows/spark_sql_test_ansi.yml
- CHANGELOG.md
- common/pom.xml
- dev/changelog/0.1.0.md
- dev/release/README.md
- dev/release/verify-release-candidate.sh
- dev/release/verifying-release-candidates.md
- docs/source/user-guide/installation.md
- fuzz-testing/pom.xml
- native/Cargo.lock
- native/Cargo.toml
- native/core/Cargo.toml
- native/proto/Cargo.toml
- pom.xml
- spark-integration/pom.xml
- spark/pom.xml
N/A
Part of the release process
- Update version from 0.1.0 to 0.2.0
- Changelog generated for all PRs between 0.0.0 tag and branch-0.1
- Fix one error in the release verification script that was discovered when verifying 0.1.0-rc1
- Add CHANGELOG.md
> chore: Update version to 0.2.0 and add 0.1.0 changelog

- .github/actions/rust-test/action.yaml
- native/core/src/execution/datafusion/expressions/xxhash64.rs
- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/datafusion/shuffle_writer.rs
Closes https://github.com/apache/datafusion-comet/issues/700.
Make sure all targets in workspace been covered by clippy
CI changes and make clippy happy.
In CI `rust-test`.
> chore(native): Make sure all targets in workspace been covered by clippy

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: Unsupported window expression should fall back to Spark

- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala
> fix: ReusedExchangeExec can be child operator of CometBroadcastExchangeExec

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: Fallback to Spark for window expression with range frame

- pom.xml
Closes #.
CI fails to build because newly added logo files fail license check.
```
[INFO] --- apache-rat:0.16:check (default) @ comet-parent-spark3.4_2.12 ---
[INFO] Rat check: Summary over all files. Unapproved: 7, unknown: 7, generated: 1, approved: 169 licenses.
Warning:  Files with unapproved licenses:
docs/source/_static/images/logo_original.svg
docs/source/_static/images/logo_white.svg
docs/source/_static/images/white.svg
docs/source/_static/images/dark.svg
docs/source/_static/images/DataFusionComet-Logo-Dark.svg
docs/source/_static/images/logo_dark.svg
docs/source/_static/images/DataFusionComet-Logo-Light.svg
```
> build: Add Comet logo files into exclude list

- native/spark-expr/src/cast.rs
- native/spark-expr/src/lib.rs
N/A
Spark-compatible "Cast" is implemented as a physical expr in Comet, but other downstream projects might like to use it as a logical expr. To facilitate it, this makes the core logic invokable through `pub fn spark_cast`.
Makes some `Cast` struct's functions static, and moves those plus a bunch existing of static functions out of Cast impl. 
Moves ColumnarValue handling logic out of Cast::evaluate into `spark_cast`, and makes that public.
Exports `spark_cast` from spark-expr/lib
**Recommend reviewing with "Hide whitespace" ON.**
Existing tests
> chore: make Cast's logic reusable for other projects

- native/Cargo.lock
- native/Cargo.toml
N/A
Upgrade to latest DF so that we can catch any regressions before the next release.
Bump Arrow and DataFusion versions.
Existing tests, and I ran TPC-H locally and saw no change in performance
> chore: Bump DataFusion to rev 35c2e7e

- common/src/main/java/org/apache/comet/vector/CometPlainVector.java
Part of #679 and #670
This PR improves the isNullAt performance
The new `isNullAt ` method uses the OR operator instead of the if clause
Existing tests
> fix: optimize isNullAt

- docs/source/contributor-guide/development.md
- pom.xml
Follow-up to #404
Closes #.
The `skip.surefire.tests` property introduced in #404 causes `-DskipTests` to not work for `maven-surefire-plugin`.
To skip only java tests we just add `-Dtest=none`.
+ Remove `skip.surefire.tests` and set failIfNoSpecifiedTests to false for `maven-surefire-plugin`.
+ Update doc
1. test ` ./mvnw install -DskipTests -pl common`
before this pr (`-DskipTests` does not take effect):
```
[INFO] --- surefire:3.1.0:test (default-test) @ comet-common-spark3.4_2.12 ---
[INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.comet.parquet.TestColumnReader
24/07/31 …
```
> fix: Remove `skip.surefire.tests` mvn property

- native/core/src/common/bit.rs
- native/core/src/parquet/read/column.rs
- native/core/src/parquet/util/jni.rs
- spark/src/test/resources/tpcds-micro-benchmarks/scan_decimal.sql
- spark/src/test/scala/org/apache/spark/sql/benchmark/CometTPCDSMicroBenchmark.scala
Part of [#679](https://github.com/apache/datafusion-comet/issues/679) and [#670](https://github.com/apache/datafusion-comet/issues/670)
.
profiler output shows that with decimal128 enabled we have a bottleneck in `comet::common::bit::memcpy`. 
This PR changes the method to use `copy_nonoverlapped` for speed
Tested using existing tests. This is a draft PR partly to verify there are no regressions.
> perf: decimal decode improvements

- native/spark-expr/src/cast.rs
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
addresses timezone, 3 & 5 digit years' compatibility mentioned in #376 
Added 3 & 5 digit year, time-zone support.
Through Unit tests.
> feat: Add support for time-zone, 3 & 5 digit years: Cast from string to timestamp. 

- common/src/main/java/org/apache/comet/vector/CometDictionary.java
- common/src/main/java/org/apache/comet/vector/CometVector.java
- pom.xml
Part of #679 and #670
This PR improves the getDecimal performance
The new `createDecimal` method skips the negative scale check
Existing tests
> fix: skip negative scale checks for creating decimals

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
- spark/src/test/spark-4.0/org/apache/comet/exec/CometShuffle4_0Suite.scala
> fix: Fallback to Spark for unsupported partitioning

- native/core/src/execution/jni_api.rs
N/A
To help debug performance issues, I would like to see the executed DataFusion plan with native metrics.
Example output (goes to executor logs):
```
Comet native query plan with metrics:
ProjectionExec: expr=[col_0@0 as col_0, count@1 as col_1], metrics=[start_timestamp{partition=0}=2024-07-31 19:33:43.785691143 UTC, end_timestamp{partition=0}=2024-07-31 19:33:43.883594710 UTC, elapsed_compute{partition=0}=551ns, output_rows{partition=0}=7]
AggregateExec: mode=Final, gby=[col_0@0 as col_0], aggr=[count], metrics=[start_timestamp{partition=0}=2024-07-31 19:33:43.785670424 UTC, end_timestamp{partition=0}=NONE, elapsed_compute{partition=0}=5.799264ms, output_rows{partition=0}=7]
ScanExec: schema=[col_0: Utf8, col_1: Int64], metrics=[]
```
> feat: show executed native plan with metrics when in debug mode

- native/core/src/execution/datafusion/expressions/create_named_struct.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/750
Fixes a runtime error
Unwrap dictionaries in `CreateNamedStruct` to avoid schema mismatch error in arrow-rs
New tests
> fix: unwrap dictionaries in CreateNamedStruct

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
> fix: Fallback to Spark for unsupported input besides ordering

- common/src/main/scala/org/apache/comet/CometConf.scala
- docs/source/user-guide/configs.md
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/spark/sql/benchmark/CometStringExpressionBenchmark.scala
Closes https://github.com/apache/datafusion-comet/issues/483
Rust and Java have different behavior for upper and lower, so we need to disable by default and let user opt-in.
> feat: Add config to enable native upper and lower string conversion

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: Native window operator should be CometUnaryExec

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
> fix: Fallback to Spark when shuffling on struct with duplicate field name

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
N/A
Calls to withInfo would sometimes overwrite information from previous calls to withInfo
withInfo now preserves existing info on a node
New unit test added
> fix: withInfo was overwriting information in some cases

- common/src/main/java/org/apache/comet/vector/CometDelegateVector.java
- common/src/main/java/org/apache/comet/vector/CometDictionary.java
- common/src/main/java/org/apache/comet/vector/CometDictionaryVector.java
- common/src/main/java/org/apache/comet/vector/CometPlainVector.java
- common/src/main/java/org/apache/comet/vector/CometVector.java
- spark/src/test/resources/tpcds-micro-benchmarks/add_decimals.sql
- spark/src/test/scala/org/apache/spark/sql/benchmark/CometTPCDSMicroBenchmark.scala
Part of #679 and #670
This PR improves `getDecimal` read on decimals with a small precision
Implemented getLongDecimal that reads a long out of 16-byte Decimal data.
Existing tests
> fix: Optimize getDecimal for small precision

- native/core/src/execution/jni_api.rs
- native/core/src/execution/operators/copy.rs
- native/core/src/execution/operators/scan.rs
N/A
Add more metrics so that we can more easily see the overhead of each operator.
Example output:
```
ProjectionExec: ..., metrics=[elapsed_compute{partition=0}=3.467µs, output_rows{partition=0}=100]
SortExec: ..., metrics=[elapsed_compute{partition=0}=128.029µs, output_rows{partition=0}=100, ...
CopyExec, metrics=[..., elapsed_compute{partition=0}=88.506µs, output_rows{partition=0}=201]
ScanExec: ..., metrics=[s..., elapsed_compute{partition=0}=5.461µs, output_rows{partition=0}=201]
```
Add more metrics
> perf: add metrics to CopyExec and ScanExec

- pom.xml
- spark/src/test/scala/org/apache/spark/sql/CometTPCDSQuerySuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCDSQueryTestSuite.scala
Closes #.
I did memory profiling yesterday again locally, and didn't see the memory issue last time. Trying to re-enable q72.
In Github Action runner, it still cannot run q72 with sort merge join config. I only enabled q72 for other type join configs.
> build: Re-enable TPCDS q72 for broadcast and hash join configs

- native/core/src/execution/datafusion/planner.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #796.
Support null literals in more cases. Useful for creating test cases in #735 but probably will come in useful in more cases in the future.
Add support for null literals with struct data type.
New test case.
> feat: Add support for null literal with struct type

- common/src/main/java/org/apache/comet/vector/CometMapVector.java
- common/src/main/java/org/apache/comet/vector/CometStructVector.java
- common/src/main/java/org/apache/comet/vector/CometVector.java
- native/core/src/execution/datafusion/planner.rs
- native/proto/src/proto/expr.proto
- native/spark-expr/src/structs.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Closes #755.
Should improve performance as we avoid materializing arrays with dictionary encoding.
This PR removes the workaround from #750 and makes changes needed to CreateNamedStruct to preserve dictionary types. This is achived by just serializing the field names instead of the full return type, this way we get a type that actually matches the expected physical type. The original implementation was done as it lead to a slightly simpler implementation, but it clear from #750 that this was the wrong choice and leads to issues with the physical data_type.
Secondly this includes some changes in the Comet*Vector classes in 2a55eb537720e9f3558d24746f123b7b463662b9 these are needed to make those classes support dictionary types inside CometStructVector.
> feat: Optimze CreateNamedStruct preserve dictionaries

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #799.
Looks like this was mostly missed in the implemenation of #731 which extended support for structs.
The parameter `allowStruct` in `supportedDataType` is forwarded to recursive calls.
New test case.
> fix: Improve support for nested structs

- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/operators/scan.rs
N/A
I recently learned more about how ScanExec works so I thought I would add some documentation to help other contributors.
- More documentation
- Some pedantic code cleanup changes
- Use a single metrics timer instead of two timers when fetching batches
- Create a vector with the correct capacity to avoid overhead of reallocation
- Re-use CastOptions across all batches instead of creating per-batch
Existing tests
> Minor: ScanExec code cleanup and additional documentation

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: Check sort order of SortExec instead of child output

- common/src/main/scala/org/apache/comet/CometConf.scala
- docs/source/user-guide/configs.md
- docs/source/user-guide/expressions.md
- native/core/src/execution/datafusion/expressions/avg.rs
- native/core/src/execution/datafusion/expressions/avg_decimal.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/resources/tpcds-micro-benchmarks/agg_stddev.sql
- spark/src/test/resources/tpcds-micro-benchmarks/stddev.sql
- spark/src/test/scala/org/apache/spark/sql/benchmark/CometTPCDSMicroBenchmark.scala
Closes https://github.com/apache/datafusion-comet/issues/817
Related to https://github.com/apache/datafusion-comet/issues/824
- Bug fix
- q39 is the worst performing TPC-DS query compared to Spark (25-30 seconds compared to 9 seconds with Spark) and much of that time is because our implementation of `stddev` is slower than Spark. Disabling this aggregate provides a 2x speedup for the query (14 seconds) and helps our overall TPC-DS number.
> fix: Fix panic in `avg` aggregate and disable `stddev` by default

- dev/diffs/3.4.3.diff
- dev/diffs/3.5.1.diff
- dev/diffs/4.0.0-preview1.diff
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala
Closes #621 .
Allow more joins to be executed by comet.
The latest Datafusion contains fix for doing joins with struct keys, so this PR removes that limitation. The Spark diffs had to be upgrade to exclude one more test case for the same reason as ther other tests in that test suite.
Existing and new tests.
> fix: Supported nested types in HashJoin

- Makefile
N/A.
When using jvm 17+ spark needs extra jvm args to avoid getting errors like
```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.2.0:java (default-cli) on project comet-spark-spark3.4_2.12: An exception occurred while executing the Java class. class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x35b75242) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x35b75242 -> [Help 1]
```
These args are already present inside the main pom.xml. To avoid duplicating the args we using maven to extract them. In order avoid slowing down the Makefile the args are defined as a function and therefore only evaluated when they are needed.
Manually running the make commands using jvm …
> chore: Make it possible to run 'make benchmark-%' using jvm 17+

- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/operators/copy.rs
- native/core/src/execution/operators/mod.rs
N/A
We use `CopyExec` to wrap inputs to operators that can cache batches. This is to avoid corruption issues if the input batches come from a `ScanExec` where arrays are re-used, or from some other operators that may be wrapping `ScanExec` and that can pass through input batches unchanged (projection, limit, or filter).
`CopyExec` also unpacks dictionary arrays (not just primitives, but Utf8 as well).
When we have nested joins, I see that `CopyExec` is processing the output of the nested joins and this is redundant because joins do not re-use arrays.
This PR aims to avoid deep copies of arrays in some cases where it is not necessary.
Existing tests
> perf: Remove some redundant copying of batches

- common/src/main/scala/org/apache/comet/CometConf.scala
- native/core/src/execution/jni_api.rs
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
> feat: Add native thread configs

- native/Cargo.lock
- native/Cargo.toml
- native/core/Cargo.toml
- native/core/benches/filter.rs
- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/operators/filter.rs
- native/core/src/execution/operators/mod.rs
Closes https://github.com/apache/datafusion-comet/issues/757
We were often creating a filtered batch in `FilterExec` and then making a copy of that batch in `CopyExec`, resulting in redundant copying of data in the case where `FilterExec` had already created a new batch with the filtered data. It was necessary to have the `CopyExec` because `FilterExec` can pass through input batches in the case where the predicate evaluates to true for all rows and this is not safe in Comet because we re-use arrays in the `ScanExec`.
This PR introduces a customized version of `FilterExec` that uses Arrow's `take_record_batch` kernel to always create new batches, even in the case where the predicate evaluates to true for all rows. This removes the need to wrap `FilterExec` in a `CopyExec`.
This reduces …
> perf: Remove redundant copying of batches after FilterExec

- docs/source/user-guide/installation.md
- docs/source/user-guide/tuning.md
Closes #826
Closes #605 
Document the way to start Comet in cluster mode so the resource manager respects Comet memory configuration parameters
> doc: Document CometPlugin to start Comet in cluster mode

- native/core/src/execution/datafusion/expressions/checkoverflow.rs
This PR improves CheckOverflow performance
This PR directly calls arrow validation methods
Existing tests
> fix: Optimize CheckOverflow

- kube/Dockerfile
Reverts apache/datafusion-comet#686
See https://github.com/apache/spark-docker/pull/65, `3.4.3` is published
> chore: Revert "fix: change the not exists base image apache/spark:3.4.3 to 3.4.2"

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
N/A
`AQEShuffleRead` will never have a native version so we should stop warning that we cannot run it natively
> minor: stop warning that AQEShuffleRead cannot run natively

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Closes https://github.com/apache/datafusion-comet/issues/845
Before this PR, we see errors such as:
```
ObjectHashAggregate [COMET: ObjectHashAggregate is not supported]
```
With this PR, we see information about which aggregate expression is not supported:
```
ObjectHashAggregate [COMET: unsupported Spark aggregate function: bloom_filter_agg]
```
> chore: Improve ObjectHashAggregate fallback error message

- .github/workflows/docker-publish.yml
> chore: Use Git tag as Comet version when publishing Docker images

- docs/source/contributor-guide/benchmarking.md
- docs/source/contributor-guide/debugging.md
- docs/source/contributor-guide/plugin_overview.md
- docs/source/user-guide/installation.md
- fuzz-testing/README.md
- native/Cargo.lock
- spark/src/main/scala/org/apache/spark/Plugins.scala
- spark/src/test/scala/org/apache/spark/CometPluginsSuite.scala
> feat: Use CometPlugin as main entrypoint

- docs/source/user-guide/compatibility.md
- native/core/src/execution/datafusion/planner.rs
- native/proto/src/proto/expr.proto
- native/spark-expr/benches/cast_from_string.rs
- native/spark-expr/benches/cast_numeric.rs
- native/spark-expr/src/cast.rs
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Related to https://github.com/apache/datafusion-comet/issues/326 and https://github.com/apache/datafusion-comet/issues/325
When running aggregate queries against schemas where numbers are in string format (csv files, parquet files generated from csv files, etc), Spark will add casts from string to floating point or decimal. We fall back to Spark because we did not have these casts implemented.
This is frustrating for casual users who just want to try Comet out on some text inputs.
This PR adds a basic implementation of these casts by delegating to DataFusion. These are not compatible with Spark and are documented as such and are only enabled if `spark.comet.cast.allowIncompatible` is enabled.
I recommend viewing the diff without whitespace changes …
> feat: Implement basic version of string to float/double/decimal

- spark/src/main/scala/org/apache/spark/shuffle/sort/RowPartition.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometMetricNode.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #.
We don't propagate spilling metrics of SortMergeJoin from DataFusion to Comet yet. This patch adds spilling related metrics to Comet SortMergeJoin operator.
> chore: Add spilling metrics of SortMergeJoin

- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> feat: Add ShuffleQueryStageExec to direct child node for CometBroadcastExchangeExec

- common/src/main/java/org/apache/comet/vector/CometListVector.java
- common/src/main/java/org/apache/comet/vector/CometVector.java
- native/core/src/execution/datafusion/planner.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #841 
`make_array` doesn't support mixed types of dictionaries and non-dictionaries. Type coercion is the fundamental piece that DataFusion uses at analysis time that is missing from Comet's use of ScalarUDFs.
In the planning for ScalarUDFs on the Rust side, check the function to see if the input types should be coerced to other types, and if so wrap the Expression in a cast to the appropriate type.
`CreateArray` unit test is updated with cases that were previously failing.
> fix: Support type coercion for ScalarUDFs

- spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala
Closes #.
This bug was found while debugging CI failure in #893. In `CometTakeOrderedAndProjectExec`, we create internal native plan to execute native limit + sort + project. The pseudo scan node created there was incorrectly using `CometTakeOrderedAndProjectExec`'s output attributes but it should be child node's output.
Currently it doesn't cause any error, although it will have incorrect schema in the scan node. Because sort/limit simply takes input so the incorrect schema doesn't make error. For project, we already bind attributes in Spark, as the input data is correct so it has no error too.
But in #893, we need to get the number of columns from the schema of scan node. If the schema is incorrect, the scan node will create incorrect number of array/schema structures which cause error …
> fix: CometTakeOrderedAndProjectExec native scan node should use child operator's output

- common/src/main/scala/org/apache/comet/vector/ExportedBatch.scala
- common/src/main/scala/org/apache/comet/vector/NativeUtil.scala
- common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala
- spark/src/main/java/org/apache/comet/CometBatchIterator.java
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
Closes #884.
Please refer to the comments in https://github.com/apache/datafusion-comet/issues/884 for details.
* Fixes `ArrowSchema` and `ArrowArray` base structure leaks in JVM
* Fixes AQE coalesce partition leaks by closing the ArrowStreamWriter
It is pretty hard to add tests for this fix, so we manually tested this and relying on existing tests to make sure that it does not break anything.
> fix: Fix various memory leaks problems

- native/core/src/lib.rs
Closes #894
More information for debugging
- `native/core/src/lib.rs`: added a call to `env!` to get a version and add this version to info message
I run it and it works:
I googled a little how one can test logging and it looks like the only solution is to redirect logs to the file, to read the file and to check the content. To be honest, I do not fully understand how that approach could be introduced into the current test system... Should I try? Because it is the only one place at the moment where one needs to test logs output and I'm not sure that it worth it.
> chore: print Comet native version to logs after Comet is initialized

- spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q47/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q47/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q57/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q57/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q47/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q47/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q57/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q57/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7-spark3_5/q47/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7-spark3_5/q47/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7-spark3_5/q57/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7-spark3_5/q57/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7/q47/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7/q47/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7/q57/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7/q57/simplified.txt
Closes #.
During debugging the last test failure in #893, it is caused by incorrectly exchange reuse of two Comet hash aggregate operators. Currently Comet hash aggregate operator's equal and hashCode don't include output. So if two hash operators have same input, mode, etc, they will be wrongly considered equal and cause the issue.
This patch add output to all Comet operators' equal and hashCode methods.
> fix: Add output to Comet operators equal and hashCode

- docs/source/user-guide/tuning.md
- spark/src/main/scala/org/apache/spark/sql/comet/CometBatchScanExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
Closes https://github.com/apache/datafusion-comet/issues/914
The total scan time reported by Comet is often less than the reported time to decode Parquet data, which does not make sense.
The issue is that we convert nano time to milliseconds for each batch and this loses a lot of precision. In one example, the actual total scan time was 41 seconds but it was reported as 23 seconds, which is very misleading. Spark also suffers from this problem.
Change scan time to be recorded in nanos.
Manual testing. See earlier screenshots.
> perf: Report accurate total time for scans

- common/src/main/scala/org/apache/comet/vector/NativeUtil.scala
- native/core/src/execution/jni_api.rs
- native/core/src/execution/utils.rs
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/comet/Native.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometExecUtils.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
Closes #885.
This is another part of #885. In #893, we already revised the way we export arrays to native side. We now allocate array/schema structures in native side when exporting arrays from JVM to native.
Similarly, this PR revises the way we import array from native side by allocating array/schema structures in JVM when importing arrays from native to JVM.
> chore: Revise array import to more follow C Data Interface semantics

- common/src/main/scala/org/apache/comet/vector/NativeUtil.scala
- native/core/src/execution/jni_api.rs
- native/core/src/execution/utils.rs
Closes #.
Addressing the latest reviews https://github.com/apache/datafusion-comet/pull/905#discussion_r1746350944 and https://github.com/apache/datafusion-comet/pull/905#discussion_r1746346897.
> chore: Address reviews

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
> fix: Fallback to Spark when cannot resolve AttributeReference

- .github/workflows/spark_sql_test.yml
- .github/workflows/spark_sql_test_ansi.yml
- dev/diffs/3.4.3.diff
- dev/diffs/3.5.1.diff
- dev/diffs/4.0.0-preview1.diff
Closes #930.
We disabled Comet shuffle for Spark core-1 test because negative ref count issue reported by Java Arrow. After fixing memory issues and some changes to more follow C Data interface, we may re-enable Comet shuffle for Spark core-1 test in CI.
> chore: Enable Comet shuffle for Spark core-1 test

- common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/ArrowReaderIterator.scala
- common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometBlockStoreShuffleReader.scala
Closes #927.
Please refer to the comments of #927 for details.
* Holds at most one unclosed `ArrowReaderIterator` in `CometBlockStoreShuffleReader`.
* (optional) automatically close the `ArrowReaderIterator` when reading the end of the stream.
It is pretty hard to add tests for this fix, so we manually tested this and relying on existing tests to make sure that it does not break anything.
> fix: Fix memory bloat caused by holding too many unclosed `ArrowReaderIterator`s

- native/core/src/execution/operators/scan.rs
- spark/src/main/scala/org/apache/spark/sql/comet/CometMetricNode.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
N/A
Make it easy to see how much of the native `ScanExec` time is spent casting columns to different types (this usually means unpacking dictionaries). 
Example from TPC-DS q9:
DataFusion metrics in native explain output:
```
metrics=[
output_rows=2097152, 
elapsed_compute=21.847892ms, 
cast_time=21.631731ms]
```
Full plan:
```
AggregateExec: mode=Partial, gby=[], aggr=[count, avg, avg], metrics=[output_rows=1, elapsed_compute=9.481194ms]
ProjectionExec: expr=[col_1@1 as col_0, col_2@2 as col_1], metrics=[output_rows=400519, elapsed_compute=50.596µs]
FilterExec: col_0@0 IS NOT NULL AND col_0@0 >= 81 AND col_0@0 <= 100, metrics=[output_rows=400519, elapsed_compute=4.753725ms]
ScanExec: source=[CometScan parquet  (unknown)], schema=[col_0: Int32, col_1: Decimal128(7, 2), col_2: …
```
> perf: Add metric for time spent casting in native scan

- .github/workflows/pr_build.yml
Closes #839.
Fix CI failure like https://github.com/apache/datafusion-comet/actions/runs/10795858606/job/29943521019
> build: Disable upload-test-reports for macos-13 runner

- common/src/main/scala/org/apache/comet/CometConf.scala
- docs/source/user-guide/configs.md
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
- spark/src/test/scala/org/apache/spark/sql/comet/CometPlanStabilitySuite.scala
Part of https://github.com/apache/datafusion-comet/issues/901
There are known correctness and performance issues with our support for SMJ with join condtion, so we should disable it by default.
New config.
> chore: Add config for enabling SMJ with join condition

- common/pom.xml
- dev/diffs/3.4.3.diff
- dev/diffs/3.5.1.diff
- dev/diffs/4.0.0-preview1.diff
- fuzz-testing/pom.xml
- pom.xml
- spark-integration/pom.xml
- spark/pom.xml
Part of https://github.com/apache/datafusion-comet/issues/721
I am requesting that ASF INFRA sets up Nexus access for the DataFusion project so that we can publish Maven artifacts. The normal convention for maven group ids for Apache projects is `org.apache.TLPNAME`, so I think we need to revisit changing our Maven group ids (<groupId> in the pom.xml) from `org.apache.comet` to `org.apache.datafusion`. The DataFusion project could hypothetically want to publish Java bindings to Maven in the future as well. The artifact names would not change and there is no need to change package names in the code.
Note that we did previously discuss this back in https://github.com/apache/datafusion-comet/pull/278.
> chore: Change maven group ID to `org.apache.datafusion`

- spark/src/main/scala/org/apache/spark/sql/comet/CometSparkToColumnarExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
N/A.
We want deeper insights to query performance when Spark to Arrow conversions occur.
Added a new metric to `CometSparkToColumnarExec` and wrapped the calls to the batch iterator's `next` function with timing functions.
Extended an existing test that exercises SparkToColumnar to check for metrics.
> perf: Add metric for time spent in CometSparkToColumnarExec

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
N/A
The fallback message in the plan was not very helpful.
Before:
```
SortMergeJoin [COMET: ]
```
After:
```
SortMergeJoin [COMET: spark.comet.exec.sortMergeJoinWithJoinFilter.enabled is not enabled]
```
> chore: Show reason for falling back to Spark when SMJ with join condition is not enabled

- dev/release/README.md
- dev/release/publish-to-maven.sh
> feat: Publish artifacts to maven

- docs/source/user-guide/compatibility.md
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q21/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q34/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q39a/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q39b/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q73/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark4_0/q21/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark4_0/q34/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark4_0/q39a/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark4_0/q39b/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark4_0/q73/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q21/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q34/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q39a/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q39b/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q73/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7-spark3_5/q34/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7-spark4_0/q34/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v2_7/q34/explain.txt
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
> fix: Normalize NaN and zeros for floating number comparison

- native/core/src/execution/datafusion/planner.rs
- native/proto/src/proto/operator.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> fix: window function range offset should be long instead of int

- docs/source/user-guide/installation.md
Closes #.
Describe installation steps from Published Source Release
> chore: clarify tarball installation

- README.md
- docs/source/user-guide/installation.md
- docs/source/user-guide/overview.md
Closes #.
Adding more documentation interlinks and Comet docs link from the main page
> doc: add documentation interlinks

- common/src/main/scala/org/apache/comet/vector/NativeUtil.scala
> fix: Use the number of rows from underlying arrays instead of logical row count from RecordBatch

- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/mod.rs
- native/core/src/execution/operators/copy.rs
N/A
We were injecting too many CopyExecs for SMJ. Plans looked like this:
```
SortMergeJoin
CopyExec [UnpackOrDeepClone]
SortExec
CopyExec [UnpackOrDeepClone]
...
CopyExec [UnpackOrDeepClone]
SortExec
CopyExec [UnpackOrDeepClone]
...
```
With the changes in this PR, the plan now looks like:
```
SortMergeJoin
SortExec
CopyExec [UnpackOrDeepClone]
...
SortExec
CopyExec [UnpackOrDeepClone]
...
```
Existing tests
> perf: Remove one redundant CopyExec for SMJ

- native/core/src/execution/datafusion/planner.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Follow up to https://github.com/apache/datafusion-comet/issues/792
Enable additional `CreateArray` tests now that we've bumped the DataFusion version in https://github.com/apache/datafusion-comet/pull/909
Enable additional tests, and make on change to the equality check for type coercion to fix one of the new tests.
New tests enabled
> chore: Enable additional CreateArray tests

- docs/templates/compatibility-template.md
This is a followup PR of #953 
Updated the template, otherwise `make release` will wipe it out
> chore: fix compatibility guide

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
> chore: Don't transform the HashAggregate to CometHashAggregate if Comet shuffle is disabled

- common/src/main/java/org/apache/comet/NativeBase.java
- native/core/src/jvm_bridge/mod.rs
- spark/src/test/scala/org/apache/comet/CometNativeSuite.scala
This is a minor, non-user-aware fix so I've not created a GtHub issue. A detailed explanation is provided in the next section.
I had this small patch in my local workspace for a while, I think it is useful for other comet developers as well. The changes are as follows:
1. Fix the library name when not loading from the JAR bundle. The [documentation of `System.loadLibrary`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/System.html#loadLibrary(java.lang.String)) states that "The libname argument must not contain any platform specific prefix, file extension or path", so the library name should be `comet` instead of `libcomet.so` or `libcomet.dylib`. This fix makes it easier to load the newly built comet library in the `native/target` directory when running Java …
> fix: Properly handle Java exceptions without error messages; fix loading of comet native library from java.library.path

- docs/source/contributor-guide/benchmarking.md
- docs/source/user-guide/tuning.md
Part of https://github.com/apache/datafusion-comet/issues/949
Provide better documentation for tuning memory usage.
[Rendered version of this PR](https://github.com/andygrove/datafusion-comet/blob/update-tuning-guide/docs/source/user-guide/tuning.md)
> docs: Update tuning guide

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
Closes #.
Currently Comet scan cannot work with Iceberg reader internally if there is meta columns. We should fallback to Spark for the case before we can support meta column.
Manually test with Iceberg tests.
> fix: Fallback to Spark if scan has meta columns

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
> fix: Fallback to Spark if named_struct contains duplicate field names

- native/core/src/execution/datafusion/shuffle_writer.rs
This reverts commit e146cfa1676fedcfb3003c2e3f1da1578d6b664b.
Closes #.
There is an issue https://github.com/apache/datafusion-comet/issues/1019 caused by the patch. Reverting the patch temporarily to unblock other works.
> chore: Revert "chore: Reserve memory for native shuffle writer per partition (#988)"

- native/core/src/execution/datafusion/shuffle_writer.rs
Closes #1019.
This restore the patch merged in #988. The patch causes the issue #1019. This patch includes a fix for that.
Manually run TPCH benchmark locally.
> chore: Reserve memory for native shuffle writer per partition

- common/src/main/scala/org/apache/comet/package.scala
Closes https://github.com/apache/datafusion-comet/issues/1026
Closes https://github.com/apache/datafusion-comet/issues/1012
Our instructions for building from source produce a jar file that does not contain `comet-git-info.properties` and this results in an exception at runtime. 
We had the same issue with our Docker build because that also builds without git info.
Use default values in `CometBuildInfo` instead of throwing an exception if `comet-git-info.properties` does not exist.
I tested manually using our Docker/k8s instructions. This was previously failing for me.
> fix: Make comet-git-info.properties optional

- common/src/main/java/org/apache/comet/NativeBase.java
Closes https://github.com/apache/datafusion-comet/issues/999
If the static initialization block failed to load the library then we did not see the reason why (in some cases).
Before:
```
│ 24/10/07 22:42:11 WARN CometSparkSessionExtensions: Comet extension is disabled because of error when loading native lib. Falling back to Spark                                                                                                   │
│ java.lang.NoClassDefFoundError: Could not initialize class org.apache.comet.NativeBase  
```
After:
```
│ 24/10/22 15:00:08 WARN CometSparkSessionExtensions: Comet extension is disabled because of error when loading native lib. Falling back to Spark                                                                                                          │
│ …
```
> chore: Improve error handling when native lib fails to load

- native/core/src/execution/jni_api.rs
- native/core/src/execution/metrics/utils.rs
Partially addresses #1024.
Comet uses JNI jstrings as the keys to updating metrics values on the Spark side during execution. As described in #1024, currently Comet allocates a jstring for every metric for every invocation of metrics updating. The calls to `jni_NewStringUTF` account for over 1% of the on-CPU time in TPC-H SF10 for me.
Added a HashMap that maps the native string to a jstring to use in JNI calls. This has the benefit of being many-to-one, whereby multiple nodes with the same metric name will benefit from the cached jstring. This cache is populated on demand: if the entry isn't present, we allocate a jstring and insert it into the cache.
I have some thoughts about this approach that I would love for reviewers to comment on:
1. I wanted to populate the cache in advance, maybe …
> perf: Cache jstrings during metrics collection

- spark/src/main/scala/org/apache/spark/Plugins.scala
Closes #1045 .
Provide a default value `1g` to `getSizeAsMb(EXECUTOR_MEMORY.key)`, which is [the default value](https://spark.apache.org/docs/3.5.3/configuration.html#application-properties) of `spark.executor.memory` in Apache Spark 3.5.3.
+ Define `private val EXECUTOR_MEMORY_DEFAULT` in the class
+ Call `getSizeAsMb(EXECUTOR_MEMORY.key)` with `EXECUTOR_MEMORY_DEFAULT` 
Tested with the `datafusion-benchmarks` as described in the issue #1045  .
> fix: need default value for getSizeAsMb(EXECUTOR_MEMORY.key)

- native/core/src/execution/datafusion/expressions/bloom_filter_agg.rs
- native/core/src/execution/datafusion/util/spark_bloom_filter.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #1023.
The other integer types just need a cast. For strings I had to add `put_binary` to `spark_bloom_filter`.
Added more types to test for Spark 3.5+.
> feat: Support more types with BloomFilterAgg

- common/src/main/java/org/apache/comet/parquet/ColumnReader.java
- common/src/main/java/org/apache/comet/parquet/MetadataColumnReader.java
- common/src/main/java/org/apache/comet/parquet/Native.java
- native/core/src/parquet/mod.rs
> chore: Refactor Arrow Array and Schema allocation in ColumnReader and MetadataColumnReader

- native/core/src/execution/datafusion/planner.rs
- native/proto/src/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
N/A
We currently have 20 duplicate structs defined in protobuf for binary expressions, such as:
```protobuf
message Equal {
Expr left = 1;
Expr right = 2;
}
message NotEqual {
Expr left = 1;
Expr right = 2;
}
message EqualNullSafe {
Expr left = 1;
Expr right = 2;
}
```
As a result, we have a lot of duplicate code in QueryPlanSerde for serializing binary expressions that cannot easily be refactored because each code block references a different (but identical) generated class.
- Use a single definition of BinaryExpr
- Refactor  QueryPlanSerde to remove a lot of duplicate boilerplate code
Existing tests
> minor: Refactor binary expr serde to reduce code duplication

- docs/source/user-guide/kubernetes.md
Closes #.
Fix the Spark configuration typo and some links
> doc: fix K8s links and doc

- native/Cargo.lock
- native/Cargo.toml
- native/core/benches/aggregate.rs
- native/core/benches/bloom_filter_agg.rs
- native/core/src/execution/datafusion/expressions/sum_decimal.rs
- native/core/src/execution/datafusion/planner.rs
- native/spark-expr/src/scalar_funcs/hash_expressions.rs
- spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala
N/A
Voting has started on DataFusion 43.0.0-rc1, so we should make sure that it does not cause any regressions in Comet.
> chore: Upgrade to DataFusion 43.0.0-rc1

- native/proto/src/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
N/A
This PR follows on from https://github.com/apache/datafusion-comet/pull/1053 which refactored `BinaryExpr` to reduce code duplication. This PR does the same for `MathExpr` and `UnaryExpr`.
Just refactoring to reduce code duplication. There are no functional changes.
> chore: Refactor UnaryExpr and MathExpr in protobuf

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
N/A
Following up from [this comment](https://github.com/apache/datafusion-comet/pull/1053#discussion_r1828621016) in a recent PR, I wanted to explore the suggestion some more.
Refactor `UnaryExpr` handling in `QueryPlanSerde` to make it more concise, but at the cost of increased complexity.
I am looking for feedback if this is a good direction or not (I do not have a strong opinion either way). If we do like this approach then I can follow up to apply this to `BinaryExpr` and `MathExpr` as well.
Existing tests
> minor: refactor UnaryExpr handling to make code more concise

- native/spark-expr/src/cast.rs
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/815
We need support for casting between struct types to support reading structs from Parquet using DataFusion's ParquetExec.
> feat: Implement CAST between struct types

- common/src/main/scala/org/apache/comet/CometConf.scala
- native/core/src/execution/datafusion/planner.rs
- native/proto/src/proto/operator.proto
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Reopening - this time with actual calls to DF ParquetExec.
The number of failures is greater now but all seem reasonable to expect at this stage
> wip - CometNativeScan

- native/core/src/execution/datafusion/planner.rs
- native/proto/src/proto/operator.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
> [comet-parquet-exec] Pass Spark's partitions to DF's ParquetExec

- native/core/src/execution/datafusion/planner.rs
- native/proto/src/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Related to #1042: Adds support for array_append operation
> feat: support array_append

- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #.
Just found this test doesn't actually test what it did. We need to add specified COMET_SHUFFLE_MODE config to restore it.
> test: Restore one test in CometExecSuite by adding COMET_SHUFFLE_MODE config

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
I think when prefetching is enabled (which is probably a setting not relevant to ParquetExec anyway we end up with a DataSourceRDD in the scan instead of a FileScanRDD. This extracts the partitions from that RDD type.
```
Total number of tests run: 754
Suites: completed 32, aborted 0
Tests: succeeded 609, failed 145, canceled 1, ignored 46, pending 0
```
> [comet-parquet-exec] Handle CometNativeScan RDD when DataSourceRDD instead of FileScanRDD

- fuzz-testing/pom.xml
- spark-integration/pom.xml
We do not need to publish these jars when we release Comet
> build: Skip installation of spark-integration  and fuzz testing modules

- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/jni_api.rs
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometExecRDD.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
> feat: Hook DataFusion Parquet native scan with Comet execution

- native/core/src/execution/operators/scan.rs
N/A
ScanExec fetches the first batch during construction and this batch was not included in metrics.
> chore: Include first ScanExec batch in metrics

- docs/source/user-guide/tuning.md
- native/core/src/execution/datafusion/shuffle_writer.rs
- native/core/src/execution/operators/scan.rs
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
N/A
Provide more visibility into shuffle costs. We already report shuffle write time but we could not see how long it took to read the input data. This PR adds a new `jvm_fetch_time` metric.
Add a new custom metric to show the time that it takes for native shuffle to read its input data (fetching batches from the JVM that already exist).
Manually.
> chore: Add custom metric for native shuffle fetching batches from JVM

- native/core/src/execution/datafusion/planner.rs
- native/proto/src/proto/operator.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
> fix: Support partition values in feature branch comet-parquet-exec

- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometExecUtils.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/ZippedPartitionsRDD.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/CometNativeSuite.scala
> fix: Use RDD partition index

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Closes #.
Fix compilation error on Spark 3.3:
```
Error:  /__w/datafusion-comet/datafusion-comet/spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:3225:
value pathUri is not a member of org.apache.spark.sql.execution.datasources.PartitionedFile
```
> fix: [comet-parquet-exec] Use filePath instead of pathUri

- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometExecRDD.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometExecUtils.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/ZippedPartitionsRDD.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/CometNativeSuite.scala
Closes #.
This cherry-picks the fix #1112 to `comet-parquet-exec` feature branch to fix failed test `limit (cartesian product)` in `CometExecSuite`.
> fix: [comet-parquet-exec] Use RDD partition index

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #1121 
Currently Comet checks for replacing a Scan node with CometScanExec if the HadoopFsRelation's FileFormat is of type `ParquetFileFormat`. However, Comet then simply [replaces that file format with it's own custom CometParquetFileFormat](https://github.com/apache/datafusion-comet/blob/5400fd7c372d2f97ba607457f7d1098e36e2a6e8/spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala#L486), discarding the original FileFormat which may have been a subclass of ParquetFileFormat with custom behaviors, which is how Delta currently creates scans. Throwing out the DeltaParquetFileFormat can end up with incorrect results for reading Delta tables. Instead, CometScanExec should only be supported if the file format is exactly ParquetFileFormat and not a subclass.
The alternative …
> fix: Don't create CometScanExec for subclasses of ParquetFileFormat

- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/datafusion/spark_plan.rs
Follow up to https://github.com/apache/datafusion-comet/pull/1111
We should not include `ScanExec` elapsed time in parent nodes because this is measuring the time to call `CometBatchIterator.next`, which is calling `next` on its input. In other words, `ScanExec` elapsed time is the time taken by the child query that generates the input batches for `ScanExec` so we should not count this time twice.
Also fixed an issue with swapped hash joins.
> fix: Fix metrics regressions

- native/core/src/execution/jni_api.rs
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/comet/Native.scala
Part of https://github.com/apache/datafusion-comet/issues/1098
We were constructing a Java map containing 5 configs and passing that into native and then extracting those configs. This is expensive compared to just passing the 5 configs as parameters.
This config mechanism also supported passing arbitrary DataFusion configs into the native context but I am not aware of anyone using this feature, and perhaps there is a cleaner way to do this if we want to add it back.
Just some refactoring to make createPlan a little more efficient.
> perf: Stop passing Java config map into native createPlan

- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/datafusion/schema_adapter.rs
- native/proto/src/proto/operator.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
The current logic takes the data schema and the required schema from the Java side (in the scan node) and:
1. Converts back to a Parquet schema (Thrift encoded)
2. Serializes it to the native side
3. Parses it to a schema descriptor
4. Converts that to an Arrow schema
This process is introducing conversion errors that are difficult to recover from (e.g. Timestamp(milli) -> INT96 -> Timestamp(nano)). This PR simplifies the schema serialization and conversion to native side, building on what @viirya did with the partition schema (thank you for the inspiration!).
In this PR, data schema and required schema are now serialized as Spark types. On the native side they are converted to Arrow types. We also now serialize more schema info (column names, nullability) than we did for just partition …
> [comet-parquet-exec] Simplify schema logic for CometNativeScan

- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/datafusion/schema_adapter.rs
- native/core/src/parquet/mod.rs
> [comet-parquet-exec] build: clippy fixes

- docs/source/user-guide/tuning.md
- native/core/src/execution/datafusion/shuffle_writer.rs
- native/core/src/execution/operators/scan.rs
- native/core/src/jvm_bridge/batch_iterator.rs
- spark/src/main/java/org/apache/comet/CometBatchIterator.java
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometExecUtils.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
N/A
This PR contains some more metrics cleanup:
- Move `jvm_fetch_time` from `CometShuffleExchangeExec` to `ScanExec` because `ScanExec` is the operator that actually fetches batches from the JVM and it is not only used in shuffle
- Record native FFI time and JVM fetch time separately in `ScanExec`. These are just native metrics and not exposed as Spark SQL metrics.
- Always populate `ScanExec` source description so that we can see metrics for different types of `ScanExec`
```
ScanExec: source=[CometScan parquet], metrics=[elapsed_compute=202.9232ms, arrow_ffi_time=23.500549ms, jvm_fetch_time=179.13512ms]
```
```
ScanExec: source=[ShuffleQueryStage], metrics=[elapsed_compute=325.973811ms, arrow_ffi_time=23.690355ms, jvm_fetch_time=301.50587ms]
```
Here is a pie chart showing JVM fetch …
> feat: Improve ScanExec native metrics

- docs/source/contributor-guide/plugin_overview.md
Closes https://github.com/apache/datafusion-comet/issues/977
I didn't fully understand how shuffle writes worked and why it involved two separate native plans. Now that I do, I am documenting it for the next person who is curious about this.
More docs.
> docs: Add some documentation explaining how shuffle works

- native/core/src/execution/datafusion/planner.rs
- native/spark-expr/benches/cast_from_string.rs
- native/spark-expr/benches/cast_numeric.rs
- native/spark-expr/src/cast.rs
- native/spark-expr/src/lib.rs
- native/spark-expr/src/to_json.rs
N/A
This is in preparation for adding additional cast options to support the `comet-parquet-exec` proof-of-concept work.
> chore: Refactor cast to use SparkCastOptions param

- spark/src/test/scala/org/apache/spark/sql/benchmark/CometExecBenchmark.scala
Closes #.
#987 accidentally commented out some scenarios in CometExecBenchmark.
Uncomment the scenarios in CometExecBenchmark.
> fix: Enable scenarios accidentally commented out in CometExecBenchmark

- native/core/benches/bloom_filter_agg.rs
- native/core/benches/parquet_read.rs
- native/core/src/errors.rs
- native/core/src/execution/datafusion/expressions/bloom_filter_agg.rs
- native/core/src/execution/datafusion/planner.rs
- native/core/src/execution/datafusion/util/spark_bit_array.rs
- native/core/src/execution/jni_api.rs
- native/core/src/execution/kernels/strings.rs
- native/core/src/execution/operators/scan.rs
- native/core/src/execution/shuffle/list.rs
- native/core/src/execution/shuffle/map.rs
- native/core/src/execution/shuffle/row.rs
- native/core/src/execution/utils.rs
- native/core/src/jvm_bridge/batch_iterator.rs
- native/core/src/jvm_bridge/comet_metric_node.rs
- native/core/src/jvm_bridge/comet_task_memory_manager.rs
- native/core/src/jvm_bridge/mod.rs
- native/core/src/lib.rs
- native/core/src/parquet/mod.rs
- native/core/src/parquet/mutable_vector.rs
- native/core/src/parquet/read/column.rs
- native/core/src/parquet/read/mod.rs
- native/core/src/parquet/read/values.rs
- native/core/src/parquet/util/test_common/page_util.rs
N/A
We were specifying `#[allow(dead_code)]` for the entire core crate rather than just where it was needed.
> chore: Remove dead code

- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
This enables a few more tests to pass since it's actually checking results of the new scan type.
> fix: [comet-parquet-exec] Add CometNativeScanExec support to checkParquetScan

- dev/diffs/4.0.0-preview1.diff
- docs/source/user-guide/source.md
- spark/src/main/scala/org/apache/comet/parquet/ParquetFilters.scala
Part of https://github.com/apache/datafusion-comet/issues/372 and https://github.com/apache/datafusion-comet/issues/551
To be ready for Spark 4.0
This PR fixes the new test SPARK-47120 added in Spark 4.0
tests enabled
> fix: Spark 4.0-preview1 SPARK-47120

- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
outputPartitioning for CometScanExec was incorrectly returning 0 causing unit tests to fail
> fix: use inputRDD to get outputPartitions in CometScanExec

- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Part of https://github.com/apache/datafusion-comet/issues/1040
This PR adds the test (ignored for now) that we have been using in the proof of concept work to support reading complex types from Parquet using DataFusion's ParquetExec.
I also added one trivial test each for Map and Array. We will need to add more but this gets us started.
New tests (ignored).
> chore: Add ignored tests for reading complex types from Parquet

- common/src/main/java/org/apache/comet/parquet/BatchReader.java
- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- native/spark-expr/src/cast.rs
- spark/src/main/scala/org/apache/comet/DataTypeSupport.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Changes in CometScanExec to support the full native reader caused the original reader. This fixes the issues so that all Comet unit tests pass with the original native scan. The only tests that do not pass are the plan stability tests where the 'expected' plans expect `CometNativeScan` but if full native is not turned on, the plan produces a CometScan (which is expected).
> fix: [comet-parquet-exec] fix regressions original comet native scal implementation

- docs/source/user-guide/tuning.md
Closes #1166 
Documenting an existing feature
Adds documentation to the tuning guide to enable extended explain plan in Spark
> fix: Document enabling comet explain plan usage in Spark (4.0)

- common/src/main/scala/org/apache/comet/CometConf.scala
- common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/IpcInputStreamIterator.scala
- common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/ShuffleUtils.scala
- docs/source/user-guide/configs.md
- docs/source/user-guide/tuning.md
- native/core/benches/shuffle_writer.rs
- native/core/src/execution/planner.rs
- native/core/src/execution/shuffle/mod.rs
- native/core/src/execution/shuffle/row.rs
- native/core/src/execution/shuffle/shuffle_writer.rs
- native/proto/src/proto/operator.proto
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala
Part of https://github.com/apache/datafusion-comet/issues/1123
- Respect `spark.shuffle.compress` so that shuffle compression can be disabled (this is mainly to help with performance profiling)
- Make compression level configurable
- Make compression codec configurable in preparation for adding support for lz4
Note that this is just the code of encoding and compressing in memory. There is no disk I/O.
Add compression configuration to protobuf
> feat: Make native shuffle compression configurable and respect `spark.shuffle.compress`

- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
N/A
This is a small refactor extracted from https://github.com/apache/datafusion-comet/pull/1192.
- Remove function `executeColumnarCollectIterator` and associated test because it isn't used anywhere else.
- Move `decodeBatches` from `CometExec` to a private function in `CometBroadcastExchangeExec.scala` since that is the only place that it is needed.
- Add some comments
Existing tests
> minor: refactor to move decodeBatches to broadcast exchange code as private function

- native/core/src/execution/jni_api.rs
N/A
This refactor is extracted from https://github.com/apache/datafusion-comet/pull/1192.
`prepare_output` currently requires an `ExecutionContext` because it calls `update_metrics` but there is no reason to call `update_metrics` from within this function.
Small refactors:
- Move `update_metrics` call out of `prepare_output`
- Move `update_metrics` call out of every `match` arm in `executionPlan` and call once before the `match`
> minor: refactor prepare_output so that it does not require an ExecutionContext

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
NA
fix copy paste issue
Manually
> fix: fix missing explanation for then branch in case when

- docs/source/user-guide/kubernetes.md
- native/core/src/execution/planner.rs
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala
Checking that filtered SMJ antijoin works correctly in Comet after fixes in the DataFusion
Closes #398 #861 #891.
> feat: Reenable tests for filtered SMJ anti join

- common/src/main/scala/org/apache/comet/vector/NativeUtil.scala
N/A
Fix this warning:
```
[INFO] compiling 6 Scala sources and 12 Java sources to /home/andy/git/apache/datafusion-comet/common/target/classes ...
[WARNING] /home/andy/git/apache/datafusion-comet/common/src/main/scala/org/apache/comet/vector/NativeUtil.scala:163: patterns after a variable pattern cannot match (SLS 8.1.1)
[WARNING] /home/andy/git/apache/datafusion-comet/common/src/main/scala/org/apache/comet/vector/NativeUtil.scala:167: unreachable code due to variable pattern 'numRows' on line 163
```
> chore: Remove unreachable code

- dev/diffs/3.4.3.diff
- dev/diffs/3.5.1.diff
- dev/diffs/4.0.0-preview1.diff
Part of https://github.com/apache/datafusion-comet/issues/1197
Since `loadCometExtension` in the diffs were not using `isCometEnabled`, `SparkSessionExtensionSuite` was not using Comet. Once enabled, some test failures discovered
`loadCometExtension` now uses `isCometEnabled` that enables Comet by default
Temporary ignore the failing tests in SparkSessionExtensionSuite
existing tests
>  test: Enable Comet by default except some tests in SparkSessionExtensionSuite

- native/spark-expr/src/lib.rs
- native/spark-expr/src/struct_funcs/create_named_struct.rs
- native/spark-expr/src/struct_funcs/get_struct_field.rs
- native/spark-expr/src/struct_funcs/mod.rs
Extracted from:
- #1206
Making it easier to find functions and add stuff at the right location
the sub folder name are named after Spark `ExpressionDescription` `group` property
just reorder files and extract functions there are no logic changes
Existing tests
> chore: extract `struct` expressions to folders based on spark grouping

- native/spark-expr/src/comet_scalar_funcs.rs
- native/spark-expr/src/lib.rs
- native/spark-expr/src/scalar_funcs.rs
- native/spark-expr/src/static_invoke/char_varchar_utils/mod.rs
- native/spark-expr/src/static_invoke/char_varchar_utils/read_side_padding.rs
- native/spark-expr/src/static_invoke/mod.rs
Extracted from:
- #1206
Making it easier to find functions and add stuff at the right location
the sub folder name are named after Spark `ExpressionDescription` `group` property
just reorder files and extract functions there are no logic changes
Existing tests
> chore: extract static invoke expressions to folders based on spark grouping

- native/Cargo.lock
- native/Cargo.toml
DataFusion 44.0.0 was release to crates.io, therefore I'm using it instead of the release candidate
> chore: Upgrade to DataFusion 44.0.0 from 44.0.0 RC2

- common/src/main/scala/org/apache/comet/CometConf.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
- spark/src/test/scala/org/apache/spark/sql/comet/CometPlanStabilitySuite.scala
Makes it easier to switch scan implementation types during development by setting the environment variable  `NATIVE_SCAN_IMPL= {native | native_full | native_recordbatch }`
Default remains `native_full`
> [comet-parquet-exec] fix: Set scan implementation choice via environment variable

- dev/diffs/3.4.3.diff
- dev/diffs/3.5.1.diff
- dev/diffs/4.0.0-preview1.diff
Because `isCometShuffleEnabled` is false by default, some tests were not reached
Removed `isCometShuffleEnabled` and updated spark test diff
existing test
> test: Enable shuffle by default in Spark tests

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/1249
Fix bug that causes Spark SQL tests to fail when we run with jvm shuffle mode.
> fix: Fall back to Spark for unsupported partition or sort expressions in window aggregates

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q16/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q16/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q28/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q28/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q94/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q94/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q95/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q95/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q16/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q16/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q28/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q28/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q94/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q94/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q95/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q95/simplified.txt
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/1260
As a short term fix until we can implement distinct aggregates correctly and fully, lets fall back to Spark for correct behavior.
> fix: Fall back to Spark for distinct aggregates

- spark/src/test/scala/org/apache/spark/sql/comet/CometPlanStabilitySuite.scala
Plans change every time we need to bring in a change from main and cause unnecessary test failures
> test: [comet-parquet-exec] temporarily disable plan stability tests

- common/src/main/scala/org/apache/comet/CometConf.scala
- docs/source/user-guide/configs.md
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Part of https://github.com/apache/datafusion-comet/issues/1052
Temporary workaround for InitCap
Disabled initCap
existing tests
> fix: disable initCap by default

- common/src/main/java/org/apache/comet/parquet/AbstractColumnReader.java
- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- common/src/main/java/org/apache/comet/parquet/NativeColumnReader.java
- common/src/main/java/org/apache/comet/vector/CometVector.java
NativeColumnReader was reading all types into a CometPlainVector which is  correct only for primitive types. The PR updates the code to use NativeUtil and follow the same logic as CometExecIterator.
This addresses 12 unit test failures involving ColumnarShuffle on struct types.
> fix: handle loading of complex types into CometVector correctly in iceberg_compat scans

- common/src/main/java/org/apache/comet/vector/HasRowIdMapping.java
Closes #.
Iceberg's CometVector has delete support which has an internal row id mapping to skip some rows in a batch. We need an API in Comet to get the row id mapping from third-party CometVector implementation like that.
> feat: Add HasRowIdMapping interface

- native/core/src/execution/planner.rs
N/A
We need to use Comet's FilterExec instead of DataFusion's FilterExec to ensure that we never re-use the underlying buffers.
> chore: [comet-parquet-exec] Fix filter import

- .github/workflows/spark_sql_test.yml
- .github/workflows/spark_sql_test_ansi.yml
- common/pom.xml
- common/src/main/java/org/apache/comet/vector/HasRowIdMapping.java
- docs/source/contributor-guide/benchmark-results/tpc-ds.md
- docs/source/contributor-guide/benchmark-results/tpc-h.md
- docs/source/contributor-guide/benchmarking.md
- docs/source/contributor-guide/debugging.md
- docs/source/user-guide/installation.md
- fuzz-testing/pom.xml
- native/Cargo.lock
- native/Cargo.toml
- pom.xml
- spark-integration/pom.xml
- spark/pom.xml
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
> chore: [comet-parquet-exec] merge from main 20240116

- native/spark-expr/src/hash_funcs/utils.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
This is a partial fix for #1294, which fixes the consistency issue of hash functions for small decimal (precision <= 18).
When precision is less than or equal to 18, spark use unscaled long value of decimal to calculate hash.
https://github.com/apache/spark/blob/d12bb23e49928ae36b57ac5fbeaa492dadf7d28f/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/hash.scala#L560-L567
When precision is less than or equal to 18, convert i128 native value of decimal to i64 to calculate hash.
> fix: partially fix consistency issue of hash functions with decimal input

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q9/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark3_5/q9/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark4_0/q9/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4-spark4_0/q9/simplified.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q9/explain.txt
- spark/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q9/simplified.txt
- spark/src/test/scala/org/apache/spark/sql/CometTPCDSQuerySuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCHQuerySuite.scala
N/A
Fix a regression that was causing a test failure in the TPC-DS correctness tests.
> fix: [comet-parquet-exec] Fix regression in supported types

- native/core/src/execution/planner.rs
- native/proto/src/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Related to Epic: https://github.com/apache/datafusion-comet/issues/1042
array_intersect: `select array_intersect(array(1, 2, 3), array(2, 3, 4))` => `array(2, 3)`
Defined under Epic: https://github.com/apache/datafusion-comet/issues/1042
`planner.rs:` Created DataFusion `array_intersect` physical expression from Spark physical expression,
`expr.proto:` `array_intersect` message has been added,
`QueryPlanSerde.scala:` `array_intersect` pattern matching case has been added,
`CometExpressionSuite.scala:` A new UT has been added for array_intersect function.
A new UT has been added.
> Feat: Support array_intersect function

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
N/A
Fix a regression that was introduced when merging the `comet-parquet-exec` branch into `main`.
> chore: Revert accidental re-introduction of off-heap memory requirement

- native/core/src/execution/planner.rs
- native/proto/src/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Related to Epic: https://github.com/apache/datafusion-comet/issues/1042
`array_join`: `select array_join(array('hello', '-', 'world'), ' ')` => `hello - world`
DataFusion' s `array_join` function is alias of array_to_string function:
https://datafusion.apache.org/user-guide/sql/scalar_functions.html#array-join
Defined under Epic: https://github.com/apache/datafusion-comet/issues/1042
`planner.rs:` Created DataFusion `array_join` physical expression from Spark physical expression with return type: `DataType::Utf8`,
`expr.proto:` `array_join` message has been added (array_intersect is 62),
`QueryPlanSerde.scala:` `array_join` pattern matching case has been added,
`CometExpressionSuite.scala:` A new UT has been added for `array_join` function.
A new UT has been added and first query result …
> Feat: Support array_join function

- docs/source/user-guide/installation.md
Fix missing slash in spark script.
> Fix missing slash in spark script

- .github/actions/java-test/action.yaml
- .github/workflows/pr_build.yml
Closes #.
The feature `upload-test-reports` for macos-13 runner was disabled (https://github.com/apache/datafusion-comet/pull/933) previously due to https://github.com/codecov/codecov-action/issues/1549. Trying to re-enable it with upgrading to `v5`.
> build: re-enable upload-test-reports for macos-13 runner

- native/core/src/execution/memory_pool.rs
Datafusion memory pool throws `insufficient_capacity_err` https://github.com/apache/datafusion/blob/main/datafusion/execution/src/memory_pool/pool.rs#L91
and aggregation expects to see it https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/aggregates/row_hash.rs#L913
However comet memory pool was throwing an execution error that causes false OOM
existing tests
> fix: memory pool error type

- native/core/src/execution/planner.rs
- native/proto/src/proto/expr.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Related to Epic: https://github.com/apache/datafusion-comet/issues/1042
`arrays_overlap`: `select arrays_overlap(array('hello', '-', 'world'), array('hello'))` => `true`
DataFusion' s array_has_any has same behavior with Spark 's arrays_overlap function
`Spark:` https://docs.databricks.com/en/sql/language-manual/functions/arrays_overlap.html
`DataFusion:` https://datafusion.apache.org/user-guide/sql/scalar_functions.html#array-has-any
Defined under Epic: https://github.com/apache/datafusion-comet/issues/1042
`planner.rs:` Maps Spark 's `arrays_overlap` function to DataFusion `array_has_any` physical expression from Spark physical expression with return type: DataType::Boolean,
`expr.proto:` arrays_overlap message has been added,
`QueryPlanSerde.scala:` arrays_overlap pattern matching case …
> Feat: Support arrays_overlap function

- docs/source/user-guide/expressions.md
- spark/src/main/scala/org/apache/comet/serde/arrays.scala
Closes #.
The doc says ArrayRemove is experimental https://github.com/apache/datafusion-comet/blob/ea6d9508800f4fd50341dd33425a08a62b549aae/docs/source/user-guide/expressions.md?plain=1#L193
although array remove is compatible (and tested) for the types that it currently supports
Updated the doc
existing test
> fix: expressions doc for ArrayRemove

- native/spark-expr/src/math_funcs/round.rs
> fix: pass scale to DF round in spark_round

- native/Cargo.lock
- native/Cargo.toml
- native/core/src/execution/operators/filter.rs
- native/spark-expr/src/agg_funcs/avg_decimal.rs
- native/spark-expr/src/utils.rs
Closes https://github.com/apache/datafusion-comet/issues/1304
Follows on from partial upgrade in https://github.com/apache/datafusion-comet/pull/1332
I plan on bumping the DF rev in this PR until DF 45 is released.
- Small fix due to breaking change https://github.com/apache/datafusion/pull/14279
> feat: Upgrade to DataFusion 45

- docs/source/user-guide/compatibility.md
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/main/scala/org/apache/comet/testing/ParquetGenerator.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/1354
Follow on issue: https://github.com/apache/datafusion-comet/issues/1371
Fix a correctness issue
- Add test to demonstrate the bug
- Mark cast from float/double to decimal as incompatible
New test + existing tests
> fix: Mark cast from float/double to decimal as incompatible

- common/src/main/scala/org/apache/comet/CometConf.scala
- docs/source/user-guide/configs.md
- native/core/src/execution/jni_api.rs
- native/core/src/execution/metrics/utils.rs
- native/core/src/jvm_bridge/comet_metric_node.rs
- native/core/src/jvm_bridge/mod.rs
- native/proto/src/lib.rs
- native/proto/src/proto/metric.proto
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/comet/Native.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometMetricNode.scala
Closes #1328.
Improve performance of update metrics
+ Define a NativeMetricNode proto type to pass all metric nodes at once to avoid iterative jni calls.
+ Call update metrics when releasing plan to reduce the number of calls.
sql metrics are displayed correctly:
cpu profile:
> perf: improve performance of update metrics

- common/src/main/scala/org/apache/comet/CometConf.scala
- docs/source/user-guide/configs.md
- native/Cargo.lock
- native/core/Cargo.toml
- native/core/src/execution/fair_memory_pool.rs
- native/core/src/execution/jni_api.rs
- native/core/src/execution/mod.rs
- spark/src/test/scala/org/apache/spark/sql/CometTPCHQuerySuite.scala
Current Comet unified memory pool is a greedy pool. One thread (consumer) can take a large amount of memory that causes OOM for other threads, especially for aggregation.
Added a fair version of unified memory pool similar to DataFusion `FairSpilPool` that caps the memory usage at `pool_size/num`
The fair unified memory pool is the default for off-heap mode with this PR
Exisiting tests
> feat: Add fair unified memory pool

- common/src/main/scala/org/apache/comet/CometConf.scala
- docs/source/user-guide/configs.md
- native/core/src/execution/jni_api.rs
DataFusion has an unbounded memory pool. I found it useful for experimental purpose.
Added an option for unbounded memory pool.
existing tests
> feat: Add unbounded memory pool

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Closes #1391 .
It is a logic error.
Moved to a direct comparator instead of checking that Class isInstanceOf Class
I believe this is an inherent language feature, it does not need a TestSuite.
> fix: Passthrough condition in StaticInvoke case block

- .github/actions/rust-test/action.yaml
- .github/actions/setup-builder/action.yaml
- NOTICE.txt
- native/Cargo.lock
- native/Cargo.toml
- native/core/Cargo.toml
- native/hdfs/Cargo.toml
- native/hdfs/README.md
- native/hdfs/src/lib.rs
- native/hdfs/src/object_store/hdfs.rs
- native/hdfs/src/object_store/mod.rs
> chore: Adding an optional `hdfs` crate

- native/core/src/execution/planner.rs
- native/proto/src/proto/operator.proto
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Closes #.
Currently Comet has a copy of DataFusion's FilterExec that is modified to do a deep copy of a batch, even if the entire batch passes the filter predicate. https://github.com/apache/datafusion-comet/blob/4fe4f57da6339a5d66114750aee915525e601d4d/native/core/src/execution/operators/filter.rs#L487
This behavior exists because the underlying Comet Scan behavior is to reuse buffers, so it is not safe to pass pointers to them into downstream operators.
However, the experimental native scans do not have this behavior (@parthchandra please confirm this optimization is safe for `native_iceberg_compat`) , so we can use DataFusion's FilterExec, and benefit from the zero-copy fast path.
- Added boolean field to Filter's proto, set in QueryPlanSerde based on Comet native scan implementation …
> perf: Use DataFusion FilterExec for experimental native scans

- docs/source/user-guide/tuning.md
Closes #1388 
Following up on #1369 and #1386 
Updated the doc
> doc: update memory tuning guide

- spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala
Still confirming if there's a unit mismatch wrt time between Spark elapsed time and native elapsed time. Once I confirm that, I'll mark this okay for review.
> feat: CometNativeScan metrics from ParquetFileMetrics and FileStreamMetrics

- .github/actions/setup-spark-builder/action.yaml
- .github/workflows/spark_sql_test.yml
- .github/workflows/spark_sql_test_ansi.yml
- common/pom.xml
- dev/diffs/3.4.3.diff
- dev/diffs/3.5.1.diff
- dev/diffs/4.0.0-preview1.diff
- docs/source/contributor-guide/debugging.md
- docs/source/user-guide/installation.md
- fuzz-testing/README.md
- fuzz-testing/pom.xml
- native/Cargo.toml
- pom.xml
- spark-integration/pom.xml
- spark/pom.xml
> chore: Prepare for 0.7.0 development

- .github/actions/setup-spark-builder/action.yaml
- .github/workflows/spark_sql_test.yml
- .github/workflows/spark_sql_test_ansi.yml
- dev/diffs/3.4.3.diff
- dev/diffs/3.5.1.diff
- dev/diffs/4.0.0-preview1.diff
Fix incorrect Comet version in Spark diffs.
Fixing this just in case anyone wants to run Spark SQL tests locally from this branch. The tests already run correctly in CI because the Comet version is provided dynamically at runtime.
> fix: [branch-0.6] Fix Comet version in Spark diffs

- dev/release/README.md
- docs/source/user-guide/installation.md
- docs/source/user-guide/kubernetes.md
- docs/source/user-guide/source.md
- native/Cargo.lock
N/A
Now that 0.6.0 has been released, we need to update the documentation to reflect that.
> chore: Update released version in documentation

- common/pom.xml
- pom.xml
Closes #1409.
Support comet on Win-amd64
add Win-amd64 profile
Build and run test successfully on windows with amd64 cpu
> feat: add Win-amd64 profile

- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- native/core/src/parquet/schema_adapter.rs
- spark/src/main/scala/org/apache/comet/parquet/CometParquetFileFormat.scala
- spark/src/main/scala/org/apache/comet/parquet/CometParquetPartitionReaderFactory.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
- spark/src/test/scala/org/apache/spark/sql/comet/ParquetDatetimeRebaseSuite.scala
major changes :
- allow Uint64 to decimal and  FixedWidthBinary to Binary conversions in complex readers
- do not enable prefetch reads in tests if complex reader is enabled
- fix more incompatible checks in uint_8/uint_16 tests
- skip datetime rebase tests for complex readers (not supported)
There may be conflicts between this and #1413  (@mbutrovich) which removes the `cast_supported` method but can be reconciled afterwards
Without #1413 the failure counts are: 
```
native_datafusion: Tests: succeeded 658, failed 19, canceled 4, ignored 54, pending 0
native_iceberg_compat: Tests: succeeded 662, failed 15, canceled 4, ignored 54, pending 0
```
> fix: fix various unit test failures in native_datafusion and native_iceberg_compat readers

- pom.xml
To fix [CVE-2024-7254](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-7254)
Update protobuf to 3.25.5
CI
> chore: Update protobuf to 3.25.5

- pom.xml
- spark/pom.xml
To fix
[CVE-2023-2976](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-2976)
[CVE-2020-8908](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908)
[CVE-2018-10237](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-10237)
Update guava to 33.2.1-jre
CI
> chore: Update guava to 33.2.1-jre

- spark/src/main/scala/org/apache/comet/rules/RewriteJoin.scala
Related to https://github.com/apache/datafusion-comet/issues/1382
The main goal of this PR is to try and choose smaller side of join for build-side.
With this PR, many queries are now faster when compared to the 0.6.0 release.
Total time for TPC-H is 285 seconds, down from 330 seconds.
- Update RewreiteJoin to match latest version from Apache Gluten
> perf: Update RewriteJoin logic to choose optimal build side

- .github/actions/rust-test/action.yaml
N/A
CI fails with the recently released machete 0.8.0
```
Downloaded cargo-machete v0.8.0
error: failed to parse manifest at `/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-machete-0.8.0/Cargo.toml`
Caused by:
feature `edition2024` is required
The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).
```
> build: pin machete to version 0.7.0

- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
Partially addresses some of the issues tracked in #1441.
Test metrics values in CometNativeScan (native_datafusion experimental native scan). Fixing metrics for native_iceberg_compat will be a larger effort similar to #1172.
- Modified ParquetReadSuite's metrics test to handle `CometNativeScan` node and metrics.
- Modified CometExecSuite's metrics test to handle `CometNativeScan` node and metrics.
- My IDE likes to reformat stuff, but I ran `make format` after so it should still be compliant.
Local testing since experimental native scans are not in CI yet.
> fix: metrics tests for native_datafusion experimental native scan

- native/core/src/execution/shuffle/shuffle_writer.rs
Closes https://github.com/apache/datafusion-comet/issues/1448
We were reserving memory twice in native shuffle, resulting in excessive shuffling.
Here are results for TPC-H q9 with 3GB off-heap memory allocated:
```
42.215020418167114,
43.29415225982666,
40.11583089828491,
40.11201024055481,
36.295708417892456
```
```
33.27595615386963,
30.483699560165405,
31.230262994766235,
31.28650164604187,
31.095990657806396
```
Stop double reserving memory.
> perf: Reduce native shuffle memory overhead by 50%

- native/core/src/execution/planner.rs
- native/proto/src/proto/expr.proto
- native/spark-expr/benches/decimal_div.rs
- native/spark-expr/src/comet_scalar_funcs.rs
- native/spark-expr/src/lib.rs
- native/spark-expr/src/math_funcs/div.rs
- native/spark-expr/src/math_funcs/mod.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Closes #1422.
Support IntegralDivide function
Since datafusion div operator conforms to the logic of intergal div, we only need to convert `IntegralDivide(...)` to `Cast(Divide(...), LongType)` and then convert it to native.
> feat: Support IntegralDivide function

- native/core/benches/perf.rs
- native/core/src/common/bit.rs
- native/core/src/errors.rs
- native/core/src/execution/operators/scan.rs
- native/core/src/execution/sort.rs
- native/core/src/jvm_bridge/mod.rs
- native/core/src/parquet/data_type.rs
- native/spark-expr/src/agg_funcs/variance.rs
- rust-toolchain.toml
Closes https://github.com/apache/datafusion-comet/issues/1466
There is a new version of `rustup` and it causing builds to fail.
Use "stable" channel instead of pinning to a Rust version in the `rust-toolchain` file. We already pin the Rust version in `Cargo.toml`.
> build: Use stable channel in rust-toolchain

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/spark/Plugins.scala
- spark/src/test/scala/org/apache/spark/CometPluginsSuite.scala
Closes #1460 .
Even when using unified memory, Comet would override `spark.executor.memoryOverhead` using inconsistent byte units.
This situation should not have happened in the first place.
Fixes for
* `shouldOverrideMemoryConf`
* Adds result of `getCometShuffleMemorySizeInMiB` to executor memoryOverhead 
Added `CometPluginsNonOverrideUnifiedModeSuite` to test that `spark.executor.memoryOverhead` is not overridden, which failed in previous versions.
> fix: Executor memory overhead overriding

- .github/workflows/pr_build.yml
- common/src/main/scala/org/apache/comet/CometConf.scala
- spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
Part of https://github.com/apache/datafusion-comet/issues/1486
To prevent regressions and track progress with supporting `native_datafusion`, I would like to start enabling CI runs with this scan as the default.
> chore: Enable CI checks for `native_datafusion` scan

- .github/workflows/pr_build.yml
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
- spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala
Part of https://github.com/apache/datafusion-comet/issues/1486
We recently added a GitHub job to test with `native_datafusion` as the default scan implementation. This PR extends this to also test with `native_iceberg_compat`.
- Update CI
- Skip some tests that currently fail, with links to issues
> chore: Add `native_iceberg_compat` CI checks

- native/core/src/execution/shuffle/shuffle_writer.rs
Closes #1495 .
It lets MemoryPools have a better grasp of the amount of operators actually running and requiring memory, as many of them use that count to determine the memory needs and allowances of each consumer.
Created a single MemoryConsumer in the ShuffleRepartitioner, and split it off into a reservation for each PartitionBuffer, instead of having them create their own.
> fix: PartitionBuffers should not have their own MemoryConsumer

- docs/source/user-guide/compatibility.md
- native/spark-expr/src/conversion_funcs/cast.rs
- spark/src/main/scala/org/apache/comet/GenerateDocs.scala
- spark/src/main/scala/org/apache/comet/expressions/CometCast.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Closes #375 
- enable decimal to decimal
-  remove hard coded  castoptions to pass to native execution
- fixed castTest to match arrow invalid argument error with spark's Number out of range error.
Closes #.
> fix: enable full decimal to decimal support

- native/core/src/execution/shuffle/shuffle_writer.rs
Also: 
* treat all single partition schemes the same way
* remove duplicate messaging by using assert_eq instead of assert
None really, but it can be seen as cleanup towards #1497 
It was just an unneeded field in a file that is already a bit complex with too many structs.
this information is always accessible, from multiple places.
With the normal testing scheme.
> chore: Remove num partitions from repartitioner

- native/Cargo.lock
- native/Cargo.toml
- native/core/src/execution/planner.rs
- native/core/src/parquet/mod.rs
- native/core/src/parquet/parquet_support.rs
Addresses part of comments in https://github.com/apache/datafusion-comet/pull/1443
Replaces the `register_object_store` method that provided hdfs support with a unified `prepare_object_store` method.
> fix: use common implementation of handling object store and hdfs urls for native_datafusion and native_iceberg_compat

- native/core/src/execution/shuffle/shuffle_writer.rs
Closes #1516 .
I feel like these are 30ish lines of redundant code(as well as imports etc) as Datafusion already provides a perfectly identical struct, so we might as well use it^
Shuffle tests both on Rust side and Spark side are enough to test this.
> chore: Use Datafusion's existing empty stream

- .github/actions/java-test/action.yaml
N/A
I have recently seen some build failures due to:
```
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
Example:
```
Run actions/upload-artifact@v4
with:
name: java-test-reports-13907435863
path: **/target/surefire-reports/*.txt
retention-days: 7
overwrite: true
if-no-files-found: warn
compression-level: 6
include-hidden-files: false
env:
RUST_VERSION: stable
JAVA_HOME: /__t/Java_Zulu_jdk/17.0.14-7/x64
JAVA_HOME_17_X64: /__t/Java_Zulu_jdk/17.0.14-7/x64
/usr/bin/docker exec  70ccce69d6cca5445b60eaedb1395aabda91e4f16400c4e06aef42fc0a773435 sh -c "cat /etc/*release | grep ^ID"
With the provided path, there will be 4 files uploaded
Artifact name is valid!
Root directory input is …
```
> build: Use unique name for surefire artifacts

- docs/source/contributor-guide/spark-sql-tests.md
Closes #.
We don't need the whole Spark repository to run Spark SQL tests.
Current approach:
```
git clone git@github.com:apache/spark.git apache-spark
du -h apache-spark
...
680M	apache-spark
```
Proposed change:
```
git clone -b 'v3.4.3' --single-branch --depth 1 git@github.com:apache/spark.git apache-spark
du -h apache-spark
...
200M	apache-spark
```
Docs update to reflect this approach with a disclaimer that it's a shallow clone.
Ran Spark SQL tests locally using this approach. CI uses a different method that likely already has this optimization:
https://github.com/apache/datafusion-comet/blob/359b4b37a2bd3af1c462d443cf845758d64fb179/.github/actions/setup-spark-builder/action.yaml#L38
> docs: Use a shallow clone for Spark SQL test instructions

- native/core/src/execution/planner.rs
- native/core/src/parquet/mod.rs
- native/core/src/parquet/parquet_exec.rs
Removes code duplication between the native_datafusion and the native_iceberg_compat implementations. 
Datafusion parquet_exec is now called thru functions in `parquet_exec.rs.`
The PR also unifies object store handling and encapsulates the `register_object_store` method that provided hdfs support.
> fix: remove code duplication in native_datafusion and native_iceberg_compat implementations

- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
Part of #1553
Check that the handle is initialized before closing to avoid native thread panic.
before this:
after this:
> fix: check if handle has been initialized before closing

- common/src/main/scala/org/apache/comet/CometConf.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCDSQueryTestSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCHQuerySuite.scala
- spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala
N/A
Enable Comet support explicitly rather than rely on default setting.
> chore: Enable Comet explicitly in `CometTPCDSQueryTestSuite`

- native/core/src/execution/shuffle/codec.rs
Closes #1520.
This is a problem I found when working on https://github.com/apache/datafusion-comet/pull/1511, the null bits were not correctly written and caused test failures. This patch is an attempt to fix it.
This patch is only aiming for fixing correctness problems. As https://github.com/apache/datafusion-comet/pull/1190#discussion_r1911955126 pointed out, the fast BatchWriter may write full data buffer for sliced `Utf8` arrays, so there's still some performance implications when working with sliced arrays.
Correctly take slicing indices and length into account when writing BooleanBuffers. This applies to null bits of all arrays, and the values of boolean arrays.
Added a new round-trip test for sliced record batches.
> fix: Taking slicing into account when writing BooleanBuffers as fast-encoding format

- native/core/Cargo.toml
- pom.xml
- spark/pom.xml
- spark/src/test/scala/org/apache/comet/WithHdfsCluster.scala
- spark/src/test/scala/org/apache/spark/sql/benchmark/CometReadBenchmark.scala
Closes #1515.
test native scan on hdfs
introduce hadoop mini cluster to test native scan on hdfs
Successfully run `CometReadHdfsBenchmark` locally (tips: build native enable hdfs: `cd native && cargo build --features hdfs`)
> feat: introduce hadoop mini cluster to test native scan on hdfs

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/CometSparkSessionExtensionsSuite.scala
We have a name collision on `isCometEnabled`
```
CometSparkSessionExtensions
private[comet] def isCometEnabled(conf: SQLConf): Boolean = {
```
and
```
SQLTestUtilsBase
protected def isCometEnabled: Boolean = SparkSession.isCometEnabled
```
causing build issues depending on which one gets picked up
```
[ERROR] /workspace/spark/src/test/scala/org/apache/comet/CometSparkSessionExtensionsSuite.scala:34: Boolean does not take parameters
[ERROR] /workspace/spark/src/test/scala/org/apache/comet/CometSparkSessionExtensionsSuite.scala:42: Boolean does not take parameters
[ERROR] /workspace/spark/src/test/scala/org/apache/comet/CometSparkSessionExtensionsSuite.scala:47: Boolean does not take parameters
```
Renamed one to `isCometLoaded`
CI
> fix: isCometEnabled name conflict

- native/core/src/parquet/parquet_exec.rs
- native/core/src/parquet/parquet_support.rs
- native/core/src/parquet/schema_adapter.rs
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
Part of #1574.
The data schema of spark parquet datasource scan may not be consistent with the actual schema of file. This may cause the `projection/filter` to not behave as expected.
This PR makes `data schema` and `file schema` case insensitive in schema adapter, but it does not affect `pruning_predicate` and `page_pruning_predicate`.
> feat: make parquet native scan schema case insensitive

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
Part of  #1454 .
Enable Iceberg compat type tests, add more tests for complex types
> feat: enable iceberg compat tests, more tests for complex types

- .github/workflows/spark_sql_test.yml
- dev/diffs/3.5.4.diff
- spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala
Closes #1572
Users with older 3.5.x versions before Spark 3.5.5 should be able using the latest comet version.
Modifying the 3.5 `ShimCometScanExec` shim to fallback to reflection with the previous method signatures if the latest is not found.
Ran `mvn test` with the `spark-3.5` profile.
Added 3.5.4 to the matrix of tested spark versions in `spark_sql_test.yml`
> added fallback using reflection for backward-compatibility

- spark/src/main/scala/org/apache/spark/sql/comet/CometSparkToColumnarExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #936.
Previous PR went stale so I wanted to move it forward.
Added unit tests for row and columnar input.
> chore: Override node name for CometSparkToColumnar

- common/src/main/java/org/apache/comet/parquet/Native.java
- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- native/core/src/execution/planner.rs
- native/core/src/parquet/mod.rs
- spark/src/main/scala/org/apache/comet/parquet/CometParquetFileFormat.scala
- spark/src/main/scala/org/apache/comet/parquet/CometParquetPartitionReaderFactory.scala
- spark/src/main/scala/org/apache/comet/parquet/ParquetFilters.scala
- spark/src/main/scala/org/apache/comet/parquet/SourceFilterSerde.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Closes #1562.
Improve performance of native_iceberg_compat scan
> feat: pushdown filter for native_iceberg_compat

- .github/workflows/pr_build.yml
- docs/source/user-guide/installation.md
Closes https://github.com/apache/datafusion-comet/issues/1579
Run Comet tests for 3.5.2 through 3.5.4 to avoid introducing regressions for those releases
> chore: Run Comet tests for more Spark versions

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala
Closes #1314 and #1588.
`EliminateRedundantTransitions` eliminates the required `ColumnarToRowExec`
+ For Spark Columnar to Comet Columnar of CometSparkToColumnarExec, we should keep the ColumnarToRowExec
+ For Spark Row to Comet Columnar of CometSparkToColumnarExec, we should remove ColumnarToRowExec and CometSparkToColumnarExec
unit test
> fix: corrected the logic of eliminating CometSparkToColumnarExec

- common/src/main/java/org/apache/comet/parquet/Native.java
- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- native/core/src/execution/planner.rs
- native/core/src/parquet/mod.rs
- spark/src/main/scala/org/apache/comet/parquet/CometParquetFileFormat.scala
Closes #1571.
Respect `batchSize/workerThreads/blockingThreads` configurations for native_iceberg_compat scan
+ Set `COMET_BATCH_SIZE/COMET_WORKER_THREADS/COMET_BLOCKING_THREADS` for NativeBatchReader
+ Use planer's session_ctx instead of new task_ctx
Successfully run `CometReadHdfsBenchmark` locally.
[CometReadHdfsBenchmark-results.txt](https://github.com/user-attachments/files/19545171/CometReadHdfsBenchmark-results.txt)
> feat: respect `batchSize/workerThreads/blockingThreads` configurations for native_iceberg_compat scan

- native/core/src/execution/shuffle/row.rs
- native/spark-expr/src/agg_funcs/correlation.rs
Closes #.
Rust clippy check fails when I submit https://github.com/apache/datafusion-comet/pull/1605, this is one of the failed runs: https://github.com/apache/datafusion-comet/actions/runs/14241125683/job/39911060021. This could be caused latest updates of clippy.
Fix clippy to make CI pass
Passing the CI
> minor: Fix clippy warnings

- native/core/src/parquet/mod.rs
- spark/src/test/scala/org/apache/comet/CometNativeSuite.scala
Closes #1553.
avoid panic caused by close null handle of parquet reader
`get_context/get_batch_context` wraps the null check, so I use `get_context/get_batch_context` to get the context to be released to avoid panic.
> fix: avoid panic caused by close null handle of parquet reader

- common/src/main/scala/org/apache/spark/sql/comet/execution/arrow/ArrowReaderIterator.scala
- common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometColumnarToRowExec.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
This PR should be merged after https://github.com/apache/datafusion-comet/pull/1606
Closes #1589.
`CometBroadcastExchangeExec` didn't implement `outputPartitioning` method, this prevents CometBroadcastExchangeExec from being correctly generated in AQE optimization. This patch fixes this problem to make shuffled equi-joins being able to be optimized to CometBroadcastHashJoin by AQE.
This PR contains 2 fixes to make AQE broadcast join optimization work correctly for Comet:
1. Implement `outputPartitioning` method of `CometBroadcastExchangeExec`, also fixes other places that prevents the AQE optimization from happening.
2. Implement `doExecuteBroadcast` method of `CometColumnarToRowExec`. The parent of `CometBroadcastExchangeExec` may change to Spark `BroadcastHashJoinExec` during AQE …
> fix: Make AQE capable of converting Comet shuffled joins to Comet broadcast hash joins

- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometNativeShuffleWriter.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleDependency.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala
- spark/src/test/scala/org/apache/comet/exec/CometNativeShuffleSuite.scala
Closes #1567.
Shuffle file deletes were handled by the [`unregisterShuffle`](https://github.com/apache/datafusion-comet/blob/0.7.0/spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala#L214-L221) method of shuffle manager. `CometShuffleManager` uses a map [taskIdMapsForShuffle](https://github.com/apache/datafusion-comet/blob/0.7.0/spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala#L58-L61) to keep track of which shuffle files to delete for a given task. This map only gets updated when [`getWriter`](https://github.com/apache/datafusion-comet/blob/0.7.0/spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala#L175-L184) is called.
In JVM shuffle mode, shuffle writers are …
> fix: Making shuffle files generated in native shuffle mode reclaimable

- native/core/src/execution/jni_api.rs
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/comet/Native.scala
- spark/src/test/scala/org/apache/comet/CometNativeSuite.scala
Closes #1607.
Comet native operators always write spill files into the default tmp directory, this is not always the desired behavior. There are cases where we want to write spill files into Spark local directories:
1. The default tmp directory is too small to hold spill files, a special volume is configured for Spark to write temporary files and shuffle data/index files.
2. Multiple directories are configured as Spark local directories. These directories could be backed by multiple physical devices to have a larger overall disk read/write throughput. Spark will spread spill files and shuffle data/index files evenly onto these local directories by default, comet should also do that when writing spill files.
All the above mentioned cases are quite common for running Spark jobs on …
> chore: Making comet native operators write spill files to spark local dir

- common/src/main/java/org/apache/comet/parquet/Native.java
- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- common/src/main/scala/org/apache/comet/CometConf.scala
- docs/source/user-guide/tuning.md
- native/core/src/execution/jni_api.rs
- native/core/src/parquet/mod.rs
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/comet/Native.scala
- spark/src/main/scala/org/apache/comet/parquet/CometParquetFileFormat.scala
Closes https://github.com/apache/datafusion-comet/issues/1590
Helps with https://github.com/apache/datafusion-comet/issues/1523
If I configure Spark executor with 8GB + 1GB offHeap and using default settings for tokio threads, q4 hangs in main branch, but completes with these changes.
- Allocate one global tokio runtime per process (executor) rather than create one runtime per query
- Use tokio defaults for number of threads
- Allow tokio thread counts to be configured with env vars
Based on an executor configured for 8 concurrent tasks and 1 core per task, the defaults for the overall process now change as follows:
| Config | Before | After |
|-|-|-|
| worker threads | 32 | 8 |
| max blocking threads | 80 | 512 |
Manual testing. I do not see any change in overall TPC-H performance, but I …
> perf: Use a global tokio runtime

- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometNativeShuffleWriter.scala
- spark/src/test/scala/org/apache/spark/sql/comet/CometTaskMetricsSuite.scala
Closes #1616 .
Shuffle write records and shuffle write time are missing in per-task metrics, which makes it inconvenient to troubleshoot query performance problems.
Expose shuffle write rows and shuffle write time to task metrics.
Before:
After:
1. Added unit test
2. Tested manually in local environment
> fix: Support per-task shuffle write rows and shuffle write time metrics

- .github/actions/setup-spark-builder/action.yaml
- .github/workflows/docker-publish.yml
- docs/source/contributor-guide/debugging.md
- docs/source/contributor-guide/development.md
- docs/source/user-guide/datasources.md
- docs/source/user-guide/installation.md
- docs/source/user-guide/source.md
- kube/Dockerfile
- native/spark-expr/src/agg_funcs/correlation.rs
- pom.xml
Closes https://github.com/apache/datafusion-comet/issues/1467
Spark 3.5 was released in 2023 so it is probably time that we made this the default rather than 3.4.
> chore: Change default Spark version to 3.5

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
N/A
In https://github.com/apache/datafusion-comet/pull/1483, we refactored the logic for translating v1 data source scans into Comet scans and reduced duplication and fixed some bugs.
This PR applies a similar refactoring to the v2 handling to make it consistent. In this case no bugs were found and there are no functional changes other than improving one fallback message to now mention Iceberg in addition to Parquet.
> chore: refactor v2 scan conversion

- dev/diffs/3.4.3.diff
- dev/diffs/3.5.4.diff
- dev/diffs/3.5.5.diff
Closes #1640. Partially address #1545 by reducing test failures.
- Add support to Spark tests for new CometNativeScanExec node type.
- Regenerate 3.5.5 diff with hash length of 11 to match other diffs.
Running core 2 Spark SQL tests with `native_datafusion` locally went from 197 failures to 98.
> fix: Modify Spark SQL core 2 tests for `native_datafusion` reader, change 3.5.5 diff hash length to 11

- .github/workflows/spark_sql_test_native_datafusion.yml
The name of the pipelines in the native_datafusion ci workflow was confusingly called native_iceberg_compat
> chore: correct name of pipelines for native_datafusion ci workflow

- native/core/src/execution/jni_api.rs
Closes #.
track unified memory pool
Wrap unified memory pool with TrackConsumersPool
after this:
```
25/04/15 22:01:13 WARN TaskSetManager: Lost task 0.0 in stage 32.0 (TID 8219) (10.5.154.255 executor driver): org.apache.comet.CometNativeException: Resources exhausted: Additional allocation failed with top memory consumers (across reservations) as: HashJoinInput[0] consumed 16737056 bytes, GroupedHashAggregateStream[0] consumed 0 bytes. Error: Failed to acquire 106560 bytes, only got 40160. Reserved: 16737056
at org.apache.comet.Native.executePlan(Native Method)
at org.apache.comet.CometExecIterator.$anonfun$getNextBatch$1(CometExecIterator.scala:137)
at org.apache.comet.CometExecIterator.$anonfun$getNextBatch$1$adapted(CometExecIterator.scala:135)
```
> feat: track unified memory pool

- common/src/main/java/org/apache/comet/parquet/BatchReader.java
- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
Part of #1542 
In some cases, the field that is being requested does not exist in the file being read. With primitive types, one has to check if the default value is defined and if so return the default value (otherwise return null). With complex types, we merely return null. Existing code was trying to treat complex types the same way as primitive types and failing an internal assertion.
Spark SQL tests 
(Note: I also added a comment that was requested in a previous PR, not related to this change).
> fix: handle missing field correctly in native_iceberg_compat

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/serde/hash.scala
- spark/src/test/scala/org/apache/comet/CometFuzzTestSuite.scala
Closes #.
- Use common `supportedDataType` method for columnar and native shuffle
- Add `TimestampNTZType` as a supported type
- Add fuzz test for shuffle that asserts that shuffle is native when experimental native scans are enabled
> feat: Add support for complex types in native shuffle

- spark/src/test/scala/org/apache/comet/CometFuzzTestSuite.scala
N/A
#1652 added better int96 support for experimental native scans (relying on CometCastSuite and other Parquet tests) but did not enable CometFuzzTestSuite because it uses complex types by default. There's an [issue](https://github.com/apache/datafusion/issues/15763) in DF's schema coercion for complex types.
This PR modifies the test to get coverage with the int96 data type without complex types.
New test coverage.
> chore: Enable CometFuzzTestSuite int96 test for experimental native scans (without complex types)

- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
Part of https://github.com/apache/datafusion-comet/issues/1542
Addresses more sql test failures
In BatchScan, the batch reader updates an internal metric directly for every row group that we read. in native_iceberg_compat this code was commented out because at that time the exact row group count was not available. With recent fixes, this count is now trivially available. This addresses sql test failures which were using this metics to verify that row group filtering was working correctly.
Spark sql tests
> fix: update row groups count in internal metrics accumulator

- docs/source/user-guide/datasources.md
- kube/local/hadoop.env
- kube/local/hdfs-docker-compose.yml
When I was working on https://github.com/apache/datafusion-comet/pull/1649 I realized it takes time to resume local HDFS setup for local testing and it would be nice to have it documented
Closes #.
> doc: Document local HDFS setup

- .github/workflows/miri.yml
- native/Cargo.lock
- native/Cargo.toml
- native/core/Cargo.toml
- native/core/benches/bit_util.rs
- native/core/benches/common.rs
- native/core/benches/parquet_read.rs
- native/core/src/common/bit.rs
- native/core/src/errors.rs
- native/core/src/execution/planner.rs
- native/core/src/execution/serde.rs
- native/core/src/parquet/util/test_common/page_util.rs
- native/core/src/parquet/util/test_common/rand_gen.rs
- native/proto/Cargo.toml
- native/spark-expr/Cargo.toml
Reduce the amount of duplicate crates due to crates that use outdated versions, thereby improving compile times and reducing binary size.
Some of the crates(such as rand) have also made changes due to upcoming Rust Compiler changes that would give them compilation errors(reserved keywords, in this case, I believe)
Update crate versions, removed some unused crates, removed crate versions when using "path"(for less maintenance), and moved to use the crates.io version of datafusion now that its released(it was left on the git version)
For the rand crate, updated the usage based on the deprecation warnings. 
Firstly by compilation, then all the tests passing normally should be enough.
As for timing and crate count:
branch `main`
Binary size - 75MBs (release build)
branch `update-crates` …
> chore: Update viable crates

- common/pom.xml
- fuzz-testing/pom.xml
- pom.xml
- spark/pom.xml
Closes #. https://github.com/apache/datafusion-comet/issues/1631
Match Maven plugin versions with Spark 3.5.5
- Match plugin versions with Spark 3.5.5
- Parameterized plugin versions
> chore: match Maven plugin versions with Spark 3.5

- native/Cargo.lock
- native/core/Cargo.toml
- native/core/src/lib.rs
Closes #1648.
Comet currently supports mimalloc to override the system memory allocator (`make release COMET_FEATURES=mimalloc` or `cargo build --features=mimalloc`). We want to explore jemalloc ([tikv-jemallocator](https://lib.rs/crates/jemallocator) crate) as an alternative to mimalloc for our custom allocator.  I will bring some discussion from #1648:
https://github.com/apache/datafusion-comet/issues/1648#issuecomment-2821590325
> FYI: We found mimalloc to be unstable for running long term (keeps memory allocated but seems doesn't release it over time => running into OOMs much more easily). Switching to jemalloc fixed this.
https://github.com/apache/datafusion-comet/issues/1648#issuecomment-2821819183
> We prefer to use jemalloc with Comet by setting LD_PRELOAD, as it returns freed …
> feat: add jemalloc as optional custom allocator

- docs/source/contributor-guide/benchmarking.md
- docs/source/contributor-guide/benchmarking_macos.md
Closes https://github.com/apache/datafusion-comet/issues/1648 (sort of .. this PR will explain why the benchmark results are unstable on macOS)
> docs: Add instructions on running TPC-H on macOS

- common/pom.xml
- common/src/main/java/org/apache/arrow/c/AbstractCometSchemaImporter.java
- common/src/main/java/org/apache/comet/CometSchemaImporter.java
- common/src/main/java/org/apache/comet/parquet/BatchReader.java
- common/src/main/java/org/apache/comet/parquet/ColumnReader.java
- common/src/main/java/org/apache/comet/parquet/LazyColumnReader.java
- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- common/src/main/java/org/apache/comet/parquet/NativeColumnReader.java
- common/src/main/java/org/apache/comet/parquet/SupportsComet.java
- common/src/main/java/org/apache/comet/parquet/Utils.java
- docs/source/user-guide/datasources.md
- docs/source/user-guide/iceberg.md
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
Part of https://github.com/apache/datafusion-comet/issues/1618
Closes https://github.com/apache/datafusion-comet/issues/1684
Tell users how to integrate Comet with Iceberg.
- Documentation
- Refactoring to avoid a shading issue
> docs: Add documentation for accelerating Iceberg Parquet scans with Comet

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
N/A
The message "OPERATOR is not native because the following children are not native: ..." is not very helpful. I originally asked for this feature, but I think we should remove it. We really just want to know why the first operator falls back to Spark.
> chore: Remove fallback reason "because the children were not native"

- fuzz-testing/src/main/scala/org/apache/comet/fuzz/Meta.scala
Closes #.
There's a typo in our fuzz test query generator. `instr` is misspelled as `in_str` which will fail to bind.
Fix the typo.
> fix: typo for `instr` in fuzz testing

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/serde/arrays.scala
- spark/src/main/scala/org/apache/comet/serde/hash.scala
`scalarExprToProto` is actually a wrapper over scalar function, picking more precise name
Closes #.
> chore: Rename `scalarExprToProto` to `scalarFunctionExprToProto`

- common/src/main/java/org/apache/arrow/c/AbstractCometSchemaImporter.java
- common/src/main/java/org/apache/comet/CometSchemaImporter.java
- common/src/main/java/org/apache/comet/parquet/BatchReader.java
- common/src/main/java/org/apache/comet/parquet/ColumnReader.java
- common/src/main/java/org/apache/comet/parquet/LazyColumnReader.java
- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- common/src/main/java/org/apache/comet/parquet/NativeColumnReader.java
- common/src/main/java/org/apache/comet/parquet/Utils.java
- docs/source/user-guide/datasources.md
- docs/source/user-guide/iceberg.md
- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
N/A
Backport #1683 to branch-0.8
> docs: Add documentation for accelerating Iceberg Parquet scans with Comet [branch-0.8] 

- native/spark-expr/src/conversion_funcs/cast.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometFuzzTestSuite.scala
Closes #.
Spark SQL's `decode` with two arguments converts a binary column to a string given an encoding from one of 'US-ASCII', 'ISO-8859-1', 'UTF-8', 'UTF-16BE', 'UTF-16LE', 'UTF-16'. 
https://github.com/apache/spark/blob/ef336ad51ba62e64a77896b9da12791051fa92cb/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/stringExpressions.scala#L3028.
Comet currently has no support for this expression, and this PR adds 'UTF-8' support.
Convert a `StringDecode` expression to a `Cast` but only for the 'UTF-8' case. This scenario maps nicely to an Arrow cast with the safe option to replace invalid values with nulls:
https://github.com/apache/arrow-rs/blob/07093a49eface9be9208dd427b810abba8d0a755/arrow-cast/src/cast/string.rs#L342
Other encodings are currently unsupported, however …
> feat: decode() expression when using 'utf-8' encoding

- common/src/main/scala/org/apache/comet/CometConf.scala
- native/Cargo.lock
- native/core/Cargo.toml
- native/core/src/execution/jni_api.rs
- spark/src/main/scala/org/apache/comet/CometExecIterator.scala
- spark/src/main/scala/org/apache/comet/Native.scala
Closes https://github.com/apache/datafusion-comet/issues/1701
We need a way to profile memory.
Logging of JVM and native memory utilization on each call to `execute_plan`. After running TPC-H locally with 8GB executor memory and 8GB off-heap memory, I see these stats:
```
JVM_MEMORY: { heapUsed: 2696, heapCommitted: 4394, nonHeapUsed: 142, nonHeapCommitted: 160 }
NATIVE_MEMORY: { resident: 11531.53 }
```
When running with multiple iterations, I see overall memory exceeding 16GB. If this were running in a container environment then I would expect to see the executor be killed due to OOM.
```
JVM_MEMORY: { heapUsed: 4217, heapCommitted: 7440, nonHeapUsed: 145, nonHeapCommitted: 165 }
NATIVE_MEMORY: { resident: 18406.37 }
```
> perf: Add memory profiling

- native/core/src/execution/memory_pools/unified_pool.rs
N/A
If we drop memory pools before all bytes are freed, it could lead to a memory leak over time. I would like to know if/when this is happening.
Add a check when dropping memory pools.
> minor: Warn if memory pool is dropped with bytes still reserved

- spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes #.
See https://github.com/apache/datafusion-comet/issues/1719
Fallback for bucketed scan when using native_datafusion.
Existing Spark SQL tests.
> fix: Bucketed scan fallback for native_datafusion Parquet scan

- dev/diffs/3.4.3.diff
- dev/diffs/3.5.4.diff
- dev/diffs/3.5.5.diff
- dev/diffs/4.0.0-preview1.diff
Closes #.
DataSourceExec (and by extension, underlying arrow-rs Parquet reader) does not support metadata columns like row_index. For now, because we don't have the metadata string at Comet plan transformation (to write a fallback) we have to just skip the Spark SQL tests.
New diffs to skip row index suite in Spark SQL tests when using native_datafusion Parquet scan.
Existing Spark SQL tests.
> fix: Skip row index Spark SQL tests for native_datafusion Parquet scan

- native/core/src/execution/memory_pools/unified_pool.rs
- spark/src/main/java/org/apache/spark/CometTaskMemoryManager.java
Closes #1733.
+ Check acquired memory when CometMemoryPool grows
+ Log memory usage
> fix: Check acquired memory when CometMemoryPool grows

- spark/src/main/java/org/apache/spark/CometTaskMemoryManager.java
Closes https://github.com/apache/datafusion-comet/issues/1726
Fix a data race that caused negative memory use to be reported
Use AtomicLong instead of long to track used memory.
Manually.
> fix: Fix data race in memory profiling

- dev/diffs/3.4.3.diff
- dev/diffs/3.5.5.diff
- dev/diffs/4.0.0-preview1.diff
Related to https://github.com/apache/datafusion-comet/issues/1737
Since merging https://github.com/apache/datafusion-comet/pull/897, we now fall back to Spark when DPP is enabled, so we no longer need to ignore all of the DPP tests in Spark SQL.
- Enable 12 tests that were previously ignored but are now passing
- Update issue link for three tests that still fail
I only updated the diffs for `3.5.5` and `4.0.0-preview1` since they are the main focus.
> fix: Enable some DPP Spark SQL tests

- native/core/src/execution/memory_pools/unified_pool.rs
Although the `acquired` is always equal to the `additional` due to the current implicit semantics, it’s still better to make this logic explicit for clarity and better maintainability.
> chore: Correct memory acquired size in unified memory pool

- native/core/src/execution/planner.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Currently native execution for null literal creation for map and list will fail
Added null literal map and list support
Added a test
> fix: support literal null list and map

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/DataTypeSupport.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometBatchScanExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometSparkToColumnarExec.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
- spark/src/test/scala/org/apache/spark/sql/comet/ParquetDatetimeRebaseSuite.scala
N/A
This is a step towards some other changes that I am trying to make related to native scans.
The current implementation of DataTypeSupport has an `isGloballySupported` method, but it contains rules that are specific to one type of native scan, which I found confusing.
Remove `isGloballySupported` and `isAdditionallySupported`. Now we just have `isTypeSupported`, which can be overridden as needed.
`DataTypeSupport` is currently implemented by the following classes, which are all updated in this PR.
- CometScanExec
- CometNativeScanExec
- CometBatchScanExec
- CometSparkToColumnarExec
Existing tests
> chore: Refactor DataTypeSupport

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/rules/CometExecRule.scala
- spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/CometFuzzTestSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
- spark/src/test/scala/org/apache/spark/sql/comet/ParquetDatetimeRebaseSuite.scala
N/A
Fixing technical debt in preparation for other improvements for native scans and complex type support
- Move some type checking logic into the native scan execs
- Improve fallback message for native scans reading byte/short
- Move `usingDataSourceExec` and `usingDataSourceExecWithIncompatTypes` into `CometTestBase`
- Reimplement type-checking logic when determining if a Comet sink is supported
- Add one more fuzz test for shuffle, for more coverage
- Add a check that we were missing for falling back to Spark for GROUP BY on complex types
> chore: More refactoring of type checking logic

- docs/source/contributor-guide/benchmarking_macos.md
It seems like `tpcbench.py` in `datafusion-benchmarks` no longer take `name` as argument. This pr removes `--name` in `benchmarking_macos.md` 
See: https://github.com/apache/datafusion-benchmarks/blob/e82732f0f55998588ebe41cc49760575e82842db/runners/datafusion-comet/tpcbench.py#L113
> docs: Remove outdated param in macos bench guide

- .github/workflows/spark_sql_test.yml
- dev/diffs/3.5.5.diff
Closes https://github.com/apache/datafusion-comet/issues/1488
Part of https://github.com/apache/datafusion-comet/issues/1441
Follows on from https://github.com/apache/datafusion-comet/pull/1762
Ignore the remaining failing tests in hive-1 because the new native scans do not support encryption yet.
Update Spark diff.
> chore: [native_iceberg_compat / native_datafusion] Ignore Spark SQL Parquet encryption tests

- native/core/src/parquet/parquet_support.rs
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #1754 
In schema_adapter Map types are cast using arrow's cast which assumes that all nested fields within the map are also castable. However, the check to verify if the fields can be cast does not take into account nested struct fields with a different number of fields. 
The PR changes the cast method to a copy of the original that calls the schema adapter's struct cast method which can handle such structs
Unit test was already added. This PR enables the test
> fix: cast map types correctly in schema adapter

- .github/actions/java-test/action.yaml
- spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/1776
> chore: Upload crash logs if Java tests fail

- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- common/src/main/java/org/apache/comet/parquet/TypeUtil.java
- common/src/main/scala/org/apache/spark/sql/comet/parquet/CometParquetReadSupport.scala
- conf/log4rs.yaml
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
Part of https://github.com/apache/datafusion-comet/issues/1542
Closes #.
This addresses test failures due to incompatibilities in schema conversion and validation between Spark and the native_iceberg_compat Scan
The implementation now does nearly identical conversion and checking to Spark. Keeping with the original native_comet implementation, the changes duplicates some code from Spark.
> fix: correct schema type checking in native_iceberg_compat

- .github/workflows/pr_build.yml
- docs/source/contributor-guide/development.md
- docs/source/user-guide/installation.md
- pom.xml
Closes https://github.com/apache/datafusion-comet/issues/1775
We want to upgrade to arrow-java 18.3.0 to pick up an important bug fix, but arrow-java no longer supports Java 8.
> chore: Drop support for Java 8

- common/src/main/scala/org/apache/comet/CometConf.scala
- spark/src/main/scala/org/apache/comet/rules/CometExecRule.scala
- spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala
- spark/src/main/scala/org/apache/comet/rules/EliminateRedundantTransitions.scala
- spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala
N/A
I am trying to help debug a test failure with AQE + DPP and it is hard to understand what is going on just by stepping through code given the recursive nature of planning in AQE. Some logging should help.
Example:
```
25/05/22 16:36:37.402 ScalaTest-run-running-CometExpressionSuite INFO CometScanRule: 
INPUT: Project [md5(cast(col#23 as binary)) AS md5(col)#34]
+- FileScan parquet spark_catalog.default.test[col#23] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/home/andy/git/apache/datafusion-comet/spark-warehouse/test], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<col:string>
OUTPUT: Project [md5(cast(col#23 as binary)) AS md5(col)#34]
+- CometScan parquet spark_catalog.default.test[col#23] Batched: true, DataFilters: [], …
```
> feat: Add config option for showing all Comet plan transformations

- spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala
- spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala
Part of https://github.com/apache/datafusion-comet/issues/1542
Closes #.
Encrypted files are not currently supported and cause failure
If encryption is enabled, fallback to Spark.
Existing Spark SQL ParquetEncryptionSuite
> fix: fallback to Spark scan if encryption is enabled (native_datafusion/native_iceberg_compat)

- dev/diffs/3.5.5.diff
- spark/src/main/scala/org/apache/comet/rules/EliminateRedundantTransitions.scala
- spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala
Closes #1737 
The AQE feature in spark relies on a cache (where key is canonicalized version of a plan and value is the actual SparkPlan object itself) to avoid recomputation of stages and improve stage efficiency. However, with comet and spark plans' canonicalized version being the same, the AQE incorrectly fetches Comet Plan instead of native Spark ones causing Class type exceptions as mentioned in the related github issue. The goal of this change is to prevent that by handling AQE use case between the final handoff between Comet and Spark systems. Although this change solves the AQE usecase, the goal of the PR is to come up with a better suited strategy which includes but not limited to changing the canonicalization logic of Comet plans so that Spark can differentiate them
Changes to …
> fix: Fix Spark SQL AQE exchange reuse test failures

- .github/actions/java-test/action.yaml
- .github/workflows/pr_build_linux.yml
- .github/workflows/pr_build_macos.yml
N/A
We frequently see CI runs fail due to artifact uploads failing due to duplicate names.
- Make macOS workflow consistent with Linux workflow by specifying profiles
- Use profile name and suite name in artifact name
> chore: Use unique artifact names in Java test run

- common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala
- native/Cargo.lock
- native/Cargo.toml
- native/core/Cargo.toml
- native/core/src/execution/planner.rs
- native/core/src/parquet/mod.rs
- native/core/src/parquet/objectstore/mod.rs
- native/core/src/parquet/objectstore/s3.rs
- native/core/src/parquet/parquet_support.rs
- native/proto/src/proto/operator.proto
- pom.xml
- spark/pom.xml
- spark/src/main/scala/org/apache/comet/objectstore/NativeConfig.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/objectstore/NativeConfigSuite.scala
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadFromS3Suite.scala
Closes #1766.
The `native_datafusion` parquet scanner does not configure the object_store client using Hadoop S3A configurations. The AWS credentials for accessing S3 such as `spark.hadoop.fs.s3a.access.key` will be ignored by `native_datafusion`, which leads to authentication failures when reading data on S3.
This patch translates commonly used Hadoop S3A configurations (mostly for setting up credentials) to object_store counterpart. This is similar to what Apache Gluten does for supporting S3 (See https://gluten.apache.org/docs/getting-started/s3/#working-with-s3).
AWS allows accessing S3 using a variety of authentication methods, while object_store only supports some of them. We depend on `aws-config` and `aws-credential-types` to provide better support for our complex use cases of AWS …
> feat: Translate Hadoop S3A configurations to object_store configurations

- dev/diffs/3.4.3.diff
- dev/diffs/3.5.4.diff
- dev/diffs/3.5.5.diff
- dev/diffs/4.0.0-preview1.diff
Partially addresses #1542.
Updated diffs. Two of the tests rely on an accumulator that isn't maintained in Comet native scans, while the other tries to strip a filter after it's already been pushed into the native plan.
> chore: IgnoreCometNativeScan on a few more Spark SQL tests

- dev/diffs/3.5.5.diff
Addresses #1739 
Enables tests in `RemoveRedundantProjectsSuite.scala` related to #242. The Comet now falls back to Spark for Dynamic Partition Pruning. These tests can now be enabled.
The other ask to enable tests in `InjectRuntimeFilterSuite` were already addressed here: [#1837](https://github.com/apache/datafusion-comet/pull/1834)
Updates the apache-spark `3.5.5.diff` to enable tests.
1. Applied the updated `3.5.5.diff` to apache-spark-3.5
2. Ran the full `RemoveRedundantProjectsSuite` suite.
> chore: Enable tests in RemoveRedundantProjectsSuite.scala related to issue #242

- native/core/src/execution/shuffle/row.rs
- spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
Closes #1844 and probably #1823.
Loading data with custom schema may produce rows containing null struct fields. Shuffling such null struct fields throws exceptions mentioned in the linked issues.
Fixes appending null rows to `StructBuilder` by making children field builders always in sync with the parent struct builder.
1. Add unit tests for `append_field` in native code
2. Add a Scala unit test modified from the minimal repro of the bug
> fix: Fix shuffle writing rows containing null struct fields

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Workaround for https://github.com/apache/datafusion-comet/issues/1246
We do not currently have any type coercion for `RANGE BETWEEN` window expressions and queries fail if the types do not match. We also have very limited testing and only have support for int/long and not the other types that Spark supports, such as float/double and date/timestamp.
Fall back to Spark for now until we have time to implement with type coercion and adequate testing.
New test added in this PR.
> fix: Fall back to Spark for `RANGE BETWEEN` window expressions

- dev/diffs/3.4.3.diff
- dev/diffs/3.5.4.diff
- dev/diffs/3.5.5.diff
- dev/diffs/4.0.0-preview1.diff
Closes https://github.com/apache/datafusion-comet/issues/1852
`WholeStageCodegenSuite` contains tests that assert that certain operators, such as joins, appear in a `WholeStageCodegenExec`. Comet does not support codegen, so these tests will fail when running natively.
We had previously updated some of these tests to make them work by changing the assertions to state that it was ok for Comet operators to not be in a `WholeStageCodegenExec` and in other cases by disabling Comet, but these are changing the very nature of the tests.
Since we do not support codegen, we should not expect to pass the codegen tests.
> chore: Ignore Spark SQL WholeStageCodegenSuite tests

- common/src/main/scala/org/apache/comet/CometConf.scala
- dev/diffs/3.4.3.diff
- dev/diffs/3.5.4.diff
- dev/diffs/3.5.5.diff
- dev/diffs/3.5.6.diff
- dev/diffs/4.0.0-preview1.diff
- spark/src/main/scala/org/apache/comet/rules/CometExecRule.scala
- spark/src/main/scala/org/apache/comet/rules/EliminateRedundantTransitions.scala
- spark/src/main/scala/org/apache/spark/sql/comet/CometColumnarToRowExec.scala
- spark/src/test/scala/org/apache/spark/sql/CometTPCDSQuerySuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
- spark/src/test/scala/org/apache/spark/sql/comet/CometPlanStabilitySuite.scala
Part of https://github.com/apache/datafusion-comet/issues/1254
Closes https://github.com/apache/datafusion-comet/issues/1252
Closes https://github.com/apache/datafusion-comet/issues/1824
The config `COMET_SHUFFLE_FALLBACK_TO_COLUMNAR` was added as a hack so that we could avoid fixing some failing Spark SQL tests. However, the failing tests are real issues and only show up now because more queries are running natively.
This PR removes the hack and updates the diff files to either fix or ignore failing tests. Some of these tests will be enabled later as part of https://github.com/apache/datafusion-comet/issues/1254.
> fix: Remove COMET_SHUFFLE_FALLBACK_TO_COLUMNAR hack

- native/core/src/parquet/parquet_support.rs
- native/spark-expr/src/conversion_funcs/cast.rs
- spark/src/test/scala/org/apache/comet/CometCastSuite.scala
Closes #1875.
- `cast_struct_to_struct` was modified to support Parquet struct conversion before we split that logic off into parquet_support.rs. This brings the cast behavior back into alignment with Spark where field names don't matter.
- Renamed `cast_*` functions in parquet_support.rs and added some documentation to better differentiate those two files.
- New test case.
> fix: cast_struct_to_struct aligns to Spark behavior

- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
The mapping between Spark and Parquet for schemas with field ids did not correctly handle the schemas with nested arrays of structs. 
The added unit test fails without the fix. 
New unit test
> fix: correctly handle schemas with nested array of struct (native_iceberg_compat)

- native/core/src/execution/planner.rs
- native/proto/src/proto/expr.proto
- native/spark-expr/src/datetime_funcs/date_trunc.rs
- native/spark-expr/src/datetime_funcs/mod.rs
- native/spark-expr/src/lib.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Part of #1819 
Part of #1819 
Implement date_trunc as ScalarUDFImpl (date_trunc.rs)
org.apache.comet.CometExpressionSuite
> chore: Implement date_trunc as ScalarUDFImpl

- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
N/A
There were multiple issues with the `various math scalar functions` test:
- It was testing multiple expressions in one query, including `abs`, which is not supported, so the entire query fell back to Spark and did not test Comet
- The input data did not include boundary values
- The test ran with and without dictionary encoding enabled but did not have any duplicate values so was not actually using dictionary encoding
- There were no assertions that anything actually ran in Comet
I discovered a new bug during this work - https://github.com/apache/datafusion-comet/issues/1897
Rewrite the test to run one expression at a time and ensure that the query ran in Comet
> minor: Improve testing of math scalar functions

- kube/Dockerfile
change kube/Dockerfile to fix #1917 
- install and use GCC 10 for that [aws-lc-rs](https://github.com/aws/aws-lc-rs/blob/378163b244587013820902242de4f9ffb177ec14/aws-lc-sys/builder/cc_builder.rs#L488) would check compiler version when build, and would fail to build for GCC 9.4.0.
- install protoc
`docker build -t apache/datafusion-comet -f kube/Dockerfile .` successfully.
> minor: fix kube/Dockerfile build failed

- spark/src/main/scala/org/apache/comet/serde/aggregates.scala
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
N/A
Actually use `ignore_nulls`
that was used in:
- #1626
forward ignore_nulls in first and last and no longer mark as unsupported
this have the same problem as #1626, all the tests are disabled for first and last
> feat: pass ignore_nulls flag to first and last

- native/core/src/execution/jni_api.rs
- native/core/src/execution/planner.rs
- native/spark-expr/src/comet_scalar_funcs.rs
- native/spark-expr/src/lib.rs
N/A
Some registration exists in the `prepare_datafusion_session_context` and some in the `PhysicalPlanner::new`, moved to a single place - `prepare_datafusion_session_context`
1. Move `SparkExpm1` udf registration to `prepare_datafusion_session_context`
2. Move all Comet Spark UDFs like `SparkBitwiseNot`, `SparkBitwiseCount`, etc to register in `register_all_comet_functions` inside the `spark-expr` crate 
Existing tests
> chore: move udf registration to better place

- docs/source/user-guide/expressions.md
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/serde/arrays.scala
- spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala
Closes #.
adds support for array_distinct
new test case
> feat: supports array_distinct

- native/spark-expr/src/agg_funcs/sum_decimal.rs
- spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
`sum` may overflow in `merge_batch`
add overflow check to `evaluate`
org.apache.comet.exec.CometAggregateSuite
> fix: Add overflow check to evaluate of sum decimal accumulator

- native/spark-expr/src/conversion_funcs/cast.rs
I am really sorry for causing CI fail.
When scale = 6
```rust
let mul = 10_f64.powi(scale as i32);
```
mul = 1000000.000000000000000000000000000000000000000000 on rustc.
mul = 999999.999999999883584678173065185546875000000000  on miri nightly-2025-06-28, which causes the test to fail.
But why previous miri's CI success?
mul = 1000000.000000000465661287307739257812500000000000 on miri nightly-2025-06-24, which will pass the test.
The doc for f64::powi also says that [the precision of this function is non-deterministic](https://doc.rust-lang.org/std/primitive.f64.html#unspecified-precision).
It seems that it is a feature of miri that it applies random errors to imprecise operations.
Ignore the test case.
> fix: Ignore a test case fails on Miri

- dev/diffs/iceberg/1.8.1.diff
N/A
We need to patch Iceberg source to specify `useDecimal128 = true` in the Comet integration.
This PR updates the 1.8.1 diff file within Comet to apply this fix.
We also need to fix this in Apache Iceberg repo.
Tested manually. The Iceberg integration tests that we run in Comet CI did not detect this bug.
> fix: [Iceberg] Fix decimal corruption

- README.md
- docs/source/contributor-guide/benchmarking_aws_ec2.md
- docs/source/index.rst
- docs/source/user-guide/compatibility.md
- docs/source/user-guide/datasources.md
- docs/source/user-guide/datatypes.md
- docs/source/user-guide/iceberg.md
- docs/source/user-guide/installation.md
- docs/source/user-guide/kubernetes.md
- docs/source/user-guide/overview.md
- docs/source/user-guide/source.md
- docs/source/user-guide/tuning.md
Part of https://github.com/apache/datafusion-comet/issues/1856
Various documentation updates to reflect changes in 0.9.0
- Update info on native scans and complex type support
- Update Iceberg integration docs
> docs: Documentation updates for 0.9.0 release

- native/core/src/common/bit.rs
- native/core/src/execution/util/spark_bit_array.rs
- native/core/src/parquet/mutable_vector.rs
- native/core/src/parquet/read/levels.rs
- native/core/src/parquet/read/values.rs
Closes #1998.
Use standard rust implementation.
Related: https://github.com/apache/datafusion-comet/pull/1954
Remove `bit::ceil` from core and use `usize::div_ceil` instead.
> refactor: standardize div_ceil

- native/hdfs/src/object_store/hdfs.rs
The `get` and `read_range` methods in hdfs object store implementation do not always read the data requested because the underlying hdfs call may return fewer bytes than requested.
https://github.com/apache/datafusion-comet/pull/1992#issuecomment-3072724220
> fix: hdfs read into buffer fully

- dev/diffs/4.0.0.diff
- docs/spark_expressions_support.md
- native/core/src/execution/planner.rs
- native/proto/src/proto/expr.proto
- native/spark-expr/src/nondetermenistic_funcs/mod.rs
- native/spark-expr/src/nondetermenistic_funcs/monotonically_increasing_id.rs
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/serde/nondetermenistic.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #.
Added support for spark_partition_id and monotonically_increasing_id expressions
Spark-compatible spark_partition_id and monotonically_increasing_id expressions implementation and small refactoring of the scala serde-code related to non-deterministic functions.
Unit tests in scala and rust.
> feat: monotonically_increasing_id and spark_partition_id implementation

- spark/src/main/scala/org/apache/comet/serde/arrays.scala
- spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala
Part of: https://github.com/apache/datafusion-comet/issues/1902
Part of: https://github.com/apache/datafusion-comet/issues/1902
1. Add more test for array_contains function
2. Delete IncompatExpr
Add more unit tests
> Chore: Improve array contains test coverage

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/spark-3.4/org/apache/comet/shims/CometExprShim.scala
- spark/src/main/spark-3.5/org/apache/comet/shims/CometExprShim.scala
- spark/src/main/spark-4.0/org/apache/comet/shims/CometExprShim.scala
- spark/src/test/scala/org/apache/comet/CometFuzzTestSuite.scala
> fix: Add support for StringDecode in Spark 4.0.0

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/serde/strings.scala
- spark/src/main/spark-3.4/org/apache/comet/shims/CometExprShim.scala
- spark/src/main/spark-3.5/org/apache/comet/shims/CometExprShim.scala
- spark/src/main/spark-4.0/org/apache/comet/shims/CometExprShim.scala
Follow-up to https://github.com/apache/datafusion-comet/pull/2075.
See discussion https://github.com/apache/datafusion-comet/pull/2075#discussion_r2261157508.
Introduce `CommonStringExprs` and move `stringDecode()` to there.
> chore: Move `stringDecode()` to `CommonStringExprs` trait

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/serde/arithmetic.scala
- spark/src/main/scala/org/apache/comet/serde/arrays.scala
- spark/src/main/scala/org/apache/comet/serde/bitwise.scala
- spark/src/main/scala/org/apache/comet/serde/comparisons.scala
- spark/src/main/scala/org/apache/comet/serde/datetime.scala
- spark/src/main/scala/org/apache/comet/serde/hash.scala
- spark/src/main/scala/org/apache/comet/serde/maps.scala
- spark/src/main/scala/org/apache/comet/serde/nondetermenistic.scala
- spark/src/main/scala/org/apache/comet/serde/strings.scala
- spark/src/main/scala/org/apache/comet/serde/unixtime.scala
N/A
This PR adds a `T` type parameter to `CometExpressionSerde` so as to simplify its `convert()` implementations and to open up the way for further ones.
See above.
Existing UTs.
> chore: Add type parameter to `CometExpressionSerde`

- native/Cargo.toml
- spark/src/main/java/org/apache/spark/shuffle/comet/CometBoundedShuffleMemoryAllocator.java
- spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocatorTrait.java
- spark/src/main/java/org/apache/spark/shuffle/comet/CometUnifiedShuffleMemoryAllocator.java
- spark/src/main/java/org/apache/spark/sql/comet/execution/shuffle/SpillWriter.java
Closes https://github.com/apache/datafusion-comet/issues/2088
CometUnifiedShuffleMemoryAllocator was missing checks for blocks that have already been freed. We did already have these checks in CometBoundedShuffleMemoryAllocator.
> fix: Avoid double free in CometUnifiedShuffleMemoryAllocator

- docs/source/user-guide/iceberg.md
- Document current limitation
Closes #. https://github.com/apache/datafusion-comet/issues/2092
Comet and Iceberg integration is still WIP. We identified several issues that can be bypassed by configurations. Therefore, updated the docs to make these configurations clear to users.
Tested by Iceberg Spark tests w/ Comet enabled: https://github.com/apache/datafusion-comet/pull/1987
> docs: Update confs to bypass Iceberg Spark issues

- native/core/src/execution/planner.rs
N/A
I am mindful that this change is trivial and inconsequential. I am just enjoying my Sunday :coffee: and trying to understand the planner and I saw this `clone()` and now I cannot unsee it :see_no_evil: 
unittest
> trivial: remove unnecessary clone()

- spark/src/main/java/org/apache/spark/shuffle/comet/CometBoundedShuffleMemoryAllocator.java
- spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocatorTrait.java
- spark/src/main/java/org/apache/spark/shuffle/comet/CometUnifiedShuffleMemoryAllocator.java
- spark/src/main/java/org/apache/spark/sql/comet/execution/shuffle/SpillWriter.java
N/A
Backport fix to branch-0.9
Backport https://github.com/apache/datafusion-comet/pull/2122
> fix: [branch-0.9] Avoid double free in CometUnifiedShuffleMemoryAllocator

- spark/src/main/scala/org/apache/comet/DataTypeSupport.scala
- spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Closes https://github.com/apache/datafusion-comet/issues/2086
Fall back to Spark for schemas containing empty structs (seems like an artificial edge case)
I tested this fix manually with Iceberg
> fix: [iceberg] Fall back to spark for schemas with empty structs

- .github/workflows/benchmark.yml
Closes https://github.com/apache/datafusion-comet/issues/2206
Fix broken CI
Downgrade from gcc 14 to gcc 12 so that tpcds-kit can compile
> fix: Fix failing TPC-DS workflow in PR CI runs

- spark/src/main/scala/org/apache/comet/serde/hash.scala
Closes #2193 
With a recent change, the Sha2 fallback message is now not very user-friendly. This PR brings back the older message.
A simple fallback message change.
N/A
> fix: Make Sha2 fallback message more user-friendly

- pom.xml
Follow up on https://github.com/apache/datafusion-comet/pull/2252#pullrequestreview-3162500690.
Create a profile `strict-warning` which will fail on Scala code warns, keeping the code hygiene
> chore: Introduce `strict-warning` profile for Scala

- .github/workflows/spark_sql_test.yml
- .github/workflows/spark_sql_test_ansi.yml
- .github/workflows/spark_sql_test_native_datafusion.yml
- .github/workflows/spark_sql_test_native_iceberg_compat.yml
Closes #.
`ENABLE_COMET_SHUFFLE` has been removed since #1240
Remove useless `ENABLE_COMET_SHUFFLE` env
minor fix
> minor: Remove useless ENABLE_COMET_SHUFFLE env

- native/core/src/parquet/objectstore/s3.rs
- spark/src/test/scala/org/apache/comet/objectstore/NativeConfigSuite.scala
Closes #.
This functionality was incorrect. The validation logic was not checking for a custom S3 endpoint. It was just checking whether an S3 endpoint was specified. It would cause an error even when specifying the default AWS S3 endpoint.
> fix: Remove check for custom S3 endpoints

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/serde/math.scala
- spark/src/main/spark-3.4/org/apache/comet/shims/CometExprShim.scala
- spark/src/main/spark-3.5/org/apache/comet/shims/CometExprShim.scala
- spark/src/main/spark-4.0/org/apache/comet/shims/CometExprShim.scala
Part of https://github.com/apache/datafusion-comet/issues/2019
- Reduce the complexity of `QueryPlanSerde.scala`
Make use of Comet's `hex` and `unhex` expressions.
`CometExpressionSuite` and other unit tests passed.
> chore: Refactor `hex`/`unhex` SerDe to avoid code duplication

- native/core/Cargo.toml
- native/core/src/parquet/parquet_support.rs
Closes #2243.
I also noticed the [Apache OpenDAL](https://github.com/apache/opendal) project, which supports object_store and many file services. Perhaps we can integrate it to access more file services.
add hdfs-opendal feature to support hdfs with opendal
Successfully run CometReadHdfsBenchmark locally (tips: build native enable hdfs-opendal: cd native && cargo build --features hdfs-opendal)
> feat: Support hdfs with OpenDAL

- dev/benchmarks/comet-tpcds.sh
- dev/benchmarks/comet-tpch.sh
N/A
Fix regression in benchmarks
https://github.com/apache/datafusion-comet/pull/2242 removed the `spark.comet.cast.allowIncompatible `config. Cast now uses `spark.comet.expression.allowIncompatible` just like other expressions, therefore the scripts need updating.
> fix: Update benchmarking scripts

- spark/src/main/scala/org/apache/comet/rules/CometExecRule.scala
Closes #.
Some execs that comet will not accelerate, such as command execs. We should ignore fallback reason for them.
Ignore fallback reason for command execs
Minor improvement
> feat: Ignore fallback info for command execs

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/1854
- Add `BooleanType` for both functions.
- Add `TimestampNTZType` to `can_rank` function.
- Support sorting `MapType` on its values 
- Move existing temporal types to a separate case clause
- Exclude Spark's `YearMonthIntervalType` and `DayTimeIntervalType` b/c Comet Spark doesn't [support](https://datafusion.apache.org/comet/user-guide/latest/datatypes.html) them.
- Align Comet's `canRank`/`can_sort_to_indices` function w/ Arrow's [can_rank](https://github.com/apache/arrow-rs/blob/55.2.0/arrow-ord/src/rank.rs#L30-L40) and [can_sort_to_indices](https://github.com/apache/arrow-rs/blob/55.2.0/arrow-ord/src/sort.rs#L193-L215)
- Tested by sorting on Array/Map of previous unsupported types
- Make sure `CometSort` is in the SparkPlan
> chore: Align sort constraints w/ `arrow-rs`

- spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
- spark/src/main/scala/org/apache/comet/rules/CometExecRule.scala
- spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala
Closes #2300.
> Comet cannot accelerate ProjectExec because: Comet is not enabled
We do not need to add fallback info for spark plan node when Comet is not enabled
> Comet cannot accelerate ProjectExec because: Comet Scan is not enabled
`Comet Scan is not enabled` fallback reason should be placed in the scan node
> Comet cannot accelerate CometProjectExec because: Metadata column is not supported
ditto
> Comet cannot accelerate ShuffleExchangeExec because: spark.shuffle.manager is not set to org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager$
CometShuffleManager class name should be `org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager`
Improve some confusing fallback reasons
disable comet shuffle manager conf in `CometTestBase` and run the following test case: …
> feat: Improve some confusing fallback reasons

- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/main/scala/org/apache/comet/serde/namedExpressions.scala
Part of https://github.com/apache/datafusion-comet/issues/2019
See https://github.com/apache/datafusion-comet/issues/2019 for motivation
Refactors `alias` and `attributeReference`.
> chore: Refactor serde for named expressions `alias` and `attributeReference`

- .github/workflows/pr_build_linux.yml
- .github/workflows/pr_build_macos.yml
- spark/src/test/scala/org/apache/comet/parquet/ParquetReadFromFakeHadoopFsSuite.scala
Cherry pick https://github.com/apache/datafusion-comet/pull/2359
> fix: [branch-0.10] Ignore ParquetReadFromFakeHadoopFsSuite

- native/Cargo.lock
- native/core/Cargo.toml
Building with the `hdfs-opendal` feature enabled fails on MacOS. 
Add a `hdrs` dependency to allow the correct shared library to be found. See: https://opendal.apache.org/docs/rust/opendal/services/struct.Hdfs.html#macos-specific-note
> build: fix build of 'hdfs-opendal' feature for MacOS

- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
Closes #2389.
A reused broadcast plan with AQE disabled will start with ReusedExchangeExec
> fix: Check reused broadcast plan in non-AQE and make setNumPartitions thread safe

- common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
Closes #2401.
High cost of creating Configuration in NativeBatchReader 
New Configuration from shared conf to avoid the high cost of loading from resource files
Before this:
After this:
> perf: New Configuration from shared conf to avoid high costs

- docs/source/user-guide/latest/expressions.md
- spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #2330.
This is follow-up to #2316. Since datafusion has been upgraded to 50.0.0, we can enable WeekDay function
Enable WeekDay function
unit Test
> feat: Enable WeekDay function

- Makefile
Closes #.
Make native features available to all make commands
Respect native features env for cargo commands
> chore: Respect native features env for cargo commands

- spark/src/main/scala/org/apache/spark/sql/comet/CometBroadcastExchangeExec.scala
- spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
Closes #2408.
After [SPARK-48195](https://issues.apache.org/jira/browse/SPARK-48195), SparkPlan will cache the RDD, which prevents us from changing the number of partitions once CometBroadcastExchangeExec.executeColumnar() has been executed.
Add a method that always creates a new CometBatchRDD.
After this,  tpch q2 ran successfully on spark 4.0.1 with comet:
> fix: Avoid spark plan execution cache preventing CometBatchRDD numPartitions change

- common/src/main/scala/org/apache/comet/CometConf.scala
Closes #.
To make it easier for us to write test cases for comet expressions like #2410.
This test case ran successfully:
```
test("test array literal") {
withSQLConf(
CometConf.COMET_SPARK_TO_ARROW_ENABLED.key -> "true",
SQLConf.OPTIMIZER_EXCLUDED_RULES.key -> "org.apache.spark.sql.catalyst.optimizer.ConstantFolding") {
checkSparkAnswerAndOperator("select array('1', '2', '3')")
}
}
```
> minor: Add RDDScan to default value of sparkToColumnar.supportedOperatorList

- spark/src/main/scala/org/apache/comet/ExtendedExplainInfo.scala
- spark/src/main/scala/org/apache/comet/rules/CometExecRule.scala
Closes #2449.
Some improvements of fallback info:
+ Ignore unsupported info for `CometSparkRowToColumnar`: `CometSparkRowToColumnar is not supported`
+ `ReusedExchangeExec` will break the children extended Infos
> chore: Improvements of fallback info

- native/spark-expr/src/static_invoke/char_varchar_utils/read_side_padding.rs
- spark/src/main/scala/org/apache/comet/serde/strings.scala
- spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
[](https://github.com/apache/datafusion-comet/issues/2435)
Closes #.
PR : https://github.com/apache/datafusion-comet/issues/2435
https://github.com/apache/datafusion-comet/issues/2435
Unit testing
> feat:add_additional_char_support_rpad

- native/core/src/execution/memory_pools/mod.rs
- native/core/src/execution/memory_pools/unified_pool.rs
Related to https://github.com/apache/datafusion-comet/issues/2453
The main change in this PR is to update the memory accounting to use checked operations when adding/subtracting memory so that we check for overflows. I do not have any evidence that there was actually an issue with this, but in #2453 we do see cases where Comet tries to release more memory that it owns, so this is just an additional safeguard.
I also renamed `CometMemoryPool` to `CometUnifiedMemoryPool`, and renamed two methods to make it easier to comprehend the boundary with Spark's memory pool.
> chore: Use checked operations when growing or shrinking unified memory pool

- spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Closes #.
While working on https://github.com/apache/datafusion-comet/pull/2425, I encountered an error in `checkCometOperators`.
As a newcomer to the Comet project, I was unaware that `native_comet` does not support complex type scanning, and the current error message was unclear and difficult to understand.
This PR improves the error message by adding a fallback reason, making it friendlier to new developers.
the log message before this PR
```
- ToPrettyString (native_comet, jvm shuffle) *** FAILED *** (2 seconds, 79 milliseconds)
Expected only Comet native operators, but found Project.
plan: *(1) Project [toprettystring(c16#1030, Some(America/Los_Angeles)) AS pretty_c16#1220]
+- *(1) ColumnarToRow
+- FileScan parquet [c16#1030] Batched: true, DataFilters: [], Format: Parquet, Location: …
```
> minor: Improve the log message of `CometTestBase#checkCometOperators`

- spark/src/test/scala/org/apache/spark/sql/comet/CometPlanStabilitySuite.scala
N/A
In the plan stability suite, there is a check that the expected and actual simplified and explain plans match, but only the simplified plan gets logged. This means that when the actual vs expected explain plan is different, no information is logged to show the difference. I discovered this while working on https://github.com/apache/datafusion-comet/pull/2492
I split these changes out into a separate PR from https://github.com/apache/datafusion-comet/pull/2492 to make reviews easier.
> chore: Improve test assertions in plan stability suite

- spark/src/test/scala/org/apache/spark/sql/comet/CometPlanStabilitySuite.scala
Partial fix for https://github.com/apache/datafusion-comet/issues/2469
I will follow up with additional PRs to enable plan stability tests for other scan modes.
We currently do not run the plan stability tests in CI, which is a problem.
Enable plan stability tests and explicitly set scan mode to `auto`.
> fix: Enable plan stability tests for `auto` scan

- docs/source/user-guide/latest/expressions.md
- docs/spark_expressions_support.md
Docs update #2102 
Documentation changes to update lpad support
> docs:support lpad expression documentation update

- common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala
- common/src/main/spark-3.x/org/apache/comet/shims/CometTypeShim.scala
Partially closes #.https://github.com/apache/datafusion-comet/issues/2255
* To perform code clean / refactor on the codebase, in order to comply with the new maven profile https://github.com/apache/datafusion-comet/issues/2255, one module at a time.
* Add explicit cast (int -> long) to avoid the warning
* Add a suppress warning on shim and put up a comment to justify it. 
* `mvn test -pl :comet-common-spark3.5_2.12 -Pstrict-warnings` to make sure the common module is now comply with the `strict-warnings` profile setting
* CI is green
> Chore: Fix Scala code warnings - common module
