.github/pull_request_template.md
=> build: Remove license header from pull request template

pom.xml
=> build: Exclude .github from apache-rat-plugin check

spark/src/test/scala/org/apache/comet/exec/CometShuffleSuite.scala
Closes #.
The Java CI now takes 70-90min to finish, and `CometShuffleSuite` is taking the majority it, of which a big portion is spent in various suites for encryption. Given a lot of the test cases are orthogonal to shuffle encryption, this PR moves the encryption suite into a separate class without extending `CometShuffleSuiteBase`.
Moves `CometShuffleEncryptionSuite` into a separate class with one test case, instead of run all the tests under `CometShuffleSuiteBase`.
=> test: Reduce test time spent in `CometShuffleSuite`

spark/src/test/scala/org/apache/comet/exec/CometShuffleSuite.scala
Closes #.
This patch adds a test in BosonShuffleSuite to verify RoundRobinPartitioning is supported by columnar shuffle.
=> test: Add test for RoundRobinPartitioning

spark/src/main/scala/org/apache/comet/CometExecIterator.scala, spark/src/main/scala/org/apache/spark/sql/comet/operators.scala
Closes #.
Reduce the amount of duplicated code.
This PR does a simple refactoring by removing some duplicated code in the repo.
=> refactor: Remove a few duplicated occurrences

core/Cargo.lock, core/Cargo.toml, core/benches/parquet_read.rs, core/src/execution/datafusion/planner.rs, core/src/execution/operators/copy.rs, core/src/execution/operators/scan.rs, core/src/parquet/util/test_common/page_util.rs
Closes #.
Upgrade arrow-rs to 50.0.0 and DataFusion to 35.0.0
=> build: Upgrade arrow-rs to 50.0.0 and DataFusion to 35.0.0

README.md
Closes #.
Fixing @viirya comments provided after #125 being merged
=> doc: Minor fix Getting started reformatting

.github/workflows/benchmark.yml
Closes #.
Resolves comments in previous PR:#130
=> build: Refine names in benchmark.yml

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
=> fix: bitwise shift with different left/right types

.gitignore
=> fix: rat check error in vscode ide

spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
=> test: Disable spark ui in unit test by default

EXPRESSIONS.md
Closes #.
We added some more supported expressions. We should update the document.
=> doc: Update supported expressions

spark/src/test/scala/org/apache/spark/sql/CometTPCDSQuerySuite.scala
Closes #.
Most tests in `CometTPCDSQuerySuite ` are accidentally ignored by the commits in #213. This patch restores them.
=> test: Restore tests in CometTPCDSQuerySuite

spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
N/A
I see this output when Comet is disabled:
```
INFO CometSparkSessionExtensions: Comet extension is disabled, please turn on sspark.comet.enabled to enable it
```
The config property should be `spark.comet.enabled` and not `sspark.comet.enabled`.
Modify log message.
Manually
=> chore: Fix typo in info message

.asf.yaml
=> chore: Update Comet repo description

.asf.yaml
Closes #.
Getting email from ASF infra after merging PRs: 
```
An error occurred while running notifications feature in .asf.yaml!:
Invalid notification target '[commits@arrow.apache.org](mailto:commits@arrow.apache.org)'. Must be a valid @[datafusion.apache.org](http://datafusion.apache.org/) list!
```
So this updates `asf.yaml` to use `datafusion.apache.org`
=> build: Update asf.yaml to use `@datafusion.apache.org`

README.md
=> doc: Update DataFusion project name and url

spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
Closes #.
This is a follow up fix to #255. #255 added a case of `BatchScanExec` to catch all data source v2 scans other than Parquet and attach info with `withInfo`. It hides the following Iceberg scan handling. Because we don't have Iceberg test for now, so it was not caught.
We should rearrange the order of `BatchScanExec` patterns to make it correct.
=> fix: Iceberg scan transition should be in front of other data source v2

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Address scalafix identified errors
This ignore unused variables
Local build and scalafix scan
=> chore: Ignore unused variables

.asf.yaml
N/A
Publish documentation (eventually) to a `datafusion.apache.org/comet`.
Update `.asf.yaml`
=> chore: Update documentation publishing domain and path

docs/source/compatibility.md, docs/source/index.rst
Part of https://github.com/apache/datafusion-comet/issues/230
It is important to document areas where Comet is currently not guaranteed to produce the same results as Spark.
New documentation page.
I tested building the site manually.
=> feat: Add compatibility guide

docs/source/contributor-guide/debugging.md, docs/source/contributor-guide/plugin_overview.md, docs/source/index.rst
N/A
Make it easier for new contributors to understand how Comet works and where to start looking at code when adding new operators or expressions.
New "Comet Plugin Overview Page".
Manually tested publishing locally.
=> docs: Add a plugin overview page to the contributors guide

README.md
=> doc: add contributing in README.md

README.md
=> docs: fix the docs url of installation instructions

common/src/main/scala/org/apache/comet/CometConf.scala
=> chore: Make COMET_EXEC_BROADCAST_FORCE_ENABLED internal config

docs/source/contributor-guide/benchmarking.md, docs/source/index.rst
N/A
Explain how to run TPC-* benchmarks
New benchmarking guide
=> docs: Add benchmarking guide

core/src/execution/datafusion/planner.rs
=> fix: Incorrect input schema when preparing result expressions for HashAggregation

.github/workflows/pr_build.yml, pom.xml
Closes #525 
Reduce CI time and for local testing with spark 4.0.
=> chore: Upgrade spark to 4.0.0-preview1

core/Cargo.lock, core/Cargo.toml
=> build: Use DataFusion 39.0.0 release

core/src/execution/datafusion/expressions/correlation.rs, core/src/execution/datafusion/expressions/covariance.rs, core/src/execution/datafusion/planner.rs, core/src/execution/proto/expr.proto, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
=> feat: add nullOnDivideByZero for Covariance

core/src/execution/shuffle/list.rs, core/src/execution/shuffle/row.rs
Closes #.
Make it easier to debug issues reported by users
=> chore: remove some unwraps from shuffle module

pom.xml
=> build: Upgrade to 2.13.14 for scala-2.13 profile

native/Cargo.lock, native/Cargo.toml
N/A
DataFusion 40 was just released, so we don't need to use the release candidate now.
Use DataFusion 40.0.0 instead of 40.0.0-rc1
Existing tests
=> feat: Upgrade to DataFusion 40

Makefile
Closes https://github.com/apache/datafusion-comet/issues/662
=> fix: Remove nightly flag in release-nogit target in Makefile

kube/Dockerfile
=> fix: change the not exists base image apache/spark:3.4.3 to 3.4.2

native/core/benches/cast_from_string.rs, native/core/benches/cast_numeric.rs, native/core/benches/shuffle_writer.rs, native/core/src/errors.rs, native/core/src/execution/datafusion/spark_hash.rs, native/core/src/parquet/read/values.rs, native/spark-expr/src/cast.rs, native/spark-expr/src/kernels/temporal.rs
Part of https://github.com/apache/datafusion-comet/issues/700
Make rust clippy happy and improve some code style.
Code style changes.
Only clippy fix.
=> chore: Make rust clippy happy

native/spark-expr/Cargo.toml, native/spark-expr/benches/decimal_div.rs
N/A
I wanted to better understand the impact of https://github.com/apache/datafusion-comet/pull/741
New benchmark
N/A
=> chore: Add criterion benchmark for decimal_div

native/core/src/execution/datafusion/planner.rs, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/645.
=> feat: Support count AggregateUDF for window function

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/test/scala/org/apache/comet/exec/CometColumnarShuffleSuite.scala
=> fix: Unsupported types for SinglePartition should fallback to Spark

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Closes https://github.com/apache/datafusion-comet/issues/779
=> chore: Remove legacy code for adding a cast to a coalesce

native/Cargo.lock, native/Cargo.toml
=> chore: Use DataFusion 41.0.0-rc1

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
Closes #.
This patch complements unsupported cases to `supportedSortType` function. For the supported/unsupported cases, please check `arrow-ord/src/sort.rs` in arrow-rs.
=> chore: Add more unsupported cases to supportedSortType

.github/workflows/docker-publish.yml
N/A
Trying to fix docker image publishing. It was trying to push the images to docker.io instead of ghcr.io.
=> chore: Fix docker image publishing (specify ghcr.io in tag)

native/proto/src/lib.rs, native/spark-expr/src/cast.rs, native/spark-expr/src/if_expr.rs, native/spark-expr/src/lib.rs, native/spark-expr/src/regexp.rs, native/spark-expr/src/scalar_funcs.rs, native/spark-expr/src/scalar_funcs/hash_expressions.rs, native/spark-expr/src/structs.rs, native/spark-expr/src/temporal.rs
Related #690 .
Enable lint to make easier for the code reader/reviewer to identify if its lightweight clone or not
=> feat: Enable `clippy::clone_on_ref_ptr` on `proto` and `spark_exprs` crates

native/core/src/execution/datafusion/expressions/avg.rs, native/core/src/execution/datafusion/expressions/avg_decimal.rs, native/core/src/execution/datafusion/expressions/bitwise_not.rs, native/core/src/execution/datafusion/expressions/bloom_filter_might_contain.rs, native/core/src/execution/datafusion/expressions/checkoverflow.rs, native/core/src/execution/datafusion/expressions/correlation.rs, native/core/src/execution/datafusion/expressions/covariance.rs, native/core/src/execution/datafusion/expressions/negative.rs, native/core/src/execution/datafusion/expressions/normalize_nan.rs, native/core/src/execution/datafusion/expressions/stddev.rs, native/core/src/execution/datafusion/expressions/strings.rs, native/core/src/execution/datafusion/expressions/sum_decimal.rs, native/core/src/execution/datafusion/expressions/variance.rs, native/core/src/execution/datafusion/operators/expand.rs, native/core/src/execution/datafusion/planner.rs, native/core/src/execution/datafusion/shuffle_writer.rs, native/core/src/execution/jni_api.rs, native/core/src/execution/operators/copy.rs, native/core/src/execution/operators/filter.rs, native/core/src/execution/operators/scan.rs, native/core/src/lib.rs, native/core/src/parquet/read/column.rs, native/core/src/parquet/util/buffer.rs, native/core/src/parquet/util/memory.rs, native/core/src/parquet/util/test_common/page_util.rs
=> feat: Enable `clippy::clone_on_ref_ptr` on `core` crate

docs/source/user-guide/installation.md
It works fine with Spark 3.5 with the additional 2 conf props.
docs only
=> chore: Update installation.md

native/core/src/execution/datafusion/shuffle_writer.rs, spark/src/main/scala/org/apache/spark/sql/comet/CometCollectLimitExec.scala, spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala, spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala, spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala, spark/src/test/scala/org/apache/comet/exec/CometNativeShuffleSuite.scala
=> chore: Improve CometExchange metrics

docs/source/user-guide/kubernetes.md
Closes #689 .
Document how to deploy Apache Spark with Comet accelerator to the Kubernetes using Helm
=> doc: Documenting Helm chart for Comet Kube execution

native/core/src/execution/jni_api.rs
=> chore: Remove unused function

native/spark-expr/src/list.rs
N/A
Build is failing in main branch
=> build: fix build

docs/source/contributor-guide/development.md
Closes #.
We moved native code but haven't updated the path in the doc.
=> doc: Update native code path in development

pom.xml
Closes #.
Similar to #911, but for Scala.
=> build: Set Java version arg for scala-maven-plugin

native/core/src/execution/metrics/utils.rs, native/core/src/jvm_bridge/comet_metric_node.rs, spark/src/main/scala/org/apache/spark/sql/comet/CometMetricNode.scala
N/A
I lost some time today debugging a metrics issue where I thought that metrics were being lost between native and jvm because the calls to `add` from native did not match the final value in jvm. It was not obvious to me that `add` was actually calling `set` and replacing previous values. 
Rename a method and add some docs.
=> minor: rename CometMetricNode `add` to `set` and update documentation

native/Cargo.lock, native/Cargo.toml, native/core/benches/bit_util.rs, native/core/src/common/bit.rs, native/core/src/execution/datafusion/planner.rs
N/A
Check for any regressions before the 42.0.0 release is finalized.
=> chore: Upgrade to DataFusion 42.0.0

spark/pom.xml
N/A
Fixes a regression introduced in https://github.com/apache/datafusion-comet/pull/941 that caused the jar file to be missing Comet classes
=> build: Fix regression in jar packaging

dev/changelog/0.3.0.md
N/A
Preparing for next release
=> chore: Generate changelog for 0.3.0 release

docs/source/user-guide/expressions.md
This is a followup PR of #960 
#960 fixed the issue, updating expressions.md
=> chore: update rem expression guide

kube/Dockerfile
N/A
Dockerfile is incorrect and does not currently add Comet jar file to the image
=> minor: Remove hard-coded version number from Dockerfile

native/core/src/execution/operators/copy.rs, spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
=> fix: TopK operator should return correct results on dictionary column with nulls

native/Cargo.lock, native/Cargo.toml
=> feat: Use official DataFusion 43 release

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
N/A
Follows on from https://github.com/apache/datafusion-comet/pull/1065
=> chore: Refactor binary and math expression serde code

dev/changelog/0.4.0.md
Part of https://github.com/apache/datafusion-comet/issues/1071
Getting ready to create 0.4.0 release candidate
Add changelog for 0.4.0
=> chore: Add changelog for 0.4.0

.github/actions/setup-spark-builder/action.yaml, .github/workflows/spark_sql_test.yml, .github/workflows/spark_sql_test_ansi.yml, benchmarks/README.md, common/pom.xml, dev/diffs/3.4.3.diff, dev/diffs/3.5.1.diff, dev/diffs/4.0.0-preview1.diff, docs/source/contributor-guide/debugging.md, docs/source/user-guide/installation.md, fuzz-testing/README.md, fuzz-testing/pom.xml, native/Cargo.lock, native/Cargo.toml, pom.xml, spark-integration/pom.xml, spark/pom.xml
N/A
Bump version number now that we have cut the `branch-0.4` branch.
=> chore: Prepare for 0.5.0 development

dev/release/README.md
N/A
I couldn't remember where to find the GPG key. This will help me (or the next release manager) next time.
=> minor: Add hint for finding the GPG key to use when publishing to maven

README.md
=> docs: Fix readme typo FGPA -> FPGA

pom.xml
Closes #1188.
bump protobuf version to 3.21.12 (same as in spark 3.4.3 https://github.com/apache/spark/blob/v3.4.3/pom.xml#L127)
=> build(deps): bump protobuf version to 3.21.12

spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala, spark/src/main/scala/org/apache/comet/DataTypeSupport.scala, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala, spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala
N/A
Fix failing tests in DisableAQECometShuffleSuite
=> [comet-parquet-exec] Fix regressions in DisableAQECometShuffleSuite

spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/1258
A test failure is happening on main due to merging conflicting PRs https://github.com/apache/datafusion-comet/commit/d15d05116f0e8104e6c15cf323f6106262807a93 and https://github.com/apache/datafusion-comet/commit/be488390dcd89b2a5bff6f24b9ae7724383cffde
Update a test
=> build: Fix test failure caused by merging conflicting PRs

dev/changelog/0.4.0.md, dev/changelog/0.5.0.md
Part of https://github.com/apache/datafusion-comet/issues/1233
=> chore: Add changelog for 0.5.0

.github/workflows/spark_sql_test.yml, .github/workflows/spark_sql_test_ansi.yml, common/pom.xml, docs/source/contributor-guide/debugging.md, docs/source/user-guide/compatibility.md, docs/source/user-guide/installation.md, fuzz-testing/pom.xml, native/Cargo.lock, native/Cargo.toml, pom.xml, spark-integration/pom.xml, spark/pom.xml
N/A
Update version numbers now that we have created the `branch-0.5` release branch.
=> chore: Start 0.6.0 development

docs/source/user-guide/compatibility.md
Leftover from https://github.com/apache/datafusion-comet/pull/1281
=> minor: update compatibility

native/Cargo.lock, native/Cargo.toml
N/A
Make it explicit that we want to use `53.4.0`
=> chore: Upgrade to Arrow 53.4.0

docs/source/user-guide/compatibility.md
=> minor: commit compatibility doc

fuzz-testing/pom.xml
Closes #.
fuzz comet dependency version was hardcoded
changed to `project.version`
existing test
=> minor: update fuzz dependency

common/src/main/scala/org/apache/comet/CometConf.scala, docs/source/user-guide/compatibility.md, docs/source/user-guide/configs.md, docs/templates/compatibility-template.md, docs/templates/configs-template.md, spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala, spark/src/main/scala/org/apache/comet/DataTypeSupport.scala, spark/src/test/scala/org/apache/comet/CometCastSuite.scala, spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala, spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala, spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Follow-on PR to https://github.com/apache/datafusion-comet/pull/1376 to address review comments.
=> fix: Change default value of COMET_SCAN_ALLOW_INCOMPATIBLE and add documentation

spark/src/test/scala/org/apache/spark/sql/benchmark/CometReadBenchmark.scala
[CometReadBenchmark-jdk11-results.txt](https://github.com/user-attachments/files/18045981/CometReadBenchmark-jdk11-results.txt)
=> test: Add experimental native scans to CometReadBenchmark

.github/workflows/docker-publish.yml
=> chore: docker no space left on device

.github/workflows/docker-publish.yml
=> chore: debug no space left on device

.github/workflows/docker-publish.yml
=> chore: fix docker

.github/workflows/docker-publish.yml
=> chore: fixes for kube build

.github/workflows/docker-publish.yml, kube/Dockerfile
Adding faster maven mirror and enabling some caching
Closes #.
=> chore: faster maven mirror

docs/source/user-guide/expressions.md, fuzz-testing/src/main/scala/org/apache/comet/fuzz/Meta.scala
Follow-up to  #1422
Add div operator for fuzz-testing and update expression doc
minor fix
=> feat: Add div operator for fuzz testing and update expression doc

kube/Dockerfile
N/A
The recent change to the rust-toolchain file broke the Docker build for me.
Stop copying rust-toolchain to Dockerfie.
=> fix: Stop copying rust-toolchain to docker file

spark/src/main/scala/org/apache/spark/Plugins.scala
N/A
Remove hard-coded value and reference default value in config instead. This is consistent with how other configs were being referenced.
=> minor: Remove hard-coded config default

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
Closes #1506.
keep same logic as spark
check overflow for decimal integral division
=> fix: check overflow for decimal integral division

dev/release/build-release-comet.sh
N/A
Fixes for issues encountered when releasing 0.7.0
- specify `--no-cache` when building docker images so that the Docker image is built with the correct Rust version and doesn't trigger an upgrade later (which fails with a cross-device linking issue that I do not fully understand).
=> chore: fix issue in release process

.asf.yaml
Closes https://github.com/apache/datafusion-comet/issues/1533
=> chore: Re-enable GitHub discussions

dev/changelog/0.7.0.md
Part of https://github.com/apache/datafusion-comet/issues/1420
=> docs: Add changelog for 0.7.0 release

docs/source/user-guide/kubernetes.md
Related to #1546.
Update `kubernetes.md` to reflect latest changes
=> doc: Renew `kubernetes.md`

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
=> minor: fix typo

native/core/src/parquet/mod.rs
Part of https://github.com/apache/datafusion-comet/issues/1553
`register_object_store` and `file scan` should use the same `session_env` to ensure that `file scan` can get registered `object_store` from `session_env`
make register_object_store use same session_env as file scan
Locally passed scan benchmark on hdfs
=> fix: make register_object_store use same session_env as file scan

docs/source/user-guide/installation.md
Part of https://github.com/apache/datafusion-comet/issues/1579
Follows on from https://github.com/apache/datafusion-comet/pull/1573
=> docs: Update supported Spark versions

native/core/src/execution/shuffle/row.rs, spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala
Closes #1551.
Fixing STRUCT of ARRAY schema issue
=> feat: Fix struct of arrays schema issue

spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala
Related #1550 .
Adding array/struct tests with deeper nested levels
=> feat: adding more struct/arrays tests

spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
N/A
In `QueryPlanSerde`, we have a common pattern of:
```scala
val newOp = transform1(op)
newOp match {
case Some(nativeOp) =>
CometProjectExec(
nativeOp,
op,
op.output,
op.projectList,
op.child,
SerializedPlan(None))
case None =>
op
}
```
The name `transform1` has always confused me, so I renamed this to `operatorToProto`.
These sections of code follow the following pattern: if the `op` can be translated to proto, then apply some function to the resulting proto; otherwise, return the original plan.
```scala
operatorToProto(op) match {
case Some(x) => f(x)
case None => op
}
```
It is more idiomatic to use:
```scala
operatorToProto(op).map(x => f(x)).getOrElse(op)
```
Also, this is a common enough operation that it makes sense to factor out into a separate method, so I did that as well. …
=> chore: Refactor QueryPlanSerde to use idiomatic Scala and reduce verbosity

common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala, docs/source/user-guide/datatypes.md, docs/source/user-guide/installation.md, spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/main/scala/org/apache/comet/testing/ParquetGenerator.scala, spark/src/test/scala/org/apache/comet/CometFuzzTestSuite.scala
Part of https://github.com/apache/datafusion-comet/issues/1373
Closes https://github.com/apache/datafusion-comet/issues/1289
Closes https://github.com/apache/datafusion-comet/issues/1613
Closes https://github.com/apache/datafusion-comet/issues/1611 (actually, I can no longer reproduce this issue)
This is a starting point for fuzz testing as part of our standard test suite.
=> chore: Create simple fuzz test as part of test suite

common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala, spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala, spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala, spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
Related #1595.
Adding a first level MAP datatype support for native DataFusion reader
=> feat: add MAP type support for first level

docs/source/contributor-guide/benchmarking.md, docs/source/contributor-guide/benchmarking_aws_ec2.md, docs/source/contributor-guide/benchmarking_in_aws.md
Closes https://github.com/apache/datafusion-comet/issues/1583
=> docs: docs for benchmarking in aws ec2

spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala
Related to #1595 .
Adding unit tests for more nested types combinations
=> feat: Add more tests for nested types combinations for `native_datafusion`

native/core/src/execution/shuffle/map.rs, native/core/src/execution/shuffle/row.rs, spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala
Closes #1633 .
MapBuilder by default uses nullable columns to represent Map entries. Overriding this behavior using incoming values field
=> feat: Override MapBuilder values field with expected schema

native/core/src/execution/planner.rs
Closes #.
When was working on #1360 found that `execution_props` not used and basically can be used from `SessionContext`
And some general cleaning
=> chore: clean up `planner.rs`

docs/source/user-guide/compatibility.md, docs/templates/compatibility-template.md
=> docs: Update compatibility docs for new native scans

dev/changelog/0.8.0.md
=> docs: Add changelog for 0.8.0

common/pom.xml, dev/diffs/3.4.3.diff, dev/diffs/3.5.4.diff, dev/diffs/3.5.5.diff, dev/diffs/4.0.0-preview1.diff, dev/release/README.md, docs/source/contributor-guide/debugging.md, docs/source/user-guide/installation.md, fuzz-testing/pom.xml, native/Cargo.toml, pom.xml, spark-integration/pom.xml, spark/pom.xml
N/A
Now that the release branch `branch-0.8` has been created, it is time to switch `main` to `0.9.0`.
=> chore: Start 0.9.0 development

spark/src/main/scala/org/apache/comet/serde/arrays.scala
=> chore: fix build errors

spark/src/main/scala/org/apache/comet/CometSparkSessionExtensions.scala
Does not close anything, but is probably a step towards #1669.
There is needless nesting and variable assignment, since this is a huge function already we probably want to keep things compact.
Checking the two boolean conditions with an or operator feels a bit cleaner
The conversion should not change at all, so normal tests passing should be enough.
=> chore: Make Aggregate transformation more compact

dev/release/rat_exclude_files.txt
Closes #. https://github.com/apache/datafusion-comet/issues/1678
Update Rat's exclude files so that `create-tarball.sh` works
Exclude 3 more files
```shell
(venv) ➜  release git:(update_rat_exclude_files) ✗ ./run-rat.sh ../dist/apache-datafusion-comet-0.8.0-rc1/apache-datafusion-comet-0.8.0.tar.gz
3 unapproved licences. Check rat report: rat.txt
NOT APPROVED: docs/source/_static/images/comet-dataflow.excalidraw (apache-datafusion-comet-0.8.0/docs/source/_static/images/comet-dataflow.excalidraw): false
NOT APPROVED: native/core/testdata/backtrace.txt (apache-datafusion-comet-0.8.0/native/core/testdata/backtrace.txt): false
NOT APPROVED: native/core/testdata/stacktrace.txt (apache-datafusion-comet-0.8.0/native/core/testdata/stacktrace.txt): false
(venv) ➜  release …
```
=> chore: update dev/release/rat_exclude_files.txt

.github/workflows/benchmark.yml, common/pom.xml, dev/changelog/0.8.1.md, dev/diffs/3.4.3.diff, dev/diffs/3.5.4.diff, dev/diffs/3.5.5.diff, dev/diffs/4.0.0-preview1.diff, fuzz-testing/pom.xml, native/Cargo.lock, native/Cargo.toml, pom.xml, spark-integration/pom.xml, spark/pom.xml
N/A
We want to create a 0.8.1 release with a fix needed by Iceberg.
- Update version from 0.8.0 to 0.8.1
- Add changelog
=> chore: Prepare 0.8.1 release [branch-0.8]

common/src/main/scala/org/apache/comet/CometConf.scala, native/core/benches/row_columnar.rs, native/core/benches/shuffle_writer.rs, native/core/src/execution/jni_api.rs, native/core/src/execution/planner.rs, native/core/src/execution/shuffle/codec.rs, native/core/src/execution/shuffle/mod.rs, native/core/src/execution/shuffle/row.rs, native/core/src/execution/shuffle/shuffle_writer.rs, native/core/src/parquet/util/jni.rs, native/proto/src/proto/operator.proto, spark/src/main/java/org/apache/spark/sql/comet/execution/shuffle/SpillWriter.java, spark/src/main/scala/org/apache/comet/Native.scala, spark/src/main/scala/org/apache/comet/rules/CometExecRule.scala, spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometNativeShuffleWriter.scala
N/A
Now that we are using a version of Arrow that lets us skip validation on IPC reads, there is little justification in continuing to maintain our "fast encoding" option, since there is no longer any noticeable improvement in performance using this option.
=> chore: Remove fast encoding option

.github/workflows/spark_sql_test_native_datafusion.yml
Closes #. N/A
Make sure CI job name matches the actual scan implementation in test
Fix a typo
N/A
=> chore: fix CI job name

docs/source/contributor-guide/spark-sql-tests.md
=> docs: Add note on setting `core.abbrev` when generating diffs

native/core/src/lib.rs
=> chore: allow large errors for Clippy

spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala
N/A
Enable some complex tests that were previously ignored
=> chore: Enable more complex type tests

.github/workflows/spark_sql_test.yml
N/A
Some of the Spark SQL test suites are already passing when using `native_iceberg_compat`, so we may as well make those part of CI now.
=> chore: Enable partial Spark SQL tests for `native_iceberg_compat` scan

spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala
Related to https://github.com/apache/datafusion-comet/issues/1776
Skip the test to unblock other PRs.
Skip a test.
=> build: Ignore array_repeat test to fix CI issues

native/Cargo.lock, native/Cargo.toml, native/core/Cargo.toml, native/core/src/execution/planner.rs, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala, spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
Part of https://github.com/apache/datafusion-comet/issues/1704
Demonstrate using an expression from the new `datafusion-spark` crate.
=> feat: Add support for `expm1` expression from `datafusion-spark` crate

docs/source/contributor-guide/benchmarking_macos.md
Closes [#1796](https://github.com/apache/datafusion-comet/issues/1796)
=> fix: cargo install tpchgen-cli in benchmark doc

native/core/src/execution/planner.rs, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala, spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
=> fix: support `map_keys`

common/src/main/java/org/apache/comet/parquet/NativeBatchReader.java
Partially address #1542.
We validate the parquet type after fetching the batch from native, which can generate a Comet exception. Spark SQL tests expect the type validation exception to be generated first, so move the check up.
It seems overkill to do this on every batch, so I tried moving it to init but that didn't work. I will open an issue to maybe flip a boolean flag that we've checked this type to not do it on subsequent batches.
Fixed Spark SQL test `SPARK-34212 Parquet should read decimals correctly` for `native_iceberg_compat`.
=> fix: native_iceberg_compat: move checking parquet types above fetching batch

native/core/src/execution/jni_api.rs, spark/src/main/scala/org/apache/comet/rules/CometExecRule.scala, spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala
Closes https://github.com/apache/datafusion-comet/issues/1251
Fix a Spark SQL test failure when jvm shuffle is enabled.
New test and bug fix.
=> fix: Handle case where num_cols == 0 in native execution

native/Cargo.lock, native/Cargo.toml, native/core/Cargo.toml, native/core/src/execution/planner.rs, native/core/src/parquet/parquet_exec.rs, native/core/src/parquet/schema_adapter.rs
N/A
Update to release candidate so we have time to test before the final release.
=> chore: Upgrade to DataFusion 48.0.0-rc3

native/Cargo.lock, native/core/src/execution/planner.rs, native/core/src/parquet/parquet_support.rs, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala, spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala, spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala
=> fix: support read Struct by user schema

native/core/src/execution/planner.rs
Followup on https://github.com/apache/datafusion-comet/pull/1860#discussion_r2133040038.
Refactor planner read tests to improve readability and factor out reusable code
=> chore: refactor planner read schema tests

docs/source/user-guide/compatibility.md, docs/templates/compatibility-template.md
=> docs: Add docs stating that Comet does not support reading decimals encoded in Parquet BINARY format

native/core/src/execution/planner.rs, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala
=> feat: Add support to lookup map by key

common/pom.xml, dev/diffs/3.4.3.diff, dev/diffs/3.5.6.diff, dev/diffs/4.0.0.diff, dev/diffs/iceberg/1.8.1.diff, docs/source/contributor-guide/debugging.md, docs/source/user-guide/iceberg.md, docs/source/user-guide/installation.md, fuzz-testing/pom.xml, pom.xml, spark-integration/pom.xml, spark/pom.xml
=> chore: [branch-0.9] Prepare 0.9.0 rc2

docs/source/user-guide/compatibility.md, docs/source/user-guide/configs.md
Part of https://github.com/apache/datafusion-comet/issues/2016
Follow on from https://github.com/apache/datafusion-comet/pull/2017 to remove a warning that is no longer needed
=> docs: Remove legacy comment in docs

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/main/scala/org/apache/comet/serde/maps.scala, spark/src/test/scala/org/apache/comet/parquet/ParquetReadSuite.scala
=> feat: support `map_entries`

docs/source/user-guide/expressions.md
Doc changes to provide casting differences with integral division
Closes #.
Doc changes to provide casting differences with integral division
Doc changes only
We typically require tests for all PRs in order to:
1. Prevent the code from being accidentally broken by subsequent changes
2. Serve as another way to document the expected behavior of the code
If tests are not included in your PR, please explain why (for example, are they covered by existing tests)?
=> docs : Change notes for `IntegralDivide`

.github/dependabot.yml
=> chore: Adding dependabot

docs/source/contributor-guide/benchmarking_macos.md
=> doc: Alternative way to start Spark Master to run benchmarks

native/core/src/common/buffer.rs
N/A
It seemed like a good idea at the time to ask Claude Code to suggest safety improvements to `CometBuffer`. It turned out to be a distraction, but I found that some of the unsafe code was test code only so I moved it into the test module.
- move test code to test module and replace a debug_assert with assert
=> minor: CometBuffer code cleanup

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala
#2057 brought a merge error reintroducing some methods refactored in https://github.com/apache/datafusion-comet/pull/2028
Closes #.
=> chore: fix `QueryPlanSerde` merge error

native/core/src/execution/planner.rs
Closes https://github.com/apache/datafusion-comet/issues/2151
=> fix: Add CopyExec to inputs to SortMergeJoinExec

docs/source/contributor-guide/contributing.md, docs/source/contributor-guide/roadmap.md, docs/source/index.rst
Closes https://github.com/apache/datafusion-comet/issues/2185
Help contributors determine the best place to start contributing
=> docs: Add Roadmap

native/spark-expr/src/conditional_funcs/if_expr.rs
N/A
It seems like a mistake
just
no
=> fix: if expr nullable

native/Cargo.lock, native/Cargo.toml, native/core/Cargo.toml, spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala
=> chore: Upgrade to 49.0.2

spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/main/scala/org/apache/comet/serde/conditional.scala
Part of https://github.com/apache/datafusion-comet/issues/2019
See https://github.com/apache/datafusion-comet/issues/2019
- If
- CaseWhen
=> chore: Refactor serde for conditional expressions

docs/build.sh, docs/source/user-guide/compatibility.md, docs/source/user-guide/configs.md, docs/source/user-guide/datasources.md, docs/source/user-guide/datatypes.md, docs/source/user-guide/expressions.md, docs/source/user-guide/gluten_comparison.md, docs/source/user-guide/iceberg.md, docs/source/user-guide/index.md, docs/source/user-guide/installation.md, docs/source/user-guide/kubernetes.md, docs/source/user-guide/metrics.md, docs/source/user-guide/operators.md, docs/source/user-guide/overview.md, docs/source/user-guide/source.md, docs/source/user-guide/tuning.md
Part of https://github.com/apache/datafusion-comet/issues/2319
Now that the user guide moved from `/user-guide` to `/user-guide/latest`, users will get 404 errors for old content that is bookmarked or linked to from other places (such as LinkedIn posts).
For example, I have a [LinkedIn post](https://www.linkedin.com/posts/andygrove_comparison-of-comet-and-gluten-activity-7355591426836975616-pDCG?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAAUW0kBWspUNLfHWPAAzEHaIEe8u4PxUAI) that has a direct link to https://datafusion.apache.org/comet/user-guide/gluten_comparison.html but this page no longer exists.
- Add pages in `user-guide/` that contain a link to the new location, either in `user-guide/latest` or at the top level for the overviea page and the Gluten comparison page
There is …
=> docs: Add manual redirects from old pages that no longer exist

common/pom.xml, dev/diffs/3.4.3.diff, dev/diffs/3.5.6.diff, dev/diffs/4.0.0.diff, dev/diffs/iceberg/1.8.1.diff, docs/source/contributor-guide/debugging.md, docs/source/index.rst, fuzz-testing/pom.xml, pom.xml, spark-integration/pom.xml, spark/pom.xml
Part of https://github.com/apache/datafusion-comet/issues/1970
Prepare for release
=> chore: [branch-0.10] Bump version to 0.10.0

.github/workflows/pr_build_linux.yml, .github/workflows/pr_build_macos.yml, spark/src/test/scala/org/apache/comet/parquet/ParquetReadFromFakeHadoopFsSuite.scala
=> fix: temporarily ignore test for hdfs file systems

spark/src/main/scala/org/apache/comet/serde/literals.scala, spark/src/test/scala/org/apache/comet/exec/CometNativeReaderSuite.scala
=> fix: Byte array Literals failed on cast

.github/actions/rust-test/action.yaml, .github/workflows/validate_workflows.yml
Follow up on https://github.com/apache/datafusion-comet/pull/2434
Closes #.
=> chore: add validate_workflows.yml

common/pom.xml, dev/diffs/3.4.3.diff, dev/diffs/3.5.6.diff, dev/diffs/4.0.1.diff, dev/diffs/iceberg/1.8.1.diff, fuzz-testing/pom.xml, native/Cargo.lock, native/Cargo.toml, pom.xml, spark-integration/pom.xml, spark/pom.xml
Closes #.
Preparing for 0.10.1-rc1
- Bump Maven and Crate versions
- Run `cargo update`
=> build: [branch-0.10] Bump version to 0.10.1

dev/benchmarks/tpcbench.py
Fix regression introduced in https://github.com/apache/datafusion-comet/pull/2491
Script fails without this fix
=> fix: fix regression in tpcbench.py

docs/source/user-guide/latest/expressions.md, spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala, spark/src/main/scala/org/apache/comet/serde/arrays.scala
Part of https://github.com/apache/datafusion-comet/issues/2019
See https://github.com/apache/datafusion-comet/issues/2019
=> chore: Refactor serde for `ArrayCompact` and `ArrayFilter`
